### ISSUE TITLE
Call AddGrpc in AddCodeFirstGrpc

### ISSUE THREAD

**Issue by JamesNK** [protobuf-net/protobuf-net.Grpc#1]
AddCodeFirstGrpc only makes sense when AddGrpc is called so AddCodeFirstGrpc might as well do it. It will simplify your examples.

If you look at ASP.NET Core source code you will see that nested service registration is a common thing.

**Comment by mgravell** [comment]
Question: what happens if AddGrpc gets called twice? any problems? i.e. is there any scenario in which this could blow up?

**Comment by JamesNK** [comment]
It should be fine. If it isn't then it is a bug in AddGrpc.

**Comment by mgravell** [comment]
done
