### ISSUE TITLE
Generate .proto file from annotated C# class

### ISSUE THREAD

**Issue by jfalameda** [protobuf-net/protobuf-net.Grpc#103]
Hi,

It would be great to be able to generate a proto file from an annotated C# class. I cannot find any documentation regarding how to do it.

Is this possible to achieve?

Kind regards,
José.

**Comment by mgravell** [comment]
This sounds like a dup of #5

Right now, you can only do this for the data contracts, not the service contracts. This is definitely a feature we want, it just isn't there yet. Closing to keep all the discussion in one place, but please feel free to chime in on #5
