### ISSUE TITLE
I cannot find a way to return empty response

### ISSUE THREAD

**Issue by jfalameda** [protobuf-net/protobuf-net.Grpc#105]
Hi!

I have been taking a look at the repo and I cannot find clear documentation about it. As in proto files with the Empty type, is there any way to create a method that does not return a value? What would be the .NET equivalent to be serialized into Empty?

Thanks!

**Comment by mgravell** [comment]
Void, Task, or ValueTask should work

**Comment by mgravell** [comment]
If you look for `.google.protobuf.Empty` on https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted.html, it has more detail

**Comment by mgravell** [comment]
I'm assuming that this worked fine; if not, ping me and we can reopen

**Comment by jfalameda** [comment]
Thanks. That did the job.
