### ISSUE TITLE
Please add a non generic AddCodeFirst extension

### ISSUE THREAD

**Issue by TFTomSun** [protobuf-net/protobuf-net.Grpc#106]
First of all, great  project. I work with it now since two days and up to now it feels really well designed.

Here's my proposal: 
I saw that the generic is not really required. Instead of using typeof(TService), service.GetType() could be used instead, given that the service is not null. I would like to suggest 2 extensions. One generic, where the service can be null and one non generic where a service instance is mandatory. That would allow the consumer of the API to work with a object based service collection that could be added as CodeFirst then.

**Comment by mgravell** [comment]
Sure, we can do that!
