### ISSUE TITLE
DataMembers of base types are ignored

### ISSUE THREAD

**Issue by TFTomSun** [protobuf-net/protobuf-net.Grpc#107]
I just tried to create a streaming service with the following data:

```csharp
[DataContract]
    public class StringData :Base
    {

    }
    [DataContract]
    public class Base
    {
        [DataMember(Order = 1)]
        public string Value { get; set; }

    }

```

Unfortunately the Value is not transmitted. When I move the Value property to the StringData class it works fine. Is there any workaround for that?

**Comment by mgravell** [comment]
Hi - the serializer (protobuf-net) needs more context to understand inheritance based models; this simply means adding:

``` c#
[ProtoInclude(10, typeof(StringData))]
```

to `Base`, where there is no significance to the `10` other than it must be unique inside `Base`. In `.proto` terms, this then becomes:

``` proto
message Base {
   string Value = 1;
   oneof subtype {
      StringData StringData = 10;
   }
}
message StringData {
}
```

**Comment by TFTomSun** [comment]
hm.... I think for some cases i might need to use another serializer then. I would like to use generics, too. e.g.:

```
 [DataContract]
    public class StringData :Data<string>
    {

    }

    [DataContract]
    public class Data<T>
    {
        [DataMember]
        public T Value { get; set; }
    }
```
I found already some places that seem to allow to inject other serializers for certain types. Are there some good  examples, how to setup something like that? I would be fine to use e.g. a json serializer instead.

**Comment by TFTomSun** [comment]
btw. I am also interested in the complicated way :) as long as i can extract the complex part into a separate library and I am able to reuse it, I am fine with it.

**Comment by mgravell** [comment]
the library is fine with you using other serializers, although note that both ends must agree on the setup, as nothing extra is transmitted to say what is being sent. There are two ways of doing this:

1. use `BinderConfiguration.Default.SetMarshaller` to set the marshaller for a *specific* type against the default config (`Marshaller<T>` is the underlying gRPC API here)
2. implement a `MarshallerFactory` that can vote "yes, I can serialize that" against inbound types, create a `BinderConfiguration` that knows about your `MarshallerFactory` (with or without the default protobuf one), and use that `BinderConfiguration` when configuring the server or creating client proxies

An example of creating a `MarshallerFactory` is [here](https://github.com/protobuf-net/protobuf-net.Grpc/blob/main/tests/protobuf-net.Grpc.Test.Integration/CustomMarshaller.cs) - most of the text here is just me giving `BinaryFormatter` a hard time - the only interesting lines are the ones at the bottom: `Serialize<T>` and `Deserialize<T>`

I'm also open to other ways of making this work.

**Comment by mgravell** [comment]
As for the "other way": you need to know the numbers you're going to use somewhere that is reliable and repeatable (even if people add/remove/rename types, etc), but:

``` c#
RuntimeTypeModel.Default[typeof(Base)].AddSubType(10, typeof(StringData));
```

**Comment by TFTomSun** [comment]
Thanks for the information. Does the RuntimeTypeModel support open generics, like:

```
RuntimeTypeModel.Default[typeof(Base<>)].AddSubType(10, typeof(StringData<>));
```

**Comment by TFTomSun** [comment]
hmm... I try to get the following test to run:

```csharp
 [Test]
        public async Task GenericsTest()
        {
            var host = "localhost";
            var grpc = new GrpcManager();

            RuntimeTypeModel.Default[typeof(Base<string>)].AddSubType(int.MaxValue, typeof(Derived<string>));

            await using (await grpc.RunServerAsync(x => x.AddCodeFirst(new CalculatorService<Derived<string>>()), host, out var port))
            await using (var service = grpc.CreateClient<ICalculatorService<Derived<string>>>(host, port))
            {
                var calculator = service.Value;

                var input = new[] { "1", "2" };
                var stream = calculator.Duplex(input.Select(x => new Derived<string> { Value = x }).ToAsyncEnumerable());

                var items = await stream.ToArrayAsync();
                CollectionAssert.AreEqual(input, items.Select(x => x.Value).ToArray());
            }
        }
```

but I get the following error message:
```
InvalidCastException: Das Objekt des Typs "AppGates.Net.ScreenDesigner.Model.Base`1[System.String]" kann nicht in Typ "AppGates.Net.ScreenDesigner.Model.Derived`1[System.String]" umgewandelt werden.

```
I don't understand why it tries to convert Base<string> to Derived <string> .. my model and service contract looks like that:

```csharp
 [DataContract]
    public class Derived<T> :Base<T>
    {
    }

    [DataContract]
    public class Base<T>
    {
        [DataMember(Order =1)]
        public T Value { get; set; }
    }
    public class CalculatorService<T>: ICalculatorService<T>
    {
        async IAsyncEnumerable<T> ICalculatorService<T>.Duplex(IAsyncEnumerable<T> input)
        {
            await foreach (var value in input)
            {
                yield return value;
            }
        }
}
```

**Comment by mgravell** [comment]
Re open generics: the short version would be "no"; the longer version would be that this might be a suitable scenario for hooking the `RuntimeTypeModel.Default.AfterApplyDefaultBehaviour` event, so that you can check the incoming type and configure any additional inheritance rules while it is still in "discovery".

**Comment by mgravell** [comment]
> InvalidCastException: Das Objekt des Typs "AppGates.Net.ScreenDesigner.Model.Base`1[System.String]" kann nicht in Typ "AppGates.Net.ScreenDesigner.Model.Derived`1[System.String]" umgewandelt werden.

I added some integration tests based on this code, using netcoreapp3.1, netcoreapp3.0 and net472 - and both protobuf-net 2.4.6 and 3.0.27, and: no repro.

https://github.com/protobuf-net/protobuf-net.Grpc/blob/main/tests/protobuf-net.Grpc.Test.Integration/Issues/Issue107.cs

**Comment by TFTomSun** [comment]
Ah :) I found the difference. I used int.MaxValue for the subtype definition. If I use 42 like you do in your test, my test runs green, too.

**Comment by mgravell** [comment]
hmmm; I'll have to take a look at that! although: `int.MaxValue` isn't a great choice, to be honest (due to varint encoding)

**Comment by TFTomSun** [comment]
ok, then maybe switching the parameter to ushort might be helpful?

**Comment by mgravell** [comment]
The range is 1-((2^29)-1)
