### ISSUE TITLE
Ports seem not to be released even after awaiting the KillAsync()

### ISSUE THREAD

**Issue by TFTomSun** [protobuf-net/protobuf-net.Grpc#109]
I have a couple of tests - I run them all for .net48 and .netcoreapp3.1 sequentially.  I'm pretty sure that my disposal is clean, but for some tests I get binding exceptions

```
 System.IO.IOException : Failed to bind port "localhost:10042"
  Stack Trace: 
    Server.CheckPortsBoundSuccessfully()
    Server.Start()
```

I think that there's somewhere a leak, that keeps the port open, or that something is not completely awaited. Did somebody else see that issue already?

**Comment by TFTomSun** [comment]
I was able to narrow down the problem. The socket is already used, before the server is even started. Killing the not started server doesn't release the port, too. Here's a test to reproduce the issue:

```csharp
  [Test]
        public async Task Issue_109()
        {
            var port = 10042;

            var server = new Server()
            {
                Ports = { new ServerPort("localhost", port, ServerCredentials.Insecure) }
            };

            await server.KillAsync();

            var server2 = new Server()
            {
                Ports = { new ServerPort("localhost", port, ServerCredentials.Insecure) }
            };

            server2.Services.AddCodeFirst(new CalculatorService<int>());
            server2.Start(); // <--- crash, socket is still in use.
        }
```

**Comment by mgravell** [comment]
I'll.take a look mostly out of curiosity and because I've been fighting some unit tests with this symptom, but: the `Server` here is the Google codebase from `Grpc.Core`, which is out of my direct control.

**Comment by TFTomSun** [comment]
:) yes I discovered that, too... after posting. If you can reproduce it, I can post the issue on their repository again and link it to this one.

**Comment by mgravell** [comment]
Definite repro here; I'm going to go ahead and log it over on `Grpc.Core`

**Comment by TFTomSun** [comment]
thanks for posting it there

**Comment by mgravell** [comment]
Since this repros without a single line from protobuf-net.Grpc, I'm going to close this here, but: I'm very interested in the issue. I might even stick my nose into Grpc.Core again if it doesn't get a response anytime soon.
