### ISSUE TITLE
implicit cast of ClientFactory to BinderConfiguration can lead to NullReferenceException

### ISSUE THREAD

**Issue by TFTomSun** [protobuf-net/protobuf-net.Grpc#110]
How to reproduce:
Add as service as CodeFirst and pass a ClientFactory as a second parameter (which then automatically gets implicitly cast to BinderConfiguration. The implicit cast is not null aware:

```csharp
        /// <summary>
        /// Get the binder configuration associated with this instance
        /// </summary>
        public static implicit operator BinderConfiguration(ClientFactory value) => value.BinderConfiguration;

```

**Comment by mgravell** [comment]
Thanks, good spot. Will fix first thing tomorrow (unless you want to PR it
while I sleep).
