### ISSUE TITLE
Wrong ServerReflectionInfo when using overriding Name in ServiceContract

### ISSUE THREAD

**Issue by Kurounin** [protobuf-net/protobuf-net.Grpc#118]
When using a `Name` for the `ServiceContract` the generated Metadata is wrong.

Using https://github.com/protobuf-net/protobuf-net.Grpc/tree/main/examples/pb-net-grpc/Server_CS when calling the gRPC endpoint  `/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo`  in https://github.com/protobuf-net/protobuf-net.Grpc/blob/b1a06847080f0fbd9a5ad9e7c4da8e79fdb786f2/src/protobuf-net.Grpc.AspNetCore.Reflection/ReflectionExtensions.cs#L53 the first Endpoint is `{gRPC - /Hyper.Calculator/Multiply}`, but the Metadata for `{Grpc.AspNetCore.Server.GrpcMethodMetadata}` is `{Name = "MyCalculator" FullName = "Server_CS.MyCalculator"}` which is wrong.

I haven't yet parsed the project to figure out where this metadata is set in order to correct it myself.

**Comment by Kurounin** [comment]
Seems there was a local issue. Latest main works correctly.

**Comment by mgravell** [comment]
There was a fix here at some point; maybe you just needed lasest?

**Comment by Kurounin** [comment]
Most likely. With the latest I noticed another small issue regarding namespace handling, which I explained here https://github.com/protobuf-net/protobuf-net.Grpc/issues/5#issuecomment-666212273
