### ISSUE TITLE
`[Authorize]` attribute being ignored when mapping endpoints via reflection.

### ISSUE THREAD

**Issue by Euan-McVie** [protobuf-net/protobuf-net.Grpc#120]
Hi,
I've been unable to get the `[Authorize]` attribute to work on my service. 
I've tracked it and can see it appears to be related to how we are mapping our gRPC endpoints by using reflection. 
The reflection method maps it up and it gets called, but unauthorized clients can still access. Explicitly adding the gRPC endpoints does work.

If you have any guidance on what could be causing the attribute to be ignored that would be helpful.
In the meantime I am going to try to pull down your examples and try to modify to recreate.

Thanks

Startup snippet:
```cs
        public static void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                // Enable WepAPI controllers
                endpoints.MapControllers();

                // Enable gRPC services
                endpoints.MapGrpcServices(); // Works, but ignores Auth
                //endpoints.MapGrpcService<Calculator>(); // Works including Auth
            });
        }
```
```cs
        public static IEndpointRouteBuilder MapGrpcServices(this IEndpointRouteBuilder builder)
        {
            if (builder is null)
                throw new ArgumentNullException(nameof(builder));

            MethodInfo? genericMapGrpcService = typeof(Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions)
                .GetMethod("MapGrpcService", BindingFlags.Public | BindingFlags.Static);

            if (genericMapGrpcService is null)
                throw new InvalidOperationException("Failed to get MapGrpcService<T> extension method from Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions");

            ILogger<IEndpointRouteBuilder> logger = builder.ServiceProvider.GetService<ILogger<IEndpointRouteBuilder>>();

            IEnumerable<(Type, DiscoverableGrpcServiceAttribute)> grpcServices = findGrpcServices();

            logger.LogInformation("Mapping {ServiceCount} gRPC service endpoints.", grpcServices.Count());

            foreach ((Type serviceType, DiscoverableGrpcServiceAttribute serviceAttribute) in grpcServices)
            {
                logger.LogDebug("Mapping endpoint for gRPC service '{ServiceId}'", serviceAttribute.ServiceId);
                MethodInfo mapGrpcService = genericMapGrpcService.MakeGenericMethod(serviceType);
                mapGrpcService.Invoke(null, new object[] { builder });
            }

            return builder;
        }
```

**Comment by mgravell** [comment]
This really needs a runnable repro. I suspect there is some nuance of which method/types get used, but...

Also, I presume that the code-first gRPC bits have been activated too.

**Comment by Euan-McVie** [comment]
Yeah, I'll try and recreate on top of your example app.
Was just in the off chance you knew that it definitely wouldn't work because of X,Y,Z. 
It works (i.e. the call gets through and it calculates, just without needing the client to be authorised, while switching to the explicit `.MapGrpcService<Calculator>` causes the expect unauth exception.

It has `ConfigureServices` with:
```cs
services.AddCodeFirstGrpc();
services.AddScoped<ICalculator, Calculator>();
```

**Comment by mgravell** [comment]
I'm definitely intrigued; calling a generic method via reflection *should* work the same; checking what the actual `serviceType` that get logged are would be worth checking, of course. But... yeah!

**Comment by Euan-McVie** [comment]
I found the issue. Was in my code. 
The reflection uses custom attributes on the interface to find the gRPC services and I was mistakenly returning the interface instead of the concrete class to use in the endpoint mapping.
