### ISSUE TITLE
How to get the current user?

### ISSUE THREAD

**Issue by victoriorinescu** [protobuf-net/protobuf-net.Grpc#122]
from:

https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.1

`
public override Task<BuyTicketsResponse> BuyTickets(
    BuyTicketsRequest request, ServerCallContext context)
{
    var user = context.GetHttpContext().User;

    // ... access data from ClaimsPrincipal ...
}

`

The only problem: ServerCallContext does not have a GetHttpContext() method.

Any idea how to solve this?

**Comment by mgravell** [comment]
You would inject an `IHttpContextAccessor` into your service, basically:

``` c#
public class MyServiceType : IWhateverServices
{
    private readonly IHttpContextAccessor _contextAccessor;
    public MyServiceType (IHttpContextAccessor contextAccessor)
        => _contextAccessor = contextAccessor;
}
```

and now you can use `_contextAccessor.HttpContext` whenever you need.

**Comment by mgravell** [comment]
Note: if the MS samples say that this *should* be available on `ServerCallContext`, then I'll see if we can make it available on `CallContext`. Can you confirm whether you're actually using `CallContext` vs `ServerCallContext` here?

**Comment by mgravell** [comment]
The following should also work:

``` c#
// if "context" is CallContext
context.ServerCallContext.GetHttpContext()

// if "context" is ServerCallContext
context.GetHttpContext()
```

but in both cases you need the `using Grpc.Core;` using directive to bring the extension method into scope.

**Comment by victoriorinescu** [comment]
I am using CallContext which has a ServerCallContext property exactly as you said; unfortunately context.ServerCallContext.GetHttpContext() does not exist...

Hmm... maybe it is another CallContext...
Mine seems to be ProtoBuf.Grpc.CallContext.

**Comment by victoriorinescu** [comment]
I use
`endpoints.MapGrpcService<MyGrpcService>();`

I don't know how to inject IHttpContextAccessor; I don't create the object :(

**Comment by mgravell** [comment]
if it is `CallContext`, then you *should* just need

``` c#
using Grpc.Core;`
```

at the top of the file, and `context.ServerCallContext.GetHttpContext()`

**Comment by victoriorinescu** [comment]
offf, it was an extension method!!!

Thank You!

**Comment by mgravell** [comment]
K, I'm assuming this is closed
