### ISSUE TITLE
Can't test my service with BloomRPC

### ISSUE THREAD

**Issue by gb1337** [protobuf-net/protobuf-net.Grpc#127]
[BloomRPC](https://github.com/uw-labs/bloomrpc) is a really neat tool to test GRPC services and I've been using it successfully for testing a GRPC-Web project built around the "official" Grpc.AspNetCore & Grpc.AspNetCore.Web packages. I'm using the Web version of GRPC because my client is built in Blazor Webassembly. 

I like the protobuf-net.Grpc code-only approach better and I feel like it integrates better with the .Net world. I got my service working very well with the Blazor client, unfortunately, BloomRPC is unable to connect to it. I have no idea where the problem could be coming from. This is the error I'm getting in the BloomRPC interface when trying a simple unary request:

`"14 UNAVAILABLE: Trying to connect an http1.x server"`

Obviously BloomRPC can connect to a GRPC service through HTTP 1.1 no problem since it did it just fine when using the official Google/MS package. 

So I'm at a loss as to why it's not liking  protobuf-net.Grpc! What is different?

PS: this issue was reported to BloomRPC by someone else a while ago, but crickets...

**Comment by gb1337** [comment]
I found a workaround... Apparently the issue is that if BloomRPC finds that the server supports HTTP 1.1, it's going to default to trying to use that protocol, only to then say HTTP 1.1 is not a supported protocol ("14 UNAVAILABLE: Trying to connect an http1.x server"). You have to instruct Kestrel to open a separate port that runs HTTP 2.0, and connect BloomRPC to that port. You can't be a smartass and use Kestrel's ability to run HTTP 1/2 on the same port, because then BloomRPC is going to default to HTTP 1.1 anyway and fail.

The only thing I don't get is how is the world was it working before with the official GRPC client.

`public static IWebHostBuilder CreateHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureKestrel(options =>
                {
                    options.ListenLocalhost(10041, listenOptions =>
                    {
                        listenOptions.Protocols = HttpProtocols.Http1;
                    });

                    options.ListenLocalhost(10042, listenOptions =>
                    {
                        listenOptions.Protocols = HttpProtocols.Http2;
                    });
                })
                .UseStartup<Startup>();`

**Comment by gb1337** [comment]
I'm closing this and hopefully this will help somebody one day.

**Comment by mgravell** [comment]
I've appreciated the journey here, thanks.
