### ISSUE TITLE
How to solve ProtoBuf.ProtoException: Possible recursion detected

### ISSUE THREAD

**Issue by lengyjc** [protobuf-net/protobuf-net.Grpc#131]
Here is my simplified model,

``` c#
[DataContract]
    public class AllObj
    {
        [DataMember(Order = 1)]
        public bool IsOk { get; set; }
        [DataMember(Order = 5)]
        public List<UserModel> Users { get; set; }
        [DataContract]
        public class UserModel
        {
            [DataMember(Order = 1)]
            public List<WorkModel> Models { get; set; }
            [DataContract]
            public class WorkModel
            {
                [DataMember(Order = 1)]
                public UserModel tUser {get;set;}
                [DataMember(Order = 2)]
                public List<TestModel> Groups { get; set; }
                [DataContract]
                public class TestModel
                {
                    [DataMember(Order = 2)]
                    public WorkModel workStation { get; set; }
                }
            }            
        }        
    }
```

It constructed by the rule that every level layers contain the pre layers ‘ quote.
There is the exception message 
Grpc.AspNetCore.Server.ServerCallHandler|Error when executing service method 'XXX'. ProtoBuf.ProtoException: Possible recursion detected (offset: 2 level(s))
Is there any setting to solve this problem?

**Comment by mgravell** [comment]
Well: is the model recursive? Is there an example data setup that throws this exception? protobuf is intended as a tree format, and as such: it doesn't love recursion at all. Now, you can often get *around* that with careful choice of what members are serialized, or "conditional serialization", but without context it is hard to advise

For example; if a user contains a model and the model always links back to that same user, it could be that not serializing `WorkModel.tUser` is a pragmatic fix - and instead, use a post-serialization callback on `UserModel`, something like (in `UserModel`):

``` c#
[ProtoAfterDeserialization]
private void OnAfterDeserialize()
{
    var models = Models;
    if (models is object)
    {
        foreach (var model in models)
            model.tUser = this;
    }
}
```

**Comment by lengyjc** [comment]
> Well: is the model recursive? Is there an example data setup that throws this exception? protobuf is intended as a tree format, and as such: it doesn't love recursion at all. Now, you can often get _around_ that with careful choice of what members are serialized, or "conditional serialization", but without context it is hard to advise
> 
> For example; if a user contains a model and the model always links back to that same user, it could be that not serializing `WorkModel.tUser` is a pragmatic fix - and instead, use a post-serialization callback on `UserModel`, something like (in `UserModel`):
> 
> ```cs
> [ProtoAfterDeserialization]
> private void OnAfterDeserialize()
> {
>     var models = Models;
>     if (models is object)
>     {
>         foreach (var model in models)
>             model.tUser = this;
>     }
> }
> ```

This model is an example model . You will get the same problem when you set the value of 'Users'.
I expect that i can set some option in AddCodeFirstGrpc or GrpcServiceOptions to give the ability that model can be deserialized
when i use CreateGrpcService method

**Comment by mgravell** [comment]
And indeed we can, but *by default*, protobuf-net.Grpc uses protobuf-net (note: it is possible to use other serializers), and protobuf-net is a protobuf serializer, and the protobuf format is a tree, not a graph. You would presumably see the same problem for the same reasons if you used `XmlSerializer` or `DataContractSerializer`.

There are lots of ways of representing data, and the trick is often: choosing an appropriate model for the circumstance, and *in this circumstance*: having a recursive model is not a good idea.

**Comment by lengyjc** [comment]
All right .  I will try to find the other way. thanks .
