### ISSUE TITLE
Maturity and needed assembly

### ISSUE THREAD

**Issue by tomas-pajer** [protobuf-net/protobuf-net.Grpc#133]
Hello Marc, 
I would like to know, if the project is mature enough for a production. I have to transform relatively big project: server = asp.net wcf and client = Silverlight using wpf and asp.net core. I have downloaded examples folder from your solution but nothing is working. :-) I am not sure which your assemblies should be used on the client and which original MS grpc assemblies should be used. In old project I have shared class definitions between server and client and I would like to use this approach again. Is it possible? Thank you very much. 
Tom

**Comment by mgravell** [comment]
If you're trying to use it from Silverlight, I can pretty much guarantee
that this is a lost cause. There are two client transports available :

1. Managed via httpclient .NET Core 3.1 or above
2. Unmanaged via Grpc.Core and p/invoke

Neither of these is *ever* going to work on Silverlight. Is that your setup?

**Comment by tomas-pajer** [comment]
You are really quick. I will migrate to client = .net core 3.1 and WPF, server = .asp core.

**Comment by tomas-pajer** [comment]
And one important fact. I am using ExpandoObject very frequently. My "classes" and all UI - all defined by users on the fly. So what about serialization of classes derived from ExpandoObject containing deep hierarchies of another ExpandoObjects? :-) Will it work? Thank you very much. Tom

**Comment by mgravell** [comment]
The serializer is swappable. By default it uses protobuf-net, which *does
not* support expando object. However, if you have a serializer in mind that
works with that type, I can provide examples of swapping the serializer.

**Comment by mgravell** [comment]
Alternatively, some kind of dictionary-string-(discriminated union) could
be doable inside protobuf-net
