### ISSUE TITLE
Support for Blazor WASM in .NET 5.0

### ISSUE THREAD

**Issue by jreid-rts** [protobuf-net/protobuf-net.Grpc#146]
Looks like this has been upgraded to support .NET 5.0 from a regular client, but I can't get it to work in a Blazor WASM project. You can test by taking the project here: "https://github.com/hakenr/BlazorGrpcWebCodeFirst" and upgrading it to net5.0 using the MS instructions here: "https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-blazor-webassembly-projects".

Alternately you can create a new Blazor core-hosted WASM solution with Visual Studio and add the necessary packages.

The error seems to be coming from Protobuf.Grpc.Internal.Reshape.  The exception I get on the client when trying to pull down a simple object via gRpc is:

'Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: TypeError: Failed to fetch", DebugException="System.Net.Http.HttpRequestException: TypeError: Failed to fetch\n   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.SendAsyncC… ProtoBuf.Grpc.Internal.Reshape.<UnaryTaskAsyncImpl>d__12`2[[ProtoBuf.Grpc.Internal.Empty, protobuf-net.Grpc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67],[RTS.Objects.Company, RTS.Objects, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in D:\\Projects\\protobuf-net.Grpc-main\\src\\protobuf-net.Grpc\\Internal\\Reshape.cs:line 294\n   at RTS.Web.Client.Pages.Counter.TestGrpc() in D:\\Projects\\RTS\\RTS.Web\\Client\\Pages\\Counter.razor:line 52'

Love how the project works in netcoreapp3.1/netstandard2.1 and would love to use it in net5.0.  Thanks.

**Comment by mgravell** [comment]
OK, that's actually really helpful; I pulled down the @hakenr code, but I'm having difficulty getting it to play "out of the box" - I'm getting the server running on :5000 and :5001, but the client keeps trying to send messages to :44383 (etc) - am I missing something in getting that example working "as is" first? once I have that, I can try upgrading everything to .NET 5

**Comment by hakenr** [comment]
Hi, I will try to upgrade the project to NET5 (I have already upgraded some other which is based on the same stack). Ho will get to that today.
In the meantime you can try to change the ports for testing: https://github.com/hakenr/BlazorGrpcWebCodeFirst/search?q=44383

**Comment by hakenr** [comment]
...just pushed a very basic upgrade to NET5 (https://github.com/hakenr/BlazorGrpcWebCodeFirst/commit/cfeafdf355c538daf0813edccc8e81c08d0890d7) and it "just works".

(BTW: I've got a version which includes authentication & authorization, just forgot to to publish it.)

**Comment by jreid-rts** [comment]
@mgravell Interesting. The @hakenr code worked for me out of the box. In the server launchSettings.json under the iisSettings it sets the sslPort to 44383 which seems to be the root of that.  The client has this hard-coded in the Index.razor.  Going to pull down Robert's net5.0 code and try that now, which would indicate the issue is not with protobuf-net.Grpc at all but is a configuration issue.  Will respond again when I can - Happy Thanksgiving to those that celebrate.

**Comment by mgravell** [comment]
You're a star, thanks @hakenr. In all seriousness, I wasn't trying to nerd-snipe you - I was happy to take a stab at it, bit I had some config issues locally. But hearing that it "just works" is awesome! Thanks.

**Comment by jreid-rts** [comment]
I just got it all working also. Needed to match the ssl port in appSettings.json on both client and server in addition to the url on the client page (making sure to use https also).  It does just work and you guys are the best. Thanks.
