### ISSUE TITLE
Unresolved Symbols running Samples

### ISSUE THREAD

**Issue by Michael-Kempe** [protobuf-net/protobuf-net.Grpc#150]
Trying to build samples (https://github.com/protobuf-net/protobuf-net.Grpc/tree/main/examples/pb-net-grpc) gives me in Server_CS -> Startup.cs -> ConfigureServices (...) -> services.AddCodeFirstGrpcReflection(); the following error:
Cannot resolve symbol 'AddCodeFirstGrpcReflection'. Perhaps I'm missing a reference? I don't know which one.
I had to manually add the protobuf-net.* Packages. 

Can anyone give me a hint?
Thanks in advance. Kind regards.

![image](https://user-images.githubusercontent.com/46563088/103649053-1c955180-4f5e-11eb-8d2f-75f0e6b2ae55.png)

**Comment by mgravell** [comment]
Has dotnet restore executed? Also, what happens if you use "dotnet build"
at the command line? My suspicion is maybe you're missing the SDK version
and everything is failing, starting with "dotnet restore".

**Comment by Michael-Kempe** [comment]
I've found the problem. I've copied the protobuf-net.Grpc\Examples\pb-net-grpc to a **different place** on my drive and tried to build it without luck. 
But when I build the example from inside protobuf-net.Grpc, everything works perfect.
Maybe the reason is because of some settings in the project files?
    
    _<ProjectReference Condition="'$(ExampleRefs)'=='local'" Include="..\..\..\src\protobuf-net.Grpc\protobuf-net.Grpc.csproj" />
    <PackageReference Condition="'$(ExampleRefs)'=='nuget'" Include="protobuf-net.Grpc" Version="$(PBGRPCLibVersion)" />_

Many thanks for the help!
