### ISSUE TITLE
Observe closed connection on client side in full duplex 

### ISSUE THREAD

**Issue by i3arnon** [protobuf-net/protobuf-net.Grpc#155]
In a full duplex scenario the server can observe the connection being closed by using the `CallContext`'s `CancellationToken`.
Is there a way to achieve the same on the client side?

For example if I have a duplex API where the requests come from the server:

```
IAsyncEnumerable<Request> FooAsync(IAsyncEnumerable<Response> responses, CallContext callContext);
```

Is there a way to know the server went down if I'm between long running requests?

```
await foreach (var request in _server.FooAsync(responses, callContext))
{
    await Task.Delay(1.Hours()); // Can this be cancelled? callContext.CancellationToken isn't cancelled.
}

```

**Comment by i3arnon** [comment]
Somewhat related: Isn't `allDone` prematurely cancelled in the last 2 `FullDuplexAsync` overloads:

https://github.com/protobuf-net/protobuf-net.Grpc/blob/cf82724b544e73dee4aba7c4453398361319292a/src/protobuf-net.Grpc/CallContext.Streaming.cs#L117-L123

The `ValueTask`s aren't awaited and `allDone` is cancelled right away

**Comment by mgravell** [comment]
Second: huh, yes that's definitely a bug. I think we fixed one similar -
kiss have missed that one. Will fix, thanks.

Thinking on the first question.

**Comment by mgravell** [comment]
The tricky thing here is: how to expose such cancellation. Ultimately, the call-options/context cancellation token is an *input* token. We can't cancel that. And even if we did, what we actually need to report is something more complex. I wonder if a helper something like:

``` c#
public static IAsyncEnumerable<T> ObserveCompletion<T>(
    this IAsyncEnumerable<T> source,
    out CancellationToken completion);
```

(I have ideas on the impl, but I'm not at a PC to write it just now)

Then:

```
await foreach (var request in _server.FooAsync(responses, callContext).ObserveCompletion(out var done))
{
    await Task.Delay(1.Hours(), done);
}
```

Not really anything gRPC related, but happy to add as a utility API if it helps?

**Comment by i3arnon** [comment]
What I'm trying to achieve is streaming request-response where the server initiates the requests (basically pull based orchestration).
I realized that I need to always be "in contact" with the stream in order to observe any connection issues through the pipe so I made it work by quickly offloading the single request into a channel and fired up a background task to actually handle the requests:

```csharp
using var cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(CancellationToken);

var requestChannel = Channel.CreateUnbounded<Request>();
var responseChannel = Channel.CreateUnbounded<Response>();

var task =
    Task.Run(
        async () =>
        {
            await foreach (var request in requestChannel.Reader.ReadAllAsync())
            {
                await HandleRequestAsync(request);
            }
        },
        cancellationTokenSource.Token);

try
{
    var responses = responseChannel.Reader.ReadAllAsync();
    await foreach (var request in _server.FooAsync(responses, cancellationTokenSource.Token))
    {
        await requestChannel.Writer.WriteAsync(request);
    }
}
catch (Exception exception)
{
    cancellationTokenSource.Cancel();
    // Log..
}

await task.SwallowCancellation();
```

I'm not sure this scenario is common enough to warrant any changes.
