### ISSUE TITLE
A non-collectible assembly may not reference a collectible assembly

### ISSUE THREAD

**Issue by FireSon** [protobuf-net/protobuf-net.Grpc#159]
Hi Mark,

I am trying to use protobuf-net.Grpc in .Net 5.0 with an assembly which is loaded with an AssemblyLoadContext. This gives the exception: "A non-collectible assembly may not reference a collectible assembly". The exception is raised in the class ProxyEmmitter at line 192: type.AddInterfaceImplementation(iType); 

Is this similar to the _**protobuf-net.Grpc Emit support xamarin error #65**_ issue? or is there some other work around?

Thanks!

**Comment by mgravell** [comment]
Honestly: no clue.

Do you have code that shows how I can repro this?

Note: the *aim* is to finish off the "generators" proxy layer so nothing
needs to happen at runtime except lookup.

**Comment by FireSon** [comment]
Thanks for the quick reply!!
In the attached zip file there are 3 projects. 
- The Its-Hub is the main project and uses the other two. 
- The Its-Server is a Grpc server which is basically a copy of your pb-grpc example. 
- The Its-Consumer is the client, 

When you run the Its-Hub the other projects are dynamically load using an AssemblyLoadContext. Once started the Its-Consumer tries to connect to the server and the described exception occurs...

Hopefully
[Its.Hub.zip](https://github.com/protobuf-net/protobuf-net.Grpc/files/5997048/Its.Hub.zip)
 this helps...

**Comment by mgravell** [comment]
Very interesting. I'll see if we can convince it to play nicely, but this might be a scenario where the real fix is: the build-time (generators) support, which completely removes ref-emit from the equation.

**Comment by FireSon** [comment]
I did some more testing and when I modified the ProxyEmmitter.cs on line 18 with the following code

        private static readonly ModuleBuilder s_module = AssemblyBuilder.DefineDynamicAssembly(
                new AssemblyName(ProxyIdentity), AssemblyBuilderAccess.RunAndCollect).DefineDynamicModule(ProxyIdentity);

I changed AssemblyBuilderAccess.Run into AssemblyBuilderAccess.RunAndCollect

And then it worked :-)

**Comment by mgravell** [comment]
Fair enough. That was on my list of things to try - haven't looked yet (see
twitter). If you want to do a PR, I'll merge it :)

**Comment by FireSon** [comment]
Hi Mark,
Would i be possible to update the NuGet package? Would help me a lot :-)
Thanks!

**Comment by mgravell** [comment]
In theory: yes. In practice: I'm mostly horizontal with covid right now. I
can give you the MyGet feed: enough?
https://www.myget.org/F/protobuf-net/api/v3/index.json

**Comment by FireSon** [comment]
O wauw that doesn't sound good! Get well soon and thanks very much for the quick reply despite covid!!
I'll used the feed :-)
