### ISSUE TITLE
Bad gRPC response. Response did not have a content-type header

### ISSUE THREAD

**Issue by GoNextGroup** [protobuf-net/protobuf-net.Grpc#16]
I use this library in my project. Earlier, I realized gRPC bridge for my microservices and everything worked fine. But after project was updated, each time I tried to use bridge, I got an error which is described in the question's header.

So, I changed code as you described in the new example - no affects.
I thought, that I had my hands curved and downloaded new code example from github and ran it (compiled Server, Client, and Shared independently by adding links they needed from nuget) - the same error was caught.

Could you check the reason of this error? ((( 
During the project example test (pb-net-grpc), I installed all last libraries which were needed for compilation and execution).

See the Stack Trace:

System.InvalidOperationException
  HResult=0x80131509
  Message = Bad gRPC response. Response did not have a content-type header.
  Источник = Grpc.Net.Client
  Stack trace:
   at Grpc.Net.Client.Internal.GrpcCall`2.ValidateHeaders()
   at Grpc.Net.Client.Internal.GrpcCall`2.<SendAsync>d__76.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<GetResponseHeadersAsync>d__67.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProtoBuf.Grpc.Internal.Reshape.<UnaryTaskAsyncImpl>d__10`2.MoveNext() in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Internal\Reshape.cs:line 222
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Client_CS.Program.<Main>d__0.MoveNext() in C:\Users\Rebelion\Downloads\protobuf-net.Grpc-master\protobuf-net.Grpc-master\examples\pb-net-grpc\Client_CS\Program.cs:line 20

Thank you.

**Comment by mgravell** [comment]
Hi; what can I do to reproduce this error? The stacktrace you've shown is from a client, so: what is the server? I've checked using the current "master" using Server_CS and Client_CS on preview9, and they are working fine locally. So: what can I do to repro what you have here?

**Comment by GoNextGroup** [comment]
It's a Client_CS stack trace: "d__0.MoveNext() in C:\Users\Rebelion\Downloads\protobuf-net.Grpc-master\protobuf-net.Grpc-master\examples\pb-net-grpc\Client_CS\Program.cs:line 20"

You could take your code example, open Server_CS, Client_CS, Share_CS independently, change links in csproj, add libraries directly and try to run.

**Comment by GoNextGroup** [comment]
https://drive.google.com/drive/folders/1bNVwvRVs5kQpDyG-Huw7GdpofuRQ6sNX?usp=sharing  Here the cutted version of an pd-net-grpc example

**Comment by mgravell** [comment]
downloaded; working fine here; what SDK are you using? in particular, if you use "dotnet --info", what does it say **at the top**? here's mine:

``` txt
C:\Code\issue16\pb-net-grpc\pb-net-grpc\Client_CS>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a
```

which tells me that I have preview9 installed

**Comment by mgravell** [comment]
also: what OS/etc are you using?

**Comment by mgravell** [comment]
minor note: I had to change the client csproj to explicitly tell it the version of Grpc.Net.Client because the token wasn't defined; you may wish to check that in your own csproj, but I *suspect* you have a copy of the directory build props file.

**Comment by GoNextGroup** [comment]
Now I've made 2 copies of project without any changing (just copy an original link and clone).  I've run copies independently (examples from pd-net-grpc) - Server and Client. The same mistake on the Client side without any reaction of Server side.

My .NET

C:\Windows\system32>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.400 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

My OS - Windows Server 2012 R2

**Comment by GoNextGroup** [comment]
> minor note: I had to change the client csproj to explicitly tell it the version of Grpc.Net.Client because the token wasn't defined; you may wish to check that in your own csproj, but I _suspect_ you have a copy of the directory build props file.

I see 0.2.23-pre1 version for Grpc.Client.Net in Client_CS references.

**Comment by mgravell** [comment]
Ok. Can you please try the dotnet-grpc / grpc-dotnet sample of the same (client and server)? I wonder if this is nothing to do with protobuf-net, but is a bug in an OS version of the core, in which case I need to let James know ASAP.

**Comment by GoNextGroup** [comment]
> Ok. Can you please try the dotnet-grpc / grpc-dotnet sample of the same (client and server)? I wonder if this is nothing to do with protobuf-net, but is a bug in an OS version of the core, in which case I need to let James know ASAP.

I will, but I need a time (little) to migrate (Is Windows 10 1903 build enough?)

**Comment by mgravell** [comment]
I was hoping you could try them on your current OS to see if it behaves the same without protobuf-net even taking part

**Comment by GoNextGroup** [comment]
Ah, I misunderstood you. Of course, I'll try now.

**Comment by GoNextGroup** [comment]
So, **dotnet-grpc** has the same error. 
**grpc** works fine
**perf** has the same error.

**Comment by GoNextGroup** [comment]
**dotnet-grpc** works on Windows 10 1903 build
**pb-net-grpc** works  on Windows 10 1903 build

**Comment by GoNextGroup** [comment]
Damn, It's really damn... I'd spent 1.5 days tried to understand the problem of my code before I wrote you about this situation...

**Comment by GoNextGroup** [comment]
After .NET and Windows were updated, the problem solved. Thank you, It's really a OS problem...

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/issues/492

At the very least the OS requirement should be documented.

**Comment by GoNextGroup** [comment]
The problem was solved by installing KB4486105, KB4507422, KB4512195, KB4512488, KB4512478, KB3162835, KB3118401 patches.

**Comment by GoNextGroup** [comment]
I was too fast. Unfortunatelly, It's not a solution.
It's a really strange behavior of the library. Let's see why.
I patched OS, after that test examples started to work properly without any errors. Also, my own code which is run by the timer also worked fine.
But! 
I have 2 project, one of which is a http storefront (WebAPI) and uses grpc for communication with database service. So, this storefront uses http1.1 for Controllers and http2 for grpc.
I tried to run this project and got the header error. But it's not the most funnies and strange moment in this story! Also all working well code I'd run earlier stopped working with the same error! pb-net-grpc and others!
Why? I really confused...

**Comment by mgravell** [comment]
K; if it fails in the same way for the dotnet-grpc tests, then this is a problem that should be reported to @JamesNK via https://github.com/grpc/grpc-dotnet/

This library simply *plugs into* grpc-dotnet etc; it doesn't do any transport itself, so if the transport is broken: there is literally nothing that protobuf-net.Grpc can do to fix that.

**Comment by GoNextGroup** [comment]
Ah, kk,, Yes, dotnet-grpc test also fails after that. I'll try to write a report to the @JamesNK, but I need a time for this to implement simple reproduciable exam (I cannot cut parts from my projects fast, unfortunatelly). If you have connection with him and grpc-dotnet development team, it would be great if you will bell him/them to focus on this situation (maybe they could reproduce this problem in a simple code example faster than me).
By the way, thank you for your help and sorry for my bad English.

**Comment by mgravell** [comment]
I've already pinged him both here and offline (you can see he commented a few above). I can't speak to the priorities of another team, of course - but: I've made them aware.

I'm going to close this one down, as I don't think there's anything extra I can add. If I've missed something and there *is* something more I can do, just ping me.

**Comment by GoNextGroup** [comment]
Yes, sure, thank you!

**Comment by mgravell** [comment]
One thing I should emphasize: protobuf-net.Grpc works with both the
newer/managed Microsoft transport layer, and the older/unmanaged Google
transport layer.

If you just want to have it *work*, you could try using Google.Core instead
of the Microsoft bits. From protobuf-net.Grpc, client-side code is
virtually identical. The server is a bigger delta, since you won't be using
Kestrel in that case.

**Comment by GoNextGroup** [comment]
I've found the source of the problem. It was the Fiddler and proxy changing...

**Comment by mgravell** [comment]
Lol! Yeah, don't do that
