### ISSUE TITLE
CallContext.Equals and GetHashCode are implemented to throw NotSupportedExceptions

### ISSUE THREAD

**Issue by dgschrei** [protobuf-net/protobuf-net.Grpc#160]
As the title says, calling these two methods on CallContext will throw NotSupportedExceptions. 

While I do get that testing for equality on two CallContext objects as part of one's own business logic, is probably not something  one should ever do, users don't always get a say in the matter.

My concrete problem right now is that I am trying to write a unit test with NSubstitute, to check whether my client correctly calls the server. 

However I can not verify the calls on the mocked server, because NSubstitute will call Equals on provided parameters internally, which then leads to an exception and a failed test.

`mockedService.Received(1).Subscribe(Arg.Any<CallContext>());`

This will fail because NSubstitute's Arg.Any leads to Equals being called somewhere in the Mocking Framework.

Since a lot of libraries make heavy use of Equals and GetHashcode this is less than ideal. 

Or to quote MS's own guidelines:

[https://docs.microsoft.com/en-us/dotnet/api/system.object.equals?view=netframework-4.8](url)

> Implementations of Equals must not throw exceptions; they should always return a value. For example, if obj is null, the Equals method should return false instead of throwing an ArgumentNullException.

[https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netframework-4.8](url)

> The GetHashCode() method should not throw exceptions.

**Comment by mgravell** [comment]
Noted. We'll have to see if we can figure out a sensible way of
implementing this - it isn't entirely trivial in this case.
