### ISSUE TITLE
Do I need to dispose or close the IService when I finish using it?

### ISSUE THREAD

**Issue by Molinware** [protobuf-net/protobuf-net.Grpc#166]
```C#
IService service = MyGrpcChannel.CreateGrpcService<IService>();
long[] ids = service.GetIds();
```

Do I need to do something to close/destroy the IService when I finish to use it?

**Comment by mgravell** [comment]
No; the service is a thin veneer on the channel. It is the channel that
needs cleanup - the "how" may be specific to whether you're using the
Google vs Microsoft transport layer.

**Comment by Molinware** [comment]
My channel is a singleton in the application. Do I still need to clean the services that I created backed by it?

**Comment by mgravell** [comment]
No, fundamentally.

**Comment by Molinware** [comment]
Thanks Marc!
