### ISSUE TITLE
Include original exception as InnerException

### ISSUE THREAD

**Issue by fbridger** [protobuf-net/protobuf-net.Grpc#167]
Original exception should be included as InnerException

https://github.com/protobuf-net/protobuf-net.Grpc/blob/167f6faa22353c9df7fc03b471320afbe5103bec/src/protobuf-net.Grpc/Internal/Reshape.cs#L157

**Comment by fbridger** [comment]
We are trying to detect if the call to gRPC failed due to a Network problem (HttpRequestException or SocketException)

**Comment by mgravell** [comment]
I think I see a way to expose this, however it would be on the the
.Status.DebugException - that do?

(I'm limited by the Google API surface)

**Comment by fbridger** [comment]
That would be great. We just need a way to obtain the original Exception to understand what happened.

**Comment by mgravell** [comment]
In addition to https://github.com/protobuf-net/protobuf-net.Grpc/commit/9c00ecf132df18346f514f87aa1a29f195e4f1cf, I have also opened https://github.com/grpc/grpc/issues/25740 on the grpc/grpc repo.
