### ISSUE TITLE
Generate proto files from code first service contracts during build for distribution

### ISSUE THREAD

**Issue by taralpatel610** [protobuf-net/protobuf-net.Grpc#168]
@mgravell Is it possible to do the above?

Runtime generation of proto files using SchemaGenerator is not working as expected when deployed to production website due to permission issues

**Comment by mgravell** [comment]
It certainly *should* be possible. What permissions problems are you seeing?

**Comment by taralpatel610** [comment]
I am calling following from startup to create all the proto files necessary when the app starts 

```c#
public static void GenerateProtoFiles( this IWebHostEnvironment webHostEnvironment ) {
	var schemaGenerator = new SchemaGenerator();
	var grpcService = typeof( IGrpcService );
	var grpcServiceInterfaces = AppDomain.CurrentDomain.GetAssemblies()
		.SelectMany( assembly => assembly.GetTypes() )
		.Where( type => graphiteGrpcService.IsAssignableFrom( type )
			&& type.IsInterface && !type.Name.Equals( grpcService.Name ) );
	if ( !Directory.Exists( Path.Combine( webHostEnvironment.WebRootPath, "Protos" ) ) ) {
		Directory.CreateDirectory( Path.Combine( webHostEnvironment.WebRootPath, "Protos" ) );
	}

	foreach ( var grpcServiceInterface in grpcServiceInterfaces ) {
		var protoSchema = schemaGenerator.GetSchema( grpcServiceInterface );
		File.WriteAllText( Path.Combine( webHostEnvironment.WebRootPath, "Protos", $"{grpcServiceInterface.Name}.proto" ), protoSchema ); 
	}
}
```

Currently apps are being deployed to IIS from a low code no code platform
As the apps itself do not have permission to write files in IIS (inetpub folder), it fails to start
I can give the permission manually but want to automate the proto generation itself
Besides it is tedious to do for many apps as its is a part of low code no code platform
Also we are planning to deploy apps to azure app services from the platform which also raises an important question about permissions

**Comment by mgravell** [comment]
Ah, I assumed you would be serving them as http responses, not physical
files. Is that not a possibility?

**Comment by taralpatel610** [comment]
Not really as the endpoint at which the proto file is served will be used by other apps to consume.
Similar to wsdl or  a rest endpoint
Basically trying to replace SOAP with grpc in .net core as exposing it is not supported by Microsoft anymore

**Comment by mgravell** [comment]
Well, yes, but it *looks* like you're simply trying to expose these as
/Protos/Whatever.proto - that seems like something that could be served
dynamically rather than from a file. Am I missing something subtle?

**Comment by taralpatel610** [comment]
Dynamic proto file serving would work great if I was consuming and exposing the services myself while developing it. 
It is part of the platform as I mentioned earlier. As a result, I need to automate it.
Serving files provide a strongly defined endpoint where it will be always available.
No other reason.

**Comment by mgravell** [comment]
So it seems to me that the real question here is "can I generate .proto
files in a build step, suitable for simple deployment". I don't have an API
for that right now.

**Comment by taralpatel610** [comment]
I'll try the dynamic way as you mentioned with a controllers, strong routes and see if that works

**Comment by taralpatel610** [comment]
Thank you @mgravell It worked
