### ISSUE TITLE
Use with code-first EF classes

### ISSUE THREAD

**Issue by milkmanmatty** [protobuf-net/protobuf-net.Grpc#178]
I'm looking to use the classes that generate the tables in EF as types defined in gRPC. From what I've seen protobuf-net.Grpc is the only way that this might work. I'm assuming there will be issues with the way repeatable proto fields are not set-able and thus conflict with the EF class fields? possibly other issues as well? Has anyone else done this before or shed any insight on possible problems?

**Comment by mgravell** [comment]
What would really help here is a concrete example of the types that you want to work with. protobuf-net does not have a strong opinion on whether collection properties are settable, unless they are immutable collection types or arrays (and thus *need* to be settable)

**Comment by milkmanmatty** [comment]
Great! I was more asking "is this possible or is there known issues". If protobuf-net does not have a strong opinion on whether collection properties are settable then this seems like the right tool for the problem, thanks!
