### ISSUE TITLE
Adding ProtoBuf.Grpc.Reflection removes System.ServiceModel?

### ISSUE THREAD

**Issue by milkmanmatty** [protobuf-net/protobuf-net.Grpc#179]
Have a server that runs a service successfully. Wanted to generate a proto file of that service for a Node client, installed ProtoBuf.Grpc.Reflection nuget package and everything breaks.

Before adding ProtoBuf.Grpc.Reflection
![before_nuget](https://user-images.githubusercontent.com/9074205/115798685-2a41ea80-a41a-11eb-86be-5f72e7964df5.png)
![before_nuget_added](https://user-images.githubusercontent.com/9074205/115798686-2ada8100-a41a-11eb-88c0-aafde8735e07.png)

After adding ProtoBuf.Grpc.Reflection
![after_nuget](https://user-images.githubusercontent.com/9074205/115798683-29a95400-a41a-11eb-94f8-9f5615900f79.png)
![after_nuget_added](https://user-images.githubusercontent.com/9074205/115798678-28782700-a41a-11eb-8a23-51b0086f7ff7.png)

Suddenly System.ServiceModel becomes unused? also apparently unusable?

I'm hoping I'm just an idiot and am missing something very basic here.

**Comment by mgravell** [comment]
protobuf-net.Grpc only demands protobuf-net V2; however, the *reflection*
tools demand protobuf-net V3. By adding reflection, you're essentially
changing protobuf-net majors, and: protobuf-net V3 doesn't have a
transitive dependency on System.ServiceModel.Primitives

So: add ^^^ as an additional dependency, and you should be set.

**Comment by milkmanmatty** [comment]
Thanks for the help! That fixed it, had to "find and install latest System.ServiceModel.Primitives" and then remove the using statement for that package. Seems counter intuitive but it definitely fixed it. Thanks again for your help I appreciate it!
