### ISSUE TITLE
Add support for an inherited interfaces

### ISSUE THREAD

**Issue by GoNextGroup** [protobuf-net/protobuf-net.Grpc#18]
I tried to realize `IAddUser<T>` interface for variety of methods which are described realization of the same connected classes like `AddLogistian: IAddLogistian,   IAddLogistian : IAddUser<Logistian>` and so on.
For example:

```
public interface IAddUser<T> where T: User
{
    Task<ServiceObject> Add(AddUserRequest addUserRequest);
}

public interface IAddLogistian : IAddUser<Logistian> { }

public class AddLogistian : IAddLogistian
{
      public async Task<ServiceObject> Add(AddUserRequest addUserRequest)
      {
          ...
      }
}
```

But the `ServiceContract` attribute which is used on `IAddLogistian`, gives a execution error: "Specified method is not supported."

StackTrace:
   at ProtoBuf.Grpc.Internal.Proxies.LiteClientBase.IAddLogistian_Proxy_0.IAddUser`1.Add(AddUserRequest )
   at WebFoundationClassesCore.Services.DatabaseServices.AddUserServices.Service.AddLogistian.<Add>d__1.MoveNext() in C:\Users\Rebelion\repos\WebFoundationClassesCore\WebFoundationClassesCore\Services\DatabaseServices\AddUserServices\Service\AddLogistian.cs:line 44

Source: ProtoBuf.Grpc.Internal.Proxies

So, there are 2 questions: 
1) How is it possible realize the described above shema?
2) Is it possible to use `IAddUser<T>`  for  different services without underlying service like `IAddLogistian` (in the future - nowaday the shema with `IAddLogistian : IAddUser<Logistian>` isn't work)?

Thank you.

**Comment by d1820** [comment]
I am having the same issue? Any answer on this. seems like multiple interfaces on a service is not supported?

**Comment by erichiller** [comment]
Same here, I think this is related to #62 as well

**Comment by mgravell** [comment]
The inner (often generic) interface can be marked as `[SubService]`, and this will behave as desired
