### ISSUE TITLE
[Question] Is inheritance supported in the DTO classes?

### ISSUE THREAD

**Issue by SeppPenner** [protobuf-net/protobuf-net.Grpc#180]
I wanted to know if inheritance is supported in the DTO classes used in service methods. I have played around a bit and wasn't able to get it working.

Example:

```csharp
[DataContract]
public class MultiplyRequest : FooClass
{
    [DataMember(Order = 2)]
    public int X { get; set; }

    [DataMember(Order = 3)]
    public int Y { get; set; }
}

[DataContract]
public class FooClass
{
    [DataMember(Order = 1)]
    public int Bar { get; set; }
}
```

As far as I found out, this is not supported by the library, correct?

**Comment by mgravell** [comment]
Protobuf-net can model inheritance, but you'd need to use the protobuf-net
attributes; then you add [ProtoInclude] on the **base** type, referring to
the **derived** type. So:

[ProtoContract]
[ProtoInclude(1, typeof(FooClass)]
public class MultiplyRequest : FooClass
{
    [ProtoMember(2)]
    public int X { get; set; }

    [ProtoMember(3)]
    public int Y { get; set; }
}

[ProtoContract]
public class FooClass
{
    [ProtoMember(1)]
    public int Bar { get; set; }
}

Note that the numbers are isolated between the different types - you don't
need to keep them unique. Note also that protobuf-net.BuildTools will
notify you of problems at compile time.

**Comment by SeppPenner** [comment]
@mgravell Thank you for the quick reply. In the mean time, I found an issue on Stackoverflow describing the same solution: https://stackoverflow.com/questions/6899561/protobuf-inheritance-and-generics.

I will give it a try :)

**Comment by codeputer** [comment]
Interesting what's the one for (likely reason the first property starts with a 2). Is the inheritance tested like a property for serialization?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgravell** [comment]
Yes; not at a PC, but if you are familiar with .proto, protobuf-net mimics inheritance via `oneof` semantics (without actually using the DSL, though), and always starts at the most base-type that it understands, and works inward to more derived types. Each additional subtype is a separate `message` (again, only in the library's imagination - we don't ever define or allocate the `message`), and a type that *has* sub-types essentially has a `oneof` with a possible member for each anticipated sub-type.

Sorry, I think I got the base-type and sub-type conflated in my example above, but it sounds like you figured it out.

**Comment by codeputer** [comment]
Ok and interesting, but I would put the DTO with emphasis on Transfer.  I think we need to really understand that serialization must occur, and binary just isn't going to cut it (sadly).  If this is how it works, I would create a DTO removing the inheritance over the wire...but all this marshalling sucks...DTO, Application model, then data persistence...each with a difference requirements and emphasis.

I like the library, as I can simply stay in C# and my love of interfaces, but it still bleeds doesn't it..

Great work btw...would love to know more and dig into the code.  Coffee on me coming!

Richard

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mgravell** [comment]
Just in case there was any confusion: I'm only describing what happens in a *semantic* sense, i.e. how it **pretends** to behave, if you were looking just at the results; it doesn't *actually* create any additional data models or objects to work with - it works completely with the data you give it, and *pretends* to perform the structural gymnastics that would be required to do that via *regular* protobuf.

**Comment by SeppPenner** [comment]
@mgravell Nice, it works. Just one small thing:

There is a typo in your example `[ProtoInclude(1, typeof(FooClass)]` should be `[ProtoInclude(1, typeof(FooClass))]`. A closing round bracket `)` is missing :)

**Comment by mgravell** [comment]
@SeppPenner  I'd be more worried about the fact that I'd annotated the wrong type :) fixed both, thanks

**Comment by SeppPenner** [comment]
> @SeppPenner I'd be more worried about the fact that I'd annotated the wrong type :) fixed both, thanks

Upps, exactly. I didn't see that as I just copy pasted your solution and added my class names ;)
