### ISSUE TITLE
[Question] Are generics supported in the DTO classes?

### ISSUE THREAD

**Issue by SeppPenner** [protobuf-net/protobuf-net.Grpc#181]
I wanted to know if generics are supported in the DTO classes used in service methods. I have played around a bit and wasn't able to get it working.

Example:

```csharp
[DataContract]
public class MultiplyRequest<T> where T:class
{
    [DataMember(Order = 1)]
    public T X { get; set; }

    [DataMember(Order = 2)]
    public int Y { get; set; }
}
```

Is this supported by the library?

**Comment by mgravell** [comment]
Data types should work fine. However, generic service interfaces or service
methods: are probably going to struggle due to route conflicts. Do you have
a specific example?

**Comment by SeppPenner** [comment]
@mgravell Sorry, my mistake. Generics work for me. I had issues with inheritance only as mentioned under https://github.com/protobuf-net/protobuf-net.Grpc/issues/180.

`protobuf-net.BuildTools` helped me to solve the issues.
