### ISSUE TITLE
Question: is it possible to create gRPC analogue for IHttpContextAccessor?

### ISSUE THREAD

**Issue by ornic** [protobuf-net/protobuf-net.Grpc#185]
I am testing migration of API from REST to gRPC and very glad to work with gRPC via CodeFirst approach, thank you for the opportunity!

Currently I globally manage CancellationToken for all services (instead of adding it as a parameter in every action and pass it down to DB services):
```C#
public ScopedCancellationTokenSourceService(IHostApplicationLifetime appLifetime, IHttpContextAccessor httpContextAccessor)
{
   _cancellationTokenSource = CancellationTokenSource
      .CreateLinkedTokenSource(httpContextAccessor.HttpContext?.RequestAborted ?? default, appLifetime.ApplicationStopped);
}
```

Is it possible to extract Cancellation status from, for example, `HttpContext` passed to `Invoke(Async)` of net.core middleware? Or may be there is some other way?

**Comment by mgravell** [comment]
`IHttpContextAccessor` should already work just fine, and we provide an extension method on `Microsoft.AspNetCore.Http.HttpContextAccessorExtensions`:

``` c#
public static ServerCallContext GetServerCallContext(this IHttpContextAccessor httpContextAccessor)
```

As you can see, this gives you the call context, which includes `.CancellationToken`

That work?

**Comment by mgravell** [comment]
btw; all this *actually* does is effectively: `return httpContext.Features.Get<IServerCallContextFeature>().ServerCallContext;` (but with a bit more clarity re NREs etc)

**Comment by ornic** [comment]
Thank you! :) Yes, that was exactly what I needed.
