### ISSUE TITLE
Please help setup a server streaming call with subscriber patttern

### ISSUE THREAD

**Issue by Dunge** [protobuf-net/protobuf-net.Grpc#187]
So I have a long running service who update stuff, and I want many clients to be able to connect/subscribe to it and all of them to receive callbacks when the service update.

I use protobuf-net.Grpc because I have a huge object model and this lib makes it much easier to keep the service interface and object model up-to-date than having to maintain a .proto file independently, so thanks for this lib it makes the work much easier.

I first started following the Microsoft guide here:
https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-duplex-services

In this guide, Microsoft use an EventHandler to receive calls from the long running service and send them back to the client streams. But it have the `Subscribe()` method on the server and on the client-side with a very different signature. On the server side, it receives an `IAsyncStreamWriter` that he can write to (and pass from one method to another) and return a simple `Task`. On the client side the function takes no special argument and returns an `AsyncDuplexStreamingCall` (or a `AsyncServerStreamingCall`) that he can read from.

With protobuf-net.Grpc, in order to have a common interface, I saw the samples returning an `IAsyncEnumerable` instead, and using `yield` on the server-side to write results. While on the client, you can `async foreach` on the result in a separate dedicated thread to read the results. Honestly, it's MUCH cleaner and easier.

Your sample pretty much look like this (adapted to my code):

        public IAsyncEnumerable<Callback> SubscribeToCallback(CallContext context = default) => SubscribeToCallback(context.CancellationToken, context);

        private async IAsyncEnumerable<Callback> SubscribeToCallback([EnumeratorCancellation] CancellationToken cancel, CallContext context = default)
        {
            while (!cancel.IsCancellationRequested)
            {
                try
                {
                    await Task.Delay(TimeSpan.FromSeconds(10), cancel);
                }
                catch (OperationCanceledException)
                {
                    // Normal, client disconnected
                    yield break;
                }

                yield return new Callback { Name = "Test" };
            }
        }

Now this is fine for having calls all returning new results on a timer independently, my problem comes with the subscription pattern since I want my service to be able to callback to all my subscribed clients. I tried to do a mix of the two solutions, and I can't seems to find a way to mix the `yield` and the EventHandler coming up from my service:

        private async IAsyncEnumerable<Callback> SubscribeToCallback([EnumeratorCancellation] CancellationToken cancel, CallContext context = default)
        {
            EventHandler<string> handler = async (sender, args) => { yield return new Callback { Name = args }; };

            try
            {
                _service.CallbackUpdate += handler;

                var completion = new TaskCompletionSource<object>();
                cancel.Register(() => completion.SetResult(null));
                await completion.Task;

                //yield return new Callback { Name = "Test" };
            }
            finally
            {
                _service.CallbackUpdate -= handler;
            }
        }

Now of course the issue is having the "yield" keyword in the EventHandler function, which is not the method that is returning the `IAsyncEnumerable`...

With the `IAsyncStreamReader` pattern from the Microsoft sample, he could just pass that object the to EventHandler, but in our case I can't do that.

**Comment by mgravell** [comment]
This is interesting. I can think of many ways of doing it, but all rather
manual and awkward. I wonder if we need a better primitive here,
essentially like Channel <T> but for broadcasts. Does that sound like
something that could work?

**Comment by Dunge** [comment]
Yeah well after posting this I stumbled on a StackOverflow post mentioning`System.Threading.Channels` to do that kind of operation too.

 I think I managed to get it working with a different Channel for each subscriber, but I have no idea of the implications of what using this to do the bridge brings in terms of performances, etc.

        private async IAsyncEnumerable<Callback> SubscribeToCallback([EnumeratorCancellation] CancellationToken cancel, CallContext context = default)
        {
            var buffer = Channel.CreateUnbounded<string>();
            EventHandler<string> handler = async (sender, args) => await buffer.Writer.WriteAsync(args);

            try
            {
                _service.CallbackUpdate += handler;

                while (!cancel.IsCancellationRequested)
                {
                    yield return new Callback { Name = await buffer.Reader.ReadAsync() };
                }
            }
            finally
            {
                _service.CallbackUpdate -= handler;
            }
        }

I also always get a "Can't write the message because the request is complete." exception triggering after canceling the token on the client side and the function ends (not during the yield).

Anyway, do you think this is an acceptable solution or am I shooting myself in the foot here trying to work around things with methods that are not standard?
