### ISSUE TITLE
Use reflection instead of [ProtoInclude]

### ISSUE THREAD

**Issue by ornic** [protobuf-net/protobuf-net.Grpc#192]
I'm trying to reduce boilerplate code in my project. Is there a way to teach **protobuf-net.Grpc** about inheritance using reflection instead of `[ProtoInclude]` attributes?

In another project I used **protobuf-net** for storage and populated `ProtoBuf.Meta.RuntimeTypeModel.Default` with some needed information about fields in classes from external libs. And it works great.

Now I am trying to do the same with **protobuf-net.Grpc** but unfortunately setting attribute this way:
```
[DataContract]
[ProtoInclude(1000, typeof(UserSurveyIdsRequestDto))]
public class BaseRequestDto
{
    [DataMember(Order = 1)]
    public string ActionUid { get; set; }

    public BaseRequestDto() { }
}

[DataContract]
public class UserSurveyIdsRequestDto : BaseRequestDto
{
    [DataMember(Order = 2)]
    public string ServerId { get; set; }

    [DataMember(Order = 3)]
    public int UserId { get; set; }

    public UserSurveyIdsRequestDto() { }
}
```

is not the same as using reflection and RuntimeTypeModel:
```
var dataContractMetaType = ProtoBuf.Meta.RuntimeTypeModel.Default.Add(typeof(BaseRequestDto));
dataContractMetaType.AddSubType(1000, typeof(UserSurveyIdsRequestDto))
```

Using `RuntimeTypeModel` way instead of `[ProtoInclude]` (all other attributes are in place) I got this error:
```
{"grpc_message":"Exception was thrown by handler. InvalidCastException: Unable to cast object of type 'BaseRequestDto' to type 'UserSurveyIdsRequestDto'."}
```

Changing DataContract -> ProtoContract had on effect :(

**Comment by mgravell** [comment]
No problem :) I was reading that thinking "huh, that should work", so: I'm
glad it did!
