### ISSUE TITLE
Using observer desing pattern for streaming server side

### ISSUE THREAD

**Issue by behnamshateri** [protobuf-net/protobuf-net.Grpc#193]
I want to use [Observer design pattern](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern) along with server side streaming.
By sending request from user to server to get data, at user subscribe as observer and then when new data from observable is released, we can get data with `OnNext` method of observer in above design pattern, how can I send this data that observer got it as stream data 

Since we must use `yield return` for streaming data, i don't know how to implement this scenario.

**Comment by mgravell** [comment]
There is no requirement to use `yield return`; if you're working from a push model, maybe a `Channel<T>` is what you're looking for? Write to it from the observer code, and simply return the async-enumerable aspect to be streamed over gRPC (there is an `AsAsyncEnumberable()` API, IIRC)

**Comment by behnamshateri** [comment]
Hi  @mgravell,

Thank's for the speedy response and solution. Just let me test it out and seems to be working as described.

Thanks greatly

**Comment by mgravell** [comment]
k; closing this out, but: feel free to ask / reopen if there's more
