### ISSUE TITLE
CreateGrpcService throws FileLoadException

### ISSUE THREAD

**Issue by jamiewinder** [protobuf-net/protobuf-net.Grpc#2]
I get this error when I call the `HttpClient.CreateGrpcService` method:
```
{System.TypeInitializationException: The type initializer for 'DefaultProxyCache`3' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Emit.ILGeneration, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Reflection.Emit.ILGeneration, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ProtoBuf.Grpc.Internal.ProxyEmitter.CreateFactory[TChannel,TService](Type baseType, BinderConfiguration binderConfig)
   at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultProxyCache`3..cctor() in C:\Code\protobuf-net.Grpc\src\protobuf-net.Grpc\Configuration\ClientFactory.cs:line 59
```
I added the `protobuf-net.Grpc` and `protobuf-net.Grpc.HttpClient` packages (both version 0.0.3-alpha54) so I don't think any assemblies are missing? Let me know if you need more details.

This is in a .NET Core 3.0 application.

EDIT: The following standalone code seems to reproduce it:
```c#
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System;
using System.Net.Http;
using System.ServiceModel;
using System.Threading.Tasks;

namespace GrpcClientTest
{
    [ServiceContract]
    public interface ITestService
    {
        Task<string> TestAsync(string request, CallContext context = default);
    }

    class Program
    {
        static void Main(string[] args)
        {
            var http = new HttpClient();
            var client = http.CreateGrpcService<ITestService>(); // Exception

        }
    }
}
```
As a .NET Core 3.0 (Preview 6) Console App, with the following packages installed:
- protobuf-net.Grpc (0.0.3-alpha.54)
- protobuf-net.Grpc.HttpClient (0.0.3-alpha.54)

**Comment by mgravell** [comment]
I think this may be a runtime mismatch because of the CLR preview bits; let me see what happens if I try to re-target my local to preview6 rather than the nightly... (I just need to actually download preview6...)

**Comment by mgravell** [comment]
Well, shoot; the installer says no:

[59A0:9480][2019-06-19T16:46:29]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

I'm kinda terrified of uninstalling preview7 to try and install preview6... I might need to wait until after the weekend at least.

(and yes, I've tried using global.json to tweak it - but I simply don't have preview6 on the box)

**Comment by mgravell** [comment]
ooh, idea, depending on how much time you have: if you `git clone` the repo, you could try changing the `global.json` to preview6, and then just (from the root) `dotnet restore` and `dotnet build`. It... might work? And then try testing with a project reference to the packages you've just built, rather than the nuget packages (`<ProjectReference>` rather than `<PackageReference>`)

**Comment by mgravell** [comment]
heh, I tried that in a sandbox VM, and ... it isn't quite there unless you have the IDE installed; currently 10 failures related to nullable checks...

**Comment by jamiewinder** [comment]
Yea, I gave it a go and found the same. Plus a few errors around `AsyncEnumerable` / `ReadAllAsync` which are presumably new things too. If I'm feeling brave, I'll look into using preview 7 tomorrow.

Thanks for your help.

**Comment by mgravell** [comment]
I have a sandbox installing - I might be able to get a preview6 build in a few hours.

**Comment by mgravell** [comment]
well, I got the build working - it wasn't *clean*, but it worked; but... it won't pack on preview6, so I can't really deploy it; I'm not sure it is worth spending more time trying to fight against an obsolete and known-buggy version of the framework :-(

**Comment by jamiewinder** [comment]
Is preview 6 obsolete? It's only been out a week! I didn't know it was considered buggy either. 

Thanks your help and efforts. I'll revisit this library once the framework catches up to it!

**Comment by ogauthier** [comment]
Got the same problem, Preview 6 with latest packages:
protobuf-net.Grpc (0.0.3-alpha.68)
protobuf-net.Grpc.HttpClient (0.0.3-alpha.68)

**Comment by mgravell** [comment]
The "buggy" there is mostly the compiler. If you don't have the latest compiler, trying to compile *the lib itself* is going to be an exercise in pain.

I probably over-spake in the context of preview6; I *am* using features from the dailies (the preview of preview7, if that makes sense), but that is actually trivial to overcome (I already have a debugger symbol for that).

My real problem, I guess,is that I don't have a machine with the latest compiler and preview6. I don't have time to spin up a VM for that combination. That's the real blocker for me.doing a preview6 nuget build.

**Comment by ogauthier** [comment]
Ok I installed the latest preview 7 bit, 3.0.0-preview7-27819-12.
And now I can't get it to compile...
error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 3.0.0-preview7-27819-12)
Any idea how to get around this?

**Comment by mgravell** [comment]
ok; was it specific about what project it got that from? the only one I can see is protobuf-net.Grpc.AspNetCode, and I've **removed it from there** (seconds ago, try pulling latest)

**Comment by ogauthier** [comment]
Just cloned the repo from scratch, still have same issue:
C:\Repos\protobuf-net.Grpc\examples\grpc\Shared\Shared.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 3.0.0-preview7-27819-12)

All projects have same error.

**Comment by mgravell** [comment]
that's weird; in particular, the key thing about grpc\Shared\Shared.csproj  - the **defining feature**, in fact, is that it doesn't use *anything new*; it is using all the old versions of *everything* (the "GA" versions of the google tools, only).

I ... don't know what to do there; again, this sounds like preview tooling problems more than anything I directly control.

**Comment by ogauthier** [comment]
What version of preview7 do you use? I'm going to try with the exact same.

**Comment by mgravell** [comment]
currently:  Version:   3.0.100-preview7-012380

**Comment by mgravell** [comment]
FYI: will be AFK for a few days - heading to NL to **talk about this stuff, yay!**; all I can say is "good luck‽" - I'll try and setup a good preview6 build when I get back - that's probably going to be my best route forward

**Comment by ogauthier** [comment]
Ok I got it to work with my preview.
I had to add a Nuget.config to your solution with this inside:
```
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-windowsdesktop" value="https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/index.json" />
    <add key="aspnet-aspnetcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/index.json" />
    <add key="aspnet-aspnetcore-tooling" value="https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/index.json" />
    <add key="aspnet-entityframeworkcore" value="https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json" />
    <add key="aspnet-extensions" value="https://dotnetfeed.blob.core.windows.net/aspnet-extensions/index.json" />
    <add key="gRPC repository" value="https://grpc.jfrog.io/grpc/api/nuget/v3/grpc-nuget-dev" />
  </packageSources>
</configuration>

```
As instructed by the Core SDK documentation here: https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries

I didn't know since I never before used preview SDKs.

**Comment by ogauthier** [comment]
I suggest you create a working setup with Preview6.

**Comment by jakejscott** [comment]
Was running into this exact same issue today too. Will try adding that Nuget.config to see if it fixes my problems too. :)

**Comment by mgravell** [comment]
When I've got past this weekend, I'm going to try uninstalling .net core completely and resetting to preview 6. There's no way on this planet that I'm going to risk that today - need to be able to demo tomorrow morning.

**Comment by AnthonyM** [comment]
I'm getting the same exception running preview 6

**Comment by mgravell** [comment]
0.0.3-alpha.96 is built against vanilla preview6
