### ISSUE TITLE
Parallel test execution leads to non-concurrent collection problems

### ISSUE THREAD

**Issue by molson194** [protobuf-net/protobuf-net.Grpc#202]
We have created one code-first GRPC service, but when we try to run multiple integration tests at the same time, we hit the following error for half of our tests.

    fail ProtoBuf.Grpc.Server.ServicesExtensions.CodeFirstServiceMethodProvider[0]
    Operations that change non-concurrent collections must have exclusive access.
    A concurrent update was performed on this collection and corrupted its state.
    The collection's state is no longer correct.

The other half of our tests have this message (showing that they succeed to set up the ProbeService)

     info: ProtoBuf.Grpc.Server.ServicesExtensions.CodeFirstServiceMethodProvider[0] RPC services being provided by ProbeService: 1

Our parallel test execution happens at the method level

    [assembly: Parallelize(Scope = ExecutionScope.MethodLevel, Workers = 0)]

During test setup, we instantiate an in-memory ASP.NET Core app using a [custom web application factory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0#customize-webapplicationfactory)

    using var customWebFactory = new CustomWebAppFactory();
    var client = customWebFactory.Channel.CreateGrpcService<IProbeService>(); // This is where the failure happens

Inside our web application factory, we expose the GRPC channel as a property.

    Channel = GrpcChannel.ForAddress($"http://localhost:{grpcPort}/", new GrpcChannelOptions
    {
        HttpClient = CreateClient(),
    });

Our probe service interface looks like this.

    [ServiceContract]
    public interface IProbeService
    {
        public Task<ProbeResponse> Probe(ProbeRequest request);
    }

And our implementation of IProbeService looks like this

    public class ProbeService : IProbeService
    {
        private readonly ILogger<ProbeService> _logger;

        public ProbeService(ILogger<ProbeService> logger)
        {
            _logger = logger;
        }

        public Task<ProbeResponse> Probe(ProbeRequest request)
        {
            _logger.Probe(request.Value);
            return Task.FromResult(new ProbeResponse(request.Value));
        }
    }

It looks like the CodeFirstServiceMethodProvider cannot handle the parallel test execution. For now, I've worked around the issue by running these tests sequentially, but eventually I'd love to run them in parallel. Any thoughts on how to fix the concurrent access issues?

**Comment by molson194** [comment]
Turns out the parallel CustomWebAppFactories were sharing the same gRPC port. Making the ports unique during parallel execution fixed the issue!

**Comment by molson194** [comment]
Re-opening as the issue is still happening. Just less often.

**Comment by molson194** [comment]
I found out the issue and created [this pull request](https://github.com/protobuf-net/protobuf-net.Grpc/pull/215) as a possible solution (though I think it needs a little bit of work).

Temporary Solution: Inject an instance of the ServiceBinder
```
var threadSafeServiceBinder = new ThreadSafeServiceBinder();
var binderConfiguration = BinderConfiguration.Create(null, threadSafeServiceBinder);
services.AddSingleton<BinderConfiguration>(binderConfiguration);
```
```
public class ThreadSafeServiceBinder : ServiceBinder{}
```

Problem: Static properties are not thread safe. When multiple threads are running at the same time, the ServiceBinder's dictionary (_map) has non-concurrent accesses.
```
public static ServiceBinder Default { get; } = new ServiceBinder();
```

The PR linked above attempts to solve the issue by removing static default properties and replacing with default constructors. I 100% realize that running multiple gRPC-based apps at the same time is an obscure use case, so let me know what is the right way forward.

Note: many other static default properties exist in the repo, but none of them are leading to threading issues. However, if the code changes in the future, they could cause issues.

**Comment by mgravell** [comment]
As discussed on #215, the preferred approach here would be to fix any errors in the existing API, rather than smash the API; I've dropped #216 into the queue, which should fix this; the other types appear to be either inherently immutable, or already consider thread safety. If we've missed something, we can fix that too (ultimately, race conditions aren't trivial to test, so it is hard to say "we've definitely fixed every possible edge race case" here)

**Comment by mgravell** [comment]
1.0.162 should be available on myget now: https://www.myget.org/F/protobuf-net/api/v3/index.json

**Comment by molson194** [comment]
The change worked! Thanks so much. Side note - I also had to upgrade protobuf-net.Grpc to version 1.0.162 (I think that's where the fix went).
