### ISSUE TITLE
Exception handling middleware / Interceptors

### ISSUE THREAD

**Issue by GoNextGroup** [protobuf-net/protobuf-net.Grpc#22]
Hello. 

Is it possible to add here any mechanism to realize interceptors and exceptions handling on the client and server side? 

Thank you.

**Comment by mgravell** [comment]
Are you talking about something that already exists in the main gRPC library, that I'm not exposing - or are you talking about something bespoke and new?

For the first: indeed I haven't done anything extra there; show me the API and I'll consider it

For the second: what would you propose?

**Comment by mythz** [comment]
You'll likely want to expose it in your AddCodeFirstGrpc ext method:

```csharp
public static void AddCodeFirstGrpc(this IServiceCollection services, Action<GrpcServiceOptions> configureOptions)
{
    services.AddGrpc(configureOptions);
    services.TryAddEnumerable(ServiceDescriptor.Singleton(typeof(IServiceMethodProvider<>), typeof(CodeFirstServiceMethodProvider<>)));
}
```

So it can be added like:

```csharp
services.AddCodeFirstGrpc(options => options.Interceptors.Add(....));
```

**Comment by GoNextGroup** [comment]
Yeah, It will be very good to wide AddCodeFirstGrpc with "configureOptions", but it's not critical.
I can use the code like this for it:

```
    public static class GZipCodeFirstGrpc
    {
        public static void AddGZipCodeFirstGrpc(this IServiceCollection services)
        {
            var gzipCompressionProvider = new GzipCompressionProvider(CompressionLevel.Optimal);
            Action<GrpcServiceOptions> configureOptions = e =>
            {
                e.CompressionProviders.Add(gzipCompressionProvider);
                e.Interceptors.Add(typeof(TestInterceptor));
            };
            services.Configure(configureOptions).AddCodeFirstGrpc();
        }
    }
```
But I have no idea how to add interceptors via `protobuf-net.Grpc` on the client side. 

And in general, interceptors cannot be configured to catch exceptions generates by code. 
ASP.NET Core has great mechanism of controllers' exceptions catching by the custom filters. But it doesn't work with the grpc calls (I've tried to realize). 

The main idea is connected with the DRY principle - I don't want to repeat try-catch blocks in all grpc calls, but I want to realize it once. It could be realized on the server side by wrapping in try-catch `UnaryServerHandler` method in the Interceptor and adding it through `AddCodeFirstGrpc` on the server side, but no current way to add on the client side. And, of course, If I use ASP.NET Core + gRPC, I want to use well-working exception handling mechanism which is realized in the ASP.NET Core.

**Comment by GoNextGroup** [comment]
Potentially, It could be added here (interceptors for the grpc client) in the 

```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TService CreateGrpcService<TService>(this ChannelBase client, ClientFactory? clientFactory = null)
            where TService : class
                    => (clientFactory ?? ClientFactory.Default).CreateClient<TService>(client.CreateCallInvoker());
```

You could rewrite it like:

```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TService CreateGrpcService<TService>(this ChannelBase client, ClientFactory? clientFactory = null, Interceptor[] interceptors = null)
            where TService : class
                    => (clientFactory ?? ClientFactory.Default).CreateClient<TService>(interceptors != null ? client.CreateCallInvoker().Intercept(interceptors) : client.CreateCallInvoker());
```

**Comment by mgravell** [comment]
1.0.13 added an overload that allows this configuration at the server, both on the input and the return

I *think* that covers everything here, so I'm marking it as completed by https://github.com/protobuf-net/protobuf-net.Grpc/commit/18ef9be0349aa607ccbf8c2a0b69046c83183844 - if I'm wrong, ping me and we can reopen.

**Comment by GoNextGroup** [comment]
Marc, I think, you also should add interceptors on the client side. Earlier I wrote the code examples which could be used:

```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TService CreateGrpcService<TService>(this ChannelBase client, ClientFactory? clientFactory = null, params Interceptor[] interceptors)
            where TService : class
                    => (clientFactory ?? ClientFactory.Default).CreateClient<TService>(interceptors.Length > 0 ? client.CreateCallInvoker().Intercept(interceptors) : client.CreateCallInvoker());

```
or

```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TService CreateGrpcService<TService>(this ChannelBase client, ClientFactory? clientFactory = null, params Interceptor[] interceptors)
            where TService : class
                    => (clientFactory ?? ClientFactory.Default).CreateClient<TService>(interceptors.Length > 0 ? client.Intercept(interceptors) : client.CreateCallInvoker());
```
On the server side  `Action<GrpcServiceOptions>` is really enough.

**Comment by mgravell** [comment]
@GoNextGroup  k; let's consider this (#22) "server-side", and we'll take the client-side conversation to #26
