### ISSUE TITLE
Using code without attributes

### ISSUE THREAD

**Issue by liujiyuan** [protobuf-net/protobuf-net.Grpc#224]
Is there any way using code register interface service in runtime instead of [ServiceContract]?
just like RuntimeTypeModel instead of [DataContract] [ProtoMember]

**Comment by mgravell** [comment]
Possible: yes. But a different API. Not at a PC, but I believe you'd need to create your own `ServiceBinder`. We could perhaps create a pre-rolled "add your own types/methods" API to the library, but: it doesn't exist today IIRC

**Comment by liujiyuan** [comment]
Yes，I need the different API. Will you have a plan to develop the API or could you give me some suggestion to develop the Api by myself?
Thank you very much!

**Comment by mgravell** [comment]
completely untested, but something like this should work:

``` c#
class MyBinder : ServiceBinder
        {
            public MyBinder()
            {
                BinderConfiguration = BinderConfiguration.Create(binder: this);
                ClientFactory = ClientFactory.Create(BinderConfiguration);
            }

            readonly ConcurrentDictionary<Type, string> _services = new();
            readonly ConcurrentDictionary<MethodInfo, string> _operations = new();

            public override bool IsServiceContract(Type contractType, out string? name)
                => _services.TryGetValue(contractType, out name);
            public override bool IsOperationContract(MethodInfo method, out string? name)
                => _operations.TryGetValue(method, out name);

            public bool Add(Type service, string name)
                => _services.TryAdd(service, name);
            public bool Add(MethodInfo operation, string name)
                => _operations.TryAdd(operation, name);

            public BinderConfiguration BinderConfiguration { get; } 
            public ClientFactory ClientFactory { get; }
        }
```

You'd new-up a `MyBinder`, `.Add(...)` your services and operations, and make use of the `.BinderConfiguration` and `.ClientFactory` when creating instances or configuring the server. I can try to be more specific if needed.

**Comment by liujiyuan** [comment]
Thank you very much!!!

**Comment by mgravell** [comment]
I fleshed things out a bit to check it worked both server-side and client-side: https://github.com/protobuf-net/protobuf-net.Grpc/blob/main/tests/protobuf-net.Grpc.Test/Issues/Issue224.cs

Any problems; let me know!

**Comment by liujiyuan** [comment]
Thanks a lot!
