### ISSUE TITLE
Interceptors not beeing called

### ISSUE THREAD

**Issue by menaheme** [protobuf-net/protobuf-net.Grpc#227]
Hi, 
I used the sample [here](https://github.com/protobuf-net/protobuf-net.Grpc/blob/main/examples/pb-net-grpc/Server_CS/Startup.cs) as a starting point for testing out gRpc (code first)
and added a trivial interceptor like so:
```
 services.AddCodeFirstGrpc(config =>
            {
                config.ResponseCompressionLevel = System.IO.Compression.CompressionLevel.Optimal;
                config.Interceptors.Add<MyInterceptor>();
            });
```
the interceptor only contains  `Console.WriteLine("interceptor")` for BlockingUnary calls (that are getting through)

for some reason the interceptor isn't beeing called (placed a breakpoint in it to be sure), the call does gets processed by the server. 

Am i doing something wrong ?

**Comment by mgravell** [comment]
Can I see MyInterceptor? IIRC there are separate client and server APIs to override here.

**Comment by menaheme** [comment]
Sure:

```
using Grpc.Core;
using Grpc.Core.Interceptors;

namespace Test
{
public class AuthorizationInterceptor : Interceptor
{
    public override TResponse BlockingUnaryCall<TRequest, TResponse>(TRequest request, ClientInterceptorContext<TRequest, TResponse> context, BlockingUnaryCallContinuation<TRequest, TResponse> continuation)
    {
    Console.WriteLine(">>auth interceptor");
    
    context.Options.Headers.Add("context-data-item", "some-test-data");
    
    return base.BlockingUnaryCall(request, context, continuation);
    }
}
}
```

**Comment by mgravell** [comment]
if you are intercepting at the server, you need to overide `UnaryServerHandler` - is that the problem?

**Comment by menaheme** [comment]
Smacking forhead

If course is, sorry to have wasted your time, 

As a side note, wouldn't it be better to have separate classes for client and server? 
(just curious, this is a question for dotnet-rpc)

**Comment by mgravell** [comment]
Since the APIs are functionally separate: that would be a valid implementation, but I guess they wanted to keep it simple and avoid similar looking types. But your view has merit: you wouldn't have spent time on this if they were separate.

**Comment by menaheme** [comment]
[Aasked](https://github.com/grpc/grpc-dotnet/issues/1619) at grpc net , they also agree, but cant do much about it
Thanks again!
