### ISSUE TITLE
Best way to implement inherited records with complex types and collections

### ISSUE THREAD

**Issue by ddieruf** [protobuf-net/protobuf-net.Grpc#229]
I am looking for a little guidance on the best way to arrange a more complex use case. I have many records that are sometimes inherited from one another. Any of the records could have primitive or complete types. Many of which are Enumerated. Assuming I decorate `Level300` on the assembly I was expecting everything to _just work_. The schema output was very close to expectation, except for the Enumeration. My goal is to add as little decoration (ie: attribute) as possible. Ideally the records are kept in a very basic POCO kind of state, and I provide proto direction on the `[Service]`.

I expected `IEnumerable<ConferenceOverview>` to be `repeated ConferenceOverview` in the schema, but it's going back to the old compatibility of `IEnumerable_ConferenceOverview`.

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ProtoBuf;
using ProtoBuf.Grpc.Configuration;
using ProtoBuf.Grpc.Reflection;
using ProtoBuf.Meta;
using Xunit;

[assembly: CompatibilityLevel(CompatibilityLevel.Level300)]
namespace MyTests;

[Service]
public interface IMyService
{
  ValueTask CreateDocument(CreateDocumentRequest request);
}

[ProtoContract(ImplicitFields = ImplicitFields.AllPublic)]
public record ConferenceOverview(
  Guid Id,
  string Title
);

public record CreateDocumentRequest(
  Guid RequestId,
  IEnumerable<ConferenceOverview> Conferences
): Document(RequestId);

public record Document(Guid RequestId);

public class AccountSystemContractTest
{
  [Fact]
  public async Task SchemaGenerator_produces_unexpected_collection_type()
  {
    var generator = new SchemaGenerator
    {
      ProtoSyntax = ProtoSyntax.Proto3
    };

    var schema = generator.GetSchema( typeof( IMyService ) );

    using (var writer = new StreamWriter("services.proto"))
    {
      await writer.WriteAsync(schema);
    }
  }
}
```

Output:
```proto
syntax = "proto3";
package MyTests;
import "google/protobuf/empty.proto";

message ConferenceOverview {
   string Id = 1; // default value could not be applied: 00000000-0000-0000-0000-000000000000
   string Title = 2;
}
message CreateDocumentRequest {
   string RequestId = 1;
   IEnumerable_ConferenceOverview Conferences = 2;
}
service MyService {
   rpc CreateDocument (CreateDocumentRequest) returns (.google.protobuf.Empty);
}
```

**Comment by mgravell** [comment]
This is indeed a complex one; honestly, I'm not sure *inherited* records are currently a great fit for protobuf-net DTOs; very simple `record` types that just use positional parameters, no inheritance and no attributes: should work fine, but this scenario would need a *lot* of thought to even figure out what we think the "correct" behaviour should be - for example, normally in an inheritance scenario we'd expect a bit more nuance here for LSP reasons. Right now I'd just say: "don't do this", honestly. Use regular full classes where we can understand and control the full model. Happy to put this on the list of scenarios to consider, but it is very far from trivial.

**Comment by ddieruf** [comment]
Ok so, with that said, I would like to find a good medium between manually writing the proto and fully software defined. Any thoughts?

**Comment by mgravell** [comment]
That's very vague. If you mean you want lighter weight code-first usage, then: as I say, positional non-inherited `record` usage works for many simple cases, but have their limits in terms of how far we currently analyze the model. Could that be improved? Possibly, but it would need some very detailed planning. If that isn't what you mean, please help me understand.

**Comment by ddieruf** [comment]
Sorry for the vagueness. The inheritance part is not something I can change. It's used a lot throughout the app. I need to find something that includes records with inheritance.

What about getting fancy with [Any](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any)? This comes with its own challenges I know, but is this something I could use to support the above case?

**Comment by mgravell** [comment]
No, not really. For starters, we have not, to date, had opportunity+need to implement `Any` as a first-class citizen; but mainly: when discussing `Any` - a protobuf concept - you need to focus on the reality that inheritance *isn't* a protobuf concept (we basically fake it in protobuf-net); attempting to mix `Any` and inheritance is probably not a good idea, and will end badly.

**Comment by ddieruf** [comment]
Thank you for the feedback. This is very helpful.
