### ISSUE TITLE
Grpc client factory add interceptor not working

### ISSUE THREAD

**Issue by irajchardoli** [protobuf-net/protobuf-net.Grpc#237]
Hi,
I have a question, I created a grpc service and used the grpc client factory for creating a channel, I also add an interceptor to the channel factory, but my interceptor never raised, I don't know where am I wrong:

       public class RequestLoggerInterceptor : Interceptor
        {
                       public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
                                       TRequest request,
                                     ServerCallContext context,
                                     UnaryServerMethod<TRequest, TResponse> continuation)
               {
                  Stopwatch sw = Stopwatch.StartNew();

            TResponse response = await base.UnaryServerHandler(request, context, continuation);

            sw.Stop();

            string tt = $"{context.Method} responded {context.Status.StatusCode} in {sw.Elapsed.TotalMilliseconds:0.0000} ms";

            Console.WriteLine(tt);

            return response;

and in the IoC:

           services.AddCodeFirstGrpcClient<IMyService>(
                    o =>
                    {
                        o.Address = new Uri(serviceAddress);
                        o.Interceptors.Add(new RequestLoggerInterceptor());
                    })

**Comment by mgravell** [comment]
how did you create/obtain the client instance in the calling code?

**Comment by mgravell** [comment]
ah, I think I see the more likely problem; `UnaryServerHandler` is for server-side interceptors; you probably want to `override` the `AsyncUnaryCallContinuation` or `BlockingUnaryCallContinuation` method

**Comment by irajchardoli** [comment]
Thanks for the quick reply, I should have used AsyncUnaryCall.

**Comment by menaheme** [comment]
I also tripped over this one, questioned jamesNk about the interface design
,
But he said its too late to change it
