### ISSUE TITLE
Support WriteAsync cancellation token

### ISSUE THREAD

**Issue by JamesNK** [protobuf-net/protobuf-net.Grpc#239]
`IAsyncStreamWriter<T>` adds a default interface implementation for `WriteAsync` that takes a cancellation token: https://github.com/grpc/grpc-dotnet/blob/c0779fc83fd71f9e1644f6312fbe1fa4980bec3f/src/Grpc.Core.Api/IAsyncStreamWriter.cs#L41-L57

I'm not sure if protobuf-net.Grpc exposes that type publically, but if it does then it should implement the DIM to use the cancellation token.

**Comment by mgravell** [comment]
No can do; the library is implementation agnostic, and it explodes here: https://github.com/grpc/grpc-dotnet/issues/1747

Suggestions?

**Comment by mgravell** [comment]
@JamesNK bump

**Comment by JamesNK** [comment]
The default implementation is to explode. Are you not overriding the default implementation?

**Comment by JamesNK** [comment]
Or do you not implement `IAsyncStreamWriter` at all? Does this problem happen when Grpc.Core is used?

Grpc.Core doesn't support write cancellation and never will. You could detect if Grpc.Core is used and not call the `CancellationToken` overload.

**Comment by mgravell** [comment]
We don't provide the writer - the channel implementation does - so: it isn't for "us" (meaning: this library) to override; the *intention* was to be implementation agnostic, or at least use publicized feature detection (like the "supports WriteAsync" part of the linked topic). If we have to drop down to specific library detection, I *guess* we can do that, but it isn't ideal.

**Comment by JamesNK** [comment]
How about thinking about this from a different direction. A developer is using Grpc.Core, writes a message with a cancellation token. What should the outcome be?:

1. The library silently ignores the cancellation token.
2. The library tells the user that the cancellation token isn't supported via an error.

Personally, I think 2 is better. It is less confusing.

By the way, there's no need to pass the ServerCallContext CancellationToken to this method. If you're doing that then an active CT is always being passed to WriteAsync and it will always explode. WriteAsync is like the `HttpRequest.Body` and `HttpResponse.Body` streams: it implicitly uses the request's cancellation token.

**Comment by mgravell** [comment]
Re `ServerCallContext`: that's fair - but I guess I'm thinking more of the incoming client `CallOptions` CT, in a client-streaming or client-half of a full-duplex scenario; good to know I don't need to worry about the server half, though. If the `CallOptions` CT is already respected, then: I guess there's nothing I need to do... so: is it? could it be?

---

Re your 1/2 question; from my consumers perspective, 1 is what would happen anyway, if we detect the limitation and call WriteAsync without throwing in the CT; and would give them what they have today without the change

**Comment by JamesNK** [comment]
On the server, `HttpContext.RequestAborted` is always implicitly used. On the client, `CallOptions.CancellationToken` and disposing of the call are always implicitly used.

**Comment by mgravell** [comment]
it sounds like there's nothing to do here, then; we already pass in the client CT via `CallOptions` - so it sounds like for both client and server, there's no need for us to supply the CT explicitly; agree?

**Comment by JamesNK** [comment]
Unless there is an API in protobuf-net.Grpc that lets a dev pass a CT token per write async call (I don't know what your streaming looks like off the top of my head) then there's no need to use it.

**Comment by mgravell** [comment]
No, we don't have that; what we do is: the caller gives us an `IAsyncEnumerable<T>` (either as an input, or as a return value from a server function) which we *consume*, writing to the writer; once they've given it to us, that's it: they don't get access to the per-call writes. We just try to respect the CT provided originally (whether as a client arg, or the ambient server cancel)

**Comment by mgravell** [comment]
Closing out; no work necessary at current time. Happy to revisit if that changes.
