### ISSUE TITLE
MarshallerFactory access modifier problem

### ISSUE THREAD

**Issue by GoNextGroup** [protobuf-net/protobuf-net.Grpc#24]
Hello, Marc.

Is it possible to remove "internal" access modified from `CreateMarshaller`. I try to realize my own class like GRPCClientPOCO, which uses alternative approach. But it's really not possible to create derived class which can override `CreateMarshaller`. Could you remove this modificator? 
Thnxs.

**Comment by mgravell** [comment]
The modifier here is `protected internal`, not `internal`, which means `protected` when seen from an external library. Here's some compiling (but pointless) code that works fine in an unrelated library:

``` c#
class UselessMarshaller : MarshallerFactory
{
    protected override Marshaller<T> CreateMarshaller<T>() => null;
    protected override bool CanSerialize(Type type) => false;
}
```

So: it isn't `internal`. What is it that you want to do? What scenario are you trying to implement? Whatever it is, I probably need to understand it to ensure that the API is appropriate and supportable for that usage.

**Comment by GoNextGroup** [comment]
Marc, could you explain how to build `Marshaller<T>` through this approach? I always though that in  abstract factory approach you should have a public `Create` method.
Let's see the idea I want to realize.
I want to create new client class like this:

```
    public class GRPCClientPOCO
    {
        private readonly CallInvoker invoker;
        private readonly JsonMarshallerFactory marshallerFactory;
        private readonly ConcurrentDictionary<(Type, Type, string, string), object> methods;
        private readonly CallOptions callOptions;

        public GRPCClientPOCO(MarshallerFactory marshallerFactory,  Interceptor []interceptors, string connectionAddress)
        {
            //GrpcClientFactory.AllowUnencryptedHttp2 = true;

            methods = new ConcurrentDictionary<(Type, Type, string, string), object>();

            var httpClient = new HttpClient()
            { 
                DefaultRequestVersion = new Version(2, 0), 
                //BaseAddress = new Uri(connectionAddress) 
            };

            var channelOptions = new GrpcChannelOptions()
            {
                HttpClient = httpClient,
                DisposeHttpClient = false,
            };

            var gzipCompressionProvider = new GzipCompressionProvider(System.IO.Compression.CompressionLevel.Optimal);
            channelOptions.CompressionProviders = new List<ICompressionProvider>() { gzipCompressionProvider };

            var grpcChannel = GrpcChannel.ForAddress(connectionAddress, channelOptions);
            invoker = interceptors != null ? grpcChannel.Intercept(interceptors) : grpcChannel.CreateCallInvoker();
            
            this.marshallerFactory = marshallerFactory;
            callOptions = default;
        }

        public async Task<TResponse> Execute<TRequest, TResponse>(TRequest request, string serviceName, string methodName) where TRequest : class
                                                                                                               where TResponse : class
        {
            object method;

            if (!methods.ContainsKey((typeof(TRequest), typeof(TResponse), serviceName, methodName)))
            {
                var requestMarshaller = marshallerFactory.CreateMarshaller<TRequest>();
                var responseMarshaller = marshallerFactory.CreateMarshaller<TResponse>();

                method = new Method<TRequest, TResponse>(MethodType.Unary, serviceName, methodName,
                                                             requestMarshaller, responseMarshaller);
                methods.TryAdd((typeof(TRequest), typeof(TResponse), serviceName, methodName), method);
            }
            else 
            {
                method = methods.GetValueOrDefault((typeof(TRequest), typeof(TResponse), serviceName, methodName));
            }

            var castedMethod = method as Method<TRequest, TResponse>;
            using var auc = invoker.AsyncUnaryCall(castedMethod, null, callOptions, request);

            return await auc.ResponseAsync;
        }
    }
```

And here  `JsonMarshallerFactory` is
```

    public class JsonMarshallerFactory : MarshallerFactory
    {
        protected readonly List<Type> types;
        protected readonly JsonSerializerSettings jsonSettings;
        protected ConcurrentDictionary<Type, object> marshallersDictionary;

        public JsonMarshallerFactory() :this(null) 
        { 
        }
        public JsonMarshallerFactory(List<Type> types) :base() 
        {
            this.types = types;

            jsonSettings = new JsonSerializerSettings()
            {
                CheckAdditionalContent = true,
                MetadataPropertyHandling = MetadataPropertyHandling.ReadAhead,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                TypeNameHandling = TypeNameHandling.All,
                Formatting = Formatting.Indented,
                TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full,
            };
        }

        protected override bool CanSerialize(Type type)
        {
            return true;
        }

        protected override byte[] Serialize<T>(T value)
        {
            var json = JsonConvert.SerializeObject(value, jsonSettings);

            return Encoding.UTF8.GetBytes(json);
        }
        protected override T Deserialize<T>(byte[] payload)
        {
            var json = Encoding.UTF8.GetString(payload);
            var result = JsonConvert.DeserializeObject<T>(json, jsonSettings);

            return result;
        }

        public override Marshaller<T> CreateMarshaller<T>() //here is the problem
        {
            if (marshallersDictionary.ContainsKey(typeof(T)))
            {
                var newTypeMarshaller = new Marshaller<T>(Serialize<T>, Deserialize<T>);
                marshallersDictionary.TryAdd(typeof(T), newTypeMarshaller);

                return newTypeMarshaller;
            }
            else
            {
                return marshallersDictionary.GetValueOrDefault(typeof(T)) as Marshaller<T>;
            }
        }
    }

```

I can use my this base class or derived class from GRPCClientPOCO with DI.

`            services.AddSingleton(p => p.ResolveWith<GRPCClientPOCO>(new JsonMarshallerFactory(), null, serverAddressConfig.Get<ServerAddressConfig>().TokenServer));`

Here 

```
        public static T ResolveWith<T>(this IServiceProvider provider, params object[] parameters) where T : class =>
            ActivatorUtilities.CreateInstance<T>(provider, parameters);
```
(This is a simple example and not so smart code).

But in this case I cannot override `CreateMarshaller`.

**Comment by mgravell** [comment]
Am I misunderstanding the example? It looks like you're going direct to the
grpc API for most things, rather than going via this library. That's fine -
but it seems arbitrary to try to use the *marshaller layer* from this
library, but nothing else. If you're going direct to the grpc API for
everything else, why wouldn't you direct to the grpc API for the marshaller?

It is 23:00 on a Sunday evening, though, so it is possible that I'm just
misreading the code...

**Comment by GoNextGroup** [comment]
My code is connected with an alternative POCO approach which was added earlied by the closed request. I've just rewrite the code of the mythz wrapped it in the class.
I tried to realize mythz code through `CreateGrpcService` way (maybe with some additions in the main protobuf-net.grpc library), but my C# skills wasn't enough for this. 
I use `AddCodeFirstGrpc` on my server side with `IGrpcService` with a little additions ('GrpcServiceOptions` parameter and some interceptors - I wrote about this earlier in the issue block).

**Comment by GoNextGroup** [comment]
Possible, it's possible to realize mythz's code approach by realization of this interface:


```
    public interface IGrpcClientSide
    {
        Task<TResponse> Execute<TRequest, TResponse>(TRequest request);
    }
```
I'll try to do this tommorow...

**Comment by mythz** [comment]
@GoNextGroup FYI I've just published a preview of ServiceStack's gRPC support you can [read about on the Customer Forums](https://forums.servicestack.net/t/preview-grpc-support/7867).

Here's our implementation of ServiceStack's [GrpcServiceClient.cs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.GrpcClient/GrpcServiceClient.cs) which allows for our ideal [typed Service Client API](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Interfaces/IRestClientAsync.cs) we were after, some usage examples are in our gRPC integration tests:

 - [GrpcTests.cs](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.Extensions.Tests/GrpcTests.cs)
 - [GrpcAuthTests.cs](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.Extensions.Tests/GrpcAuthTests.cs)
 - [GrpcAutoQueryTests.cs](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.Extensions.Tests/GrpcAutoQueryTests.cs)

We're also using a custom marshaller to support inheritance which you can see how we're registering and implementing in [GrpcFeature.cs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Extensions/GrpcFeature.cs).

The code-first support available now will allow you to implement your `IGrpcClientSide` interface.

**Comment by GoNextGroup** [comment]
mythz, the only problem I don't know how to solve is the "Service Name" and "Service Method" parameters passing - I do not know how to correctly pass it to the CallInvoker. I think, It's not possible in the current realization.

**Comment by mythz** [comment]
@GoNextGroup Not sure what you mean, here's how we're passing in the `serviceName` and `methodName`:

https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.GrpcClient/GrpcServiceClient.cs#L127-L129

```csharp
var method = new Method<TRequest, TResponse>(MethodType.Unary, serviceName, methodName,
    GrpcMarshaller<TRequest>.Instance, GrpcMarshaller<TResponse>.Instance);
var auc = invoker.AsyncUnaryCall(method, host, options, request);
```

**Comment by GoNextGroup** [comment]
> @GoNextGroup Not sure what you mean, here's how we're passing in the `serviceName` and `methodName`:
> 
> https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.GrpcClient/GrpcServiceClient.cs#L127-L129
> 
> ```cs
> var method = new Method<TRequest, TResponse>(MethodType.Unary, serviceName, methodName,
>     GrpcMarshaller<TRequest>.Instance, GrpcMarshaller<TResponse>.Instance);
> var auc = invoker.AsyncUnaryCall(method, host, options, request);
> ```

mythz, I know, if you will check my code, you see, that's just your code rewriting. I've wrapped it to the class and made it less "vanilla static".
I've just wanted to say that I don't know is it possible to use these parameters in the service which is created by the `CreateGrpcService`. I think this method should be rewritten for this ability.

**Comment by mgravell** [comment]
I *think* that for your purposes, the non-generic `CreateGrpcService()` API gives you what you need here;

usage is:

``` c#
// note you can pass a Type instead of a String to use the binder rules to resolve the serviceName
var service = channel.CreateGrpcService(serviceName);

// note you can pass a MethodInfo instead of a String to use the binder rules to resolve the methodName
var result = nonGeneric.BlockingUnary<TRequest, TResoinse>(request, methodName);
// (or any of the other APIs for async, streaming, duplex, etc)
```
