### ISSUE TITLE
File upload .net framework

### ISSUE THREAD

**Issue by vssarahan** [protobuf-net/protobuf-net.Grpc#242]
Good afternoon.
I use .net framework 4.6 for the client, .net standard for shared project, and .net core 3.1 for the backend. protobuf-net.Grpc allows me to use the Stream class as a DataMember in the server response class, but does not allow me to use Stream as a DataMember in the request class. How can I get around this limitation? Unfortunately, IAsyncEnumerable is not available for .net framework. Is it possible to do this without LangVersion tag ? Thanks!

**Comment by mgravell** [comment]
`Stream` is absolutely not supported. Can you clarify what you mean by "allows me to use" here? What is working? Note: I do plan to add some support for `Stream`, but that will be in place of a request/response class - not as part of one.

`IAsyncEnumerable` is absolutely available on .NET Framework, and the library adds the correct packages for that to work. However, if you want to use `await foreach`, then *that* requires a newer compiler version than ships out-of-the-box with .NET Framework. I can't help there, other than to say "use a newer compiler". You can use current compilers with .NET Framework without any difficulty.

**Comment by vssarahan** [comment]
"Allows me to use" means that this code works (although now I'm surprised since you say there is no support at the moment) :
`[DataContract]
    public class DownloadResult  {

        [DataMember(Order = 1)]
        public Boolean Success { get; set; }

        [DataMember(Order = 2)]
        public String ErrorMessage { get; set; }

        [DataMember(Order = 3)]
        public String FileName { get; set; }

        [DataMember(Order = 4)]
        public Stream Stream { get; set; }
    }`
I checked - the files are really downloaded. 
But I am not allowed to use this class:
`[DataContract]
    public class UploadRequest {

        [DataMember(Order = 1)]
        public String FileName { get; set; }

        [DataMember(Order = 2)]
        public Stream Stream { get; set; }
    }`

**Comment by mgravell** [comment]
"But I am not allowed to use this class" - what exactly happens? The request/response handling is basically identical, so I'm just as surprised by it working differently as I am by it doing something - anything - with `Stream` except exploding in a shower of sparks.

I tried the following:

``` c#
using ProtoBuf;
using System.Runtime.Serialization;

var clone = Serializer.DeepClone(new DownloadResult
{
    Success = true,
    ErrorMessage = "ok",
    FileName = "abc.pdf",
    Stream = new MemoryStream(new byte[] { 0, 1, 2, 3 })
});
```

and it said:

``` txt
Unhandled exception. System.InvalidOperationException: No serializer defined for type: System.IO.Stream
   at ProtoBuf.Internal.ThrowHelper.NoSerializerDefined(Type type) in /_/src/protobuf-net.Core/Internal/ThrowHelper.cs:line 73
   at ProtoBuf.Meta.ValueMember.BuildSerializer() in /_/src/protobuf-net/Meta/ValueMember.cs:line 486
   at ProtoBuf.Meta.MetaType.BuildSerializer() in /_/src/protobuf-net/Meta/MetaType.cs:line 492
   at ProtoBuf.Meta.MetaType.get_Serializer() in /_/src/protobuf-net/Meta/MetaType.cs:line 449
   at ProtoBuf.Meta.RuntimeTypeModel.<GetServicesSlow>g__GetServicesImpl|88_0(RuntimeTypeModel model, Type type, CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 1032
   at ProtoBuf.Meta.RuntimeTypeModel.GetServicesSlow(Type type, CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 998
   at ProtoBuf.Meta.RuntimeTypeModel.GetSerializer[T]() in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 961
   at ProtoBuf.Meta.TypeModel.TryGetSerializer[T](TypeModel model) in /_/src/protobuf-net.Core/Meta/TypeModel.cs:line 1485
   at ProtoBuf.Meta.TypeModel.DeepClone[T](T value, Object userState) in /_/src/protobuf-net.Core/Meta/TypeModel.cs:line 1546
   at ProtoBuf.Serializer.DeepClone[T](T instance, Object userState) in /_/src/protobuf-net/Serializer.cs:line 58
   at Program.<Main>$(String[] args) in C:\Code\ConsoleApp1\ConsoleApp1\Program.cs:line 4
```

As I say: I actively intend adding `Stream` support (it came up with a colleague), but that would be for simple scenarios only, i.e. things like:

``` C#
interface ISomeAPI
{
    Stream Read(SomeRequestType value);
    SomeResponseType Write(Stream value);
}
```

i.e. where the `Stream` *replaces* the gRPC payload entirely, allowing me to implement frames/buffers under the covers, perhaps with some attribute usage such as `[Stream(BufferSize = 16 * 1024, Flags = StreamFlags.AsyncOnly)]`

**Comment by vssarahan** [comment]
It's really amazing that it works for me.
And about IAsyncEnumerable - could you show me how I can then transfer the stream via a one-way channel from the client to the server? I only understand how to do this using async IAsyncEnumerable<T>.

**Comment by mgravell** [comment]
By "a one way channel", if you mean Channel-of-T: just create a Channel-T, use AsAsyncEnumerable() to get the API to pass to the library, and write to the . Writer - make sense?

**Comment by vssarahan** [comment]
I'm sorry, but I don't quite understand. My task is to transfer the file from the client to the server as a stream, while I have restrictions on using async IAsyncEnumerable with yield (not possible in the .net framework). Maybe there is some example, because I don't fully understand how this can be done optimally using your library. If the only optimal option is to use .net core sdk, then issue can be closed. In any case, I want to express my gratitude for the prompt answers and clarifications.

**Comment by mgravell** [comment]
It can all be done with .NET Framework. Not at a PC, but: see L185-L191
here:
https://github.com/protobuf-net/protobuf-net.Grpc/blob/18ddc4268af6ed7c77c60a8fc67a7d241f6c95ee/toys/PlayClient/Program.cs#L185
- this uses Channel<T> instead of async yield etc.

Happy to help more, but it would really help to discuss a more specific
context.
