### ISSUE TITLE
Sub class inherited properties not returned from grpc server

### ISSUE THREAD

**Issue by menaheme** [protobuf-net/protobuf-net.Grpc#246]
Hi,

I defined 2 response classes
```
[ProtoContract]
[ProtoInclude(50, RpcResponse<>)]
public class RpcRespose
{
   [ProtoMember(1)]
   int ReturnCode {get; set;}
}

[ProtoContract]
public class RpcRespose<T> : RpcResponse
{
   [ProtoMember(1)]
   T Data {get; set;}
}
```
Also i implemented an error handling Interceptor  (UnaryServerHandler)
That in case of specific exceptions returns an RpcRespose with an error code and a message (tip of the hat towards fault contracts)

```
public override async Task<TResponse> UnaryServerHandler(...)
{
  try
  {
     return await continuation(request, context);
  }
  catch(MyFaultException ex)
  {
    if (typeof(TRespose).IsSubClassOf(typeof(RpcRespose)))
    {
       //  in my test case, i throw a MyFaultException with the values 2. "test".
       return (TRespose)(Activator.CreateInstance(typeof(TResponse), new object[] {ex.ErrorCode, ex.Message});
    }
  }  
}
```

For some reason when working with a contract based on the return type RpcResponse<T>,  
 throwing a MyFaultException in the service implementation, deos indeed return an instance of RpcResponse<T>
but it contains default values rather than what was expected.

What am i missing ?

**Comment by menaheme** [comment]
Have you had the chance to look at this ?

**Comment by ScottKane** [comment]
You can't use open generic types, replace `[ProtoInclude(50, RpcResponse<>)]` with `[ProtoInclude(50, RpcResponse<SomeType>)]` You have to do this for every type you want to include as a generic.

**Comment by menaheme** [comment]
Understood, thanks
