### ISSUE TITLE
Grpc.Core.ClientBase Error in IIS when service invoked from Blazor Webassembly app

### ISSUE THREAD

**Issue by javipardoq** [protobuf-net/protobuf-net.Grpc#247]
Hi:

I'm having the following error in the browser console that is not allowing the Blazor Webassembly app to continue consuming the grpc API:

System.ArgumentException: The base-type Grpc.Core.ClientBase for service-proxy CalibrationSaaS.Application.Services.IBasicsServices`1[ProtoBuf.Grpc.CallContext] lacks a suitable CallInvoker API

The code where this is happening is the following:

var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler()));

       using (var channel = Grpc.Net.Client.GrpcChannel.ForAddress(builder.Configuration["Kestrel:Endpoints:Http3:Url"], new GrpcChannelOptions
        {
            HttpClient = httpClient
        }))
        {                
            var a = channel.CreateGrpcService<Application.Services.IBasicsServices<CallContext>>(); //The error happens in this line of code
            var b = await a.GetRoles(CallContext.Default); //This method is implemented
            return b;
        }
It was working until last week. This error Only happens when the application is published in the respective IIS, in the development Visual Studio environment it works normally.

This is the full stack trace:

System.AggregateException: AggregateException_ctor_DefaultMessage (TypeInitialization_Type, DefaultProxyCache1) ---> System.TypeInitializationException: TypeInitialization_Type, DefaultProxyCache1
---> System.ArgumentException: The base-type Grpc.Core.ClientBase for service-proxy CalibrationSaaS.Application.Services.IBasicsServices1[ProtoBuf.Grpc.CallContext] lacks a suitable CallInvoker API at ProtoBuf.Grpc.Internal.ProxyEmitter.EmitFactory[IBasicsServices1](BinderConfiguration binderConfig)
at ProtoBuf.Grpc.Internal.ProxyEmitter.CreateFactory[IBasicsServices1](BinderConfiguration binderConfig) at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultProxyCache1[[xxxx.Application.Services.IBasicsServices1[[ProtoBuf.Grpc.CallContext, protobuf-net.Grpc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67]], xxxx.Application.Services, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]..cctor() Exception_EndOfInnerExceptionStack at ProtoBuf.Grpc.Configuration.ClientFactory.DefaultClientFactory.CreateClient[IBasicsServices1](CallInvoker channel)
at xxxx.Infraestructure.Blazor.Program.Roles(WebAssemblyHostBuilder builder)
at xxxx.Infraestructure.Blazor.Program.Main(String[] args)
Exception_EndOfInnerExceptionStack

I appreciate if you could help me with this issue, I can provide more information if needed.

Thank you.

Regards.

**Comment by mgravell** [comment]
That sounds like the linker has erased the constructor in ClientBase, since
it doesn't detect it being used at build-time. You would need to configure
the linker to not do that.

**Comment by javipardoq** [comment]
Thank you @mgravell . Do you have a link in your documentation on how to do this configuration?

**Comment by mgravell** [comment]
No. This is a blazor issue, not a protobuf-net one. And I'm not a blazor person. If anyone cares to add notes, I'd gratefully accept a PR, but I'd start by looking at https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker

**Comment by JamesNK** [comment]
FYI there are annotations that might be able to be added to protobuf-net.Grpc to tell the linker not to erase constructors: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming#dynamicallyaccessedmembers

**Comment by mgravell** [comment]
I'll give that a go too, thanks @JamesNK

**Comment by achmstein** [comment]
Hi,

I tried to use the following code `<PropertyGroup>
  <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
</PropertyGroup>` but it didn't work.

**Comment by mgravell** [comment]
k, so: 1.0.171 is now up on myget, and incorporates what I *think* might help (based on @JamesNK 's comment); could you please try the muget feed (https://www.myget.org/F/protobuf-net/api/v3/index.json) and see if that helps?

**Comment by mgravell** [comment]
Awesome. Thanks for the hint @JamesNK; I'll deploy that to Nuget tomorrow

**Comment by javipardoq** [comment]
It worked great, we install the new update in our test and production environment, just as a summary, this is what we did.

1. We updated the version to 1.0.171 from Github
2. We added in our project file the following configuration:

<PropertyGroup> 
...
<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking> 
...
</PropertyGroup>

Thank you @mgravell and @JamesNK for your help.
