### ISSUE TITLE
ProxyEmitter.cs emit seems lack char '&'

### ISSUE THREAD

**Issue by fredliex** [protobuf-net/protobuf-net.Grpc#249]
hi @mgravell 

in ProxyEmitter.cs
- `case int i when (i >= -128 & i < 127): il.Emit(OpCodes.Ldc_I4_S, (sbyte)i); break;`
- `case int i when (i >= 0 & i <= 255): il.Emit(OpCodes.Ldloca_S, (byte)i); break;`
- `case int i when (i >= 4 & i <= 255): il.Emit(OpCodes.Stloc_S, (byte)i); break;`

Missing a char '&'?
Should it be correct as follows?
- `case int i when (i >= -128 && i < 127): il.Emit(OpCodes.Ldc_I4_S, (sbyte)i); break;`
- `case int i when (i >= 0 && i <= 255): il.Emit(OpCodes.Ldloca_S, (byte)i); break;`
- `case int i when (i >= 4 && i <= 255): il.Emit(OpCodes.Stloc_S, (byte)i); break;`

**Comment by mgravell** [comment]
It is "correct" either way. We don't care whether or not it gets short-circuited - there are no unwanted side-effects from running both halves. In reality it won't make any important difference in either case - the `&` version might *technically* pipeline better (fewer branches), but this isn't a performance critical path, so: that is moot.
