### ISSUE TITLE
How to Override  options using AddCodeFirstGrpc

### ISSUE THREAD

**Issue by twiga2013** [protobuf-net/protobuf-net.Grpc#25]
How do I go about overriding different properties for GRPC service i.e.

EnableDetailedErrors 
MaxReceiveMessageSize
MaxSendMessageSize

**Comment by mgravell** [comment]
Great question! You're right, we didn't expose this; adding a optional API for this, thanks

**Comment by mgravell** [comment]
[1.0.13](https://www.nuget.org/packages/protobuf-net.Grpc.AspNetCore/1.0.13)

**Comment by jjxtra** [comment]
Thanks so much for adding this, seems like some of your stuff should be standard libraries at this point!
