### ISSUE TITLE
Using this library with MessagePack serializer

### ISSUE THREAD

**Issue by gao-artur** [protobuf-net/protobuf-net.Grpc#250]
Is it possible to replace protobuf serializer with MessagePack when using this library?

**Comment by gao-artur** [comment]
Found it. Defined the `MarshallerFactory`:
```csharp
public class MessagePackMarshallerFactory : MarshallerFactory
{
    protected override bool CanSerialize(Type type)
    {
        return true;
    }

    protected override byte[] Serialize<T>(T value)
    {
        return MessagePackSerializer.Serialize(value);
    }

    protected override T Deserialize<T>(byte[] payload)
    {
        return MessagePackSerializer.Deserialize<T>(payload);
    }
}
```
Configured the server:
```csharp
services.AddSingleton(_ => BinderConfiguration.Create(
    new List<MarshallerFactory>
    {
        new MessagePackMarshallerFactory()
    }));
```
And the client:
```csharp
services.AddSingleton(_ => ClientFactory
    .Create(BinderConfiguration.Create(new List<MarshallerFactory>
    {
        new MessagePackMarshallerFactory()
    })));
```
Thanks for a great library!

**Comment by ChristianWeyer** [comment]
Great @gao-artur - would be nice to hear about your experience using MessagePack.
E.g., which advantages you will see compared to the default behavior.

Thanks.

**Comment by gao-artur** [comment]
Today we have an implementation of request/response over RabbitMq with MessagePack as a serializer. We are replacing it with grpc. Since protobuf has much more limitations compared to MessagePack we had to change many of our contracts (for example you can't use a property of type `object` with protobuf, but MessagePack is happy with it). So for us, the main advantage is easier migration 😀

**Comment by gao-artur** [comment]
More efficient version
```csharp
public class MessagePackMarshallerFactory : MarshallerFactory
{
    protected override bool CanSerialize(Type type)
    {
        return true;
    }

    protected override Marshaller<T> CreateMarshaller<T>()
    {
        return new Marshaller<T>(ContextualSerialize, ContextualDeserialize<T>);
    }

    private void ContextualSerialize<T>(T value, SerializationContext context)
    {
        var writer = context.GetBufferWriter();
        MessagePackSerializer.Serialize(writer, value);
        context.Complete();
    }

    private T ContextualDeserialize<T>(DeserializationContext context)
    {
        var ros = context.PayloadAsReadOnlySequence();
        return MessagePackSerializer.Deserialize<T>(ros);
    }
}
```

**Comment by mgravell** [comment]
There's probably capacity for a bolt-on aux library that adds this
capability. I wouldn't want to force the extra dependency by adding it to
the main library, but as an aux: no problem.

The only thing I'd opine on here is the CanSerialize - presumably
MessagePack is a little more restrictive than "can serialize anything" -
personally I'd recommend trying to validate that correctly. I don't know
enough about MessagePack to know the rules there.

But: I acknowledge that if you're only using it with suitable types: what
you have will work fine.

**Comment by gao-artur** [comment]
The `return true` here is just an example, in reality, we have a little bit more checks.
