### ISSUE TITLE
how to convert .proto file to c# contract-first code  with [ServiceContract] and [DataContract]

### ISSUE THREAD

**Issue by fengyeall111** [protobuf-net/protobuf-net.Grpc#255]
proto:
```
syntax = "proto3"; 

service Hello {
    rpc SayHello(HelloRequest) returns (HelloResponse) {}
   }

message HelloRequest {
    string name = 1;
}

message HelloResponse {
    string message = 1;
}
```
how to general contract-first code  with [ServiceContract] and [DataContract]:
```
[DataContract]
public record HelloRequest{
    [DataNumber(1)]
    public string name{get;set;}
}
...
[ServiceContract]
public interface  Hello {
    Task< HelloResponse> SayHello(HelloRequest req)
}
```

**Comment by mgravell** [comment]
https://protobuf-net.github.io/protobuf-net/contract_first.html

**Comment by fengyeall111** [comment]
> https://protobuf-net.github.io/protobuf-net/contract_first.html

thanks  for your reply. The  intention is convert .proto to wcf with attribute [servicecontract] and [datacontract]. The tool [protobuf-net.Protogen](https://www.nuget.org/packages/protobuf-net.Protogen/),  dose not satisfy demand because it can not generate “datacontract” attribute that fits wcf originally .It gennerates "protocontract"  and grpcservice method with two parameter，for wcf 
grpc method only need one   parameter。Is there some way to do this ? " protobuf-net.Protogen"  seem as if there is no corresponding function。

**Comment by mgravell** [comment]
Partially. The `services` attribute on `<AdditionalFiles>` can help influence this *for services*, i.e.

``` xml
<AdditionalFiles Include="my.proto" services="wcf"/>
```

generates:

``` c#
[global::System.ServiceModel.ServiceContract(Name = @"Hello")]
public partial interface IHello
{
    global::System.Threading.Tasks.ValueTask<HelloResponse> SayHelloAsync(HelloRequest value, global::ProtoBuf.Grpc.CallContext context = default);
}
```

(it would also use `[OperationContract]` if needed)

However, it does not currently generate `[DataContract]`/`[DataMember]` types, because *usually* that is going to be insufficient to correctly represent the model.

What is the thing that you're actually trying to achieve here? I may be able to help more if I can understand the full context.

**Comment by fengyeall111** [comment]
We have a lot of programs that use wcf  with  [DataContract]/[DataMember] types.These programs can use both http protocol and code-first pattern rpc procedure.  Now we need c#  programs communicate with go grograms by grpc. We want keep c# programs not changing code style and suport both two protocol . So We need to traslate .proto file to  c# file  with [DataContract]/[DataMember] types.That's all we need. Thank you very much.

**Comment by fengyeall111** [comment]
> Partially. The `services` attribute on `<AdditionalFiles>` can help influence this _for services_, i.e.
> 
> ```
> <AdditionalFiles Include="my.proto" services="wcf"/>
> ```
> 
> generates:
> 
> ```cs
> [global::System.ServiceModel.ServiceContract(Name = @"Hello")]
> public partial interface IHello
> {
>     global::System.Threading.Tasks.ValueTask<HelloResponse> SayHelloAsync(HelloRequest value, global::ProtoBuf.Grpc.CallContext context = default);
> }
> ```
> 
> (it would also use `[OperationContract]` if needed)
> 
> However, it does not currently generate `[DataContract]`/`[DataMember]` types, because _usually_ that is going to be insufficient to correctly represent the model.
> 
> What is the thing that you're actually trying to achieve here? I may be able to help more if I can understand the full context.

We have a lot of programs that use wcf with [DataContract]/[DataMember] types.These programs can use both http protocol and code-first pattern rpc procedure. Now we need c# programs communicate with go grograms by grpc. We want keep c# programs not changing code style and suport both two protocol . So We need to traslate .proto file to c# file with [DataContract]/[DataMember] types.That's all we need. Thank you very much.

**Comment by mgravell** [comment]
Any use of WCF-style attributes in this output is largely intended purely for reduced dependency graph reasons, and no guarantee is made that the generated types will be usable with WCF. If that is the intention: there would presumably be quite a bit of necessary discovery work to identify whether that is going to work, plus any remedial work required. Actually emitting the attributes: not very difficult, technically - I just don't think it will solve your actual need, so I'm hesitant to rush in with anything there. Can I confirm: your intentions here are to allow you to use these types with WCF?

**Comment by fengyeall111** [comment]
> 

You are right.The intention is to comminucating for Cross-platform，not change c# code style（code-first）.  I have tried some methods to commnicate go and csharp by grpc,but failed.For go ,using grpc,for c#,using code first. Even c# use dto with [protocontract] and [servicecontract] genrated by .proto file.

**Comment by mgravell** [comment]
As I already implied: we make no claims of suitability for this process to make WCF-compatible stubs. That would take quite a bit of testing and investigation of which scenarios will/won't work (the different tools have different feature sets and target scenarios), but ultimately: it just isn't a design goal of the tool, and isn't something I plan on investing my time in without a good reason. I would suggest using two models here: one designed for WCF, and one designed for gRPC. The gRPC model could be schema-first (.proto) or code-first - as you choose. Ditto WCF (via mex, wsdl, or whatever - if you want schema-first).

**Comment by fengyeall111** [comment]
Thanks.

> As I already implied: we make no claims of suitability for this process to make WCF-compatible stubs. That would take quite a bit of testing and investigation of which scenarios will/won't work (the different tools have different feature sets and target scenarios), but ultimately: it just isn't a design goal of the tool, and isn't something I plan on investing my time in without a good reason. I would suggest using two models here: one designed for WCF, and one designed for gRPC. The gRPC model could be schema-first (.proto) or code-first - as you choose. Ditto WCF (via mex, wsdl, or whatever - if you want schema-first).
