### ISSUE TITLE
contract-first rpc methods  must have parameter

### ISSUE THREAD

**Issue by fengyeall111** [protobuf-net/protobuf-net.Grpc#256]
In code-first pattern,service method may be like this:
```
Task <RoomMemberResponse> GetMemberList(RoomMemberRequest value);
```
It can have only one parameter
oppositely,contract-first method must have two  parameter,which may be like this:
```
Task <RoomMemberResponse> GetMemberList(RoomMemberRequest value,callContext ctx);
```  
I just know the sencod parameter is about rpc configuration.Is there some way to ignore the parameter like  code-first pattern service method

**Comment by mgravell** [comment]
The contract-first code should be emitting a `= default` on the end of that, so: from the perspective of most consumption code, it doesn't need to be supplied anyway. Does this help at all?

No, there is not currently an option to suppress the context parameter, but: the library itself works fine without it - we could *add* a configuration option if that would be useful.

**Comment by fengyeall111** [comment]
> The contract-first code should be emitting a `= default` on the end of that, so: from the perspective of most consumption code, it doesn't need to be supplied anyway. Does this help at all?
> 
> No, there is not currently an option to suppress the context parameter, but: the library itself works fine without it - we could _add_ a configuration option if that would be useful.

When using protoContract, the method must have  "context"   parameter
```
Task <RoomMemberResponse> GetMemberList(RoomMemberRequest value,callContext ctx);
```
Why it can not  be like service method with  [dataContract] attribute  without "context" parammeter

**Comment by mgravell** [comment]
> the method must have "context" parameter

There is no "must" here. Simply: that's what the tool currently generates. It works fine without, hence my statement that we could potentially add an option to not emit that, if useful.

> service method with [data contract]

service methods are usually annotated as operation contracts, not data contracts, no?

**Comment by fengyeall111** [comment]
Thanks.
The case: csharp code-frist grpc communicate with go grpc,for csharp,service methods can use  [datacontract]  or [protocontract] attribute，but [datacontract] attribute data model are not equivalent to proto defination. If using [protocontract],for grpc ,that's ok.for http, in some situation，we do not need  the method's second parameter.eg：using swagger，not show  “the context” parameter.
If  service method with  [protocontract] attribute  has Optional Parameters for the second parameter,that's great.Some situation we do not care the second parameter.

**Comment by mgravell** [comment]
We already emit the parameter as optional, I believe. Are we talking about Swashbuckle here? I wonder if an `ISchemaFilter` is what is needed here; for example, https://stackoverflow.com/a/48454933/23354 or https://stackoverflow.com/a/56941793/23354 - presumably all parameters of `CallContext` can be ignored (although I don't claim to be hugely familiar with Swashbuckle - this is just random searching).

As I say, tweaking the generator to optionally omit the context parameter is easy enough, but that then is contrary to:

> If service method with [protocontract] attribute has Optional Parameters for the second parameter,that's great

since: it won't be available at all if we omit it entirely.

**Comment by fengyeall111** [comment]
> We already emit the parameter as optional, I believe. Are we talking about Swashbuckle here? I wonder if an `ISchemaFilter` is what is needed here; for example, https://stackoverflow.com/a/48454933/23354 or https://stackoverflow.com/a/56941793/23354 - presumably all parameters of `CallContext` can be ignored (although I don't claim to be hugely familiar with Swashbuckle - this is just random searching).
> 
> As I say, tweaking the generator to optionally omit the context parameter is easy enough, but that then is contrary to:
> 
> > If service method with [protocontract] attribute has Optional Parameters for the second parameter,that's great
> 
> since: it won't be available at all if we omit it entirely.
Yeah. Grpc is the wrapper of  http2  that may be need context ,But http protocol don't need this.Thank you for your reply，I‘ll close this.
