### ISSUE TITLE
Is it needed to create intermediate classes when I want to use DDD?

### ISSUE THREAD

**Issue by ComptonAlvaro** [protobuf-net/protobuf-net.Grpc#258]
I am try to do some tries with gRPC and DDD.

In the server side, I have the server gRPC, that uses a repository to get data. The repository returns domain classes.

But to can send classes with gRPC code first, I need to decorate the classes with [DataContract] and the properties of the classes with [DataMember(Order = 1)].

Well, how the classes of the domain shouldn't be decorated, then the only way that I guess it is possible to send to the client the information  is creating intermediate classes, gRPC classes, to convert domain classes to classes that can be serialized and send to the client.

So here is my question, if this is the unique solution, I have to convert domain classes to classes that can be serialized, then, which is the advantage to create this gRPC classes instead of use directly probuf? I could convert domain classes to protobuf and I would have the same work, convert domain classes to something that can be serializable and send to the client. So I don't see the advantage of the gRPC code first.

Thanks.

**Comment by mgravell** [comment]
This is a little hard to talk about without seeing some kind of example code, so we don't talk past each-other, but I'll try!

Ultimately, you need some types at each end, and those types need to be configured for protobuf. One way of doing that is with attributes, although manual configuration is possible (I'm not sure I'd hugely recommend it, though). For some people, having the same model at both ends works fine. Other people might want different models at client and server. Both options are fine, as long as they are configured to be compatible (meaning: the same numbers have the same meaning).

If that doesn't work for you, and you'd rather use .proto and code-gen: that too is an option - either for regular protobuf/gRPC or using protobuf-net.BuildTools. Ultimately, this is just one set of tools: if it fits your needs, feel free to use it! I also acknowledge it isn't the right tool for every scenario.

So: turning the question around: how would you *like* this to work? It might already be possible.

**Comment by ComptonAlvaro** [comment]
Well, I was thinking in general, but I wanted to mean this.

If I use protbuf directly, I have to convert the domain classes to protobuf messages to can be sent.

If I use code first, I have to convert domain classes to gRPC clases (classes used in the contract) and then I guess the code first will convert this classes to protobuf messages to can be sent. So I have one more conversion, that I guess it is less efficient. But perhaps i am wrong and code first doesn't conver the gRPC classes to protobuf messages and can send this classes to client directly, so I would have only one conversion.

**Comment by mgravell** [comment]
Code-first does not use the Google protobuf internally and/or generate an entire additional hidden type-model; there is no additional layer of translation. Additionally, in many (not all) cases, it is possible to configure your existing model, such that there are zero additional translations.

**Comment by ComptonAlvaro** [comment]
Then I was wrong, thinking that there were an aditional translation. Then I can see the benefit to use it.

When you talk about cofigure the existing model, I guess you mean decorate the classes of the model with [DataContract] and [DataMember(Order = 1)]. Is it correct? If this is correct, then I guess it is not a good solution in my case becase I should to add dependencies to my domain, and it is better to avoid.

**Comment by mgravell** [comment]
That is certainly the most common way of configuring things, due to simplicity. Not the only way. Is your aim to avoid any changes to the model whatsoever?

**Comment by ComptonAlvaro** [comment]
Well, I would prefer to avoid changes in the model, because it is a better aproach to DDD.

Also you comment there are another ways to do it. Could you tell about the others way?


Thank you so much.

**Comment by mgravell** [comment]
It is possible to configure RuntimrTypeModel manually at runtime, but: it
isn't "nice". With the upcoming AOT work, I wonder if we could potentially
move to some kind of external JSON file configuration. I'd need to think
about it.

**Comment by ComptonAlvaro** [comment]
Really it would be nice if we could map in some way or can config the serialization of the domain models in a external way, to can keep more isolated the domain if it is followed DDD, perhaps in some way like Entity Core can configure the mapping the classes with fluent API.

I would like to ask too about the performace. the classes are not converted to protobuf messages, so I guess it uses another kind of serialization different than protobuf, which one offers better performance, protobuf of protobuf-net?

**Comment by mgravell** [comment]
protobuf-net provides an independent implementation of an encoder/decoder
for the documented protobuf binary format. Performance is contextual; right
now the best I can say is that the two implementations are comparable, and
that scenarios exist where each is better. I am actively working on the v4
branch which, I believe, will significantly improve the current
performance, making it almost always faster (based on the research so far),
however: I'd always say "do your own tests". Usually, however, the answer
is "plenty fast enough" for either implementation.

**Comment by ComptonAlvaro** [comment]
I know that always it is good to do own tests to see in a particular project which one is better, but to have a reference it is good.

It is nice to hear that in the v4 the performace will be much better.


Thanks so much for your attention, it was much clear all now. By the moment is all, if I have some another question i will open another issue.


Thanks so much for all the work.
