### ISSUE TITLE
Specific method is not support when client try to call method.

### ISSUE THREAD

**Issue by ComptonAlvaro** [protobuf-net/protobuf-net.Grpc#259]
I get en error in the client when I try to call a method:

This is my contract in a shared library:

```
    [DataContract]
    public class GetFacturasReply
    {
        [DataMember(Order = 1)]
        public int Numero { get; set; }
    }
```

This is the implementation of the service:

```
public class FacturasService : IFacturasService
{
    public async Task<GetFacturasReply> GetFacturasAsync(CallContext context = default)
    {
        return new GetFacturasReply
        {
            Numero = 1,
        };
    }
}
```

This is the call in the client:

```
try
{
    using var channel = GrpcChannel.ForAddress("http://localhost:5223");
    var client = channel.CreateGrpcService<IFacturasService>();

    var reply = await client.GetFacturasAsync();    //here I get the exception that methos is not supported

    -----
}
catch(RpcException ex)
{
    throw;
}
catch(Exception ex)
{
    throw;
}
```

But I don't understand why the method is not supported. The error it seems to be in the client, before really doing the call to the server, because in the log of the server I don't get any call neither another error.

How could be the problem?

Thanks so much.

**Comment by mgravell** [comment]
Is the interface marked as a service? For example: does it have [Service]
or [ServiceContract] ?

**Comment by ComptonAlvaro** [comment]
Yes, that's was the error, I didn't see i don't mark the interface as service.

But I still have a related error: ""Status(StatusCode=\"Unimplemented\", Detail=\"Bad gRPC response. HTTP status code: 404\")"".

My Asp Core code is this:

```
var builder = WebApplication.CreateBuilder(args);


builder.Services.AddGrpc();
builder.Services.AddCodeFirstGrpc();

var app = builder.Build();



app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
```

**Comment by mgravell** [comment]
Are you calling MapGrpcService<Your type> ? See section 2 here:
https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted.html

**Comment by ComptonAlvaro** [comment]
Yes, thanks, this solve the problem.


Thanks you so much.
