### ISSUE TITLE
Is it possible to get the ServiceContract interface in the interceptor?

### ISSUE THREAD

**Issue by shustrenko** [protobuf-net/protobuf-net.Grpc#265]
Hi. I want to add the custom attribute to the methods of ServiceContract, like

```
    [ServiceContract(Name = "MyService")]
    public interface IMyService
    {
        [RequiresCaching]
        Task<IEnumerable<MyRecord>> GetRecords();
    }
```
And then use it in the client interceptor, like

```
 internal class GrpcClientCacheInterceptor : Interceptor
    {
        public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(TRequest request, ClientInterceptorContext<TRequest, TResponse> context,
        AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
        {
            if (MethodRequiresCaching(context))
            {
                return GetCachedRespose(request, context, continuation);
            }
            else
            {
                return base.AsyncUnaryCall(request, context, continuation);
            }
        }
    }
```

I found that ClientInterceptorContext has the method name and types of method arguments. But i cant find is it possible to get the ServiceContract interface from this context?

I see that In the server Interceptor its possible to get the target type from the UnaryServerMethod like:

```
        public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
            TRequest request,
            ServerCallContext context,
            UnaryServerMethod<TRequest, TResponse> continuation) where TResponse : class
        {
            var targetType = continuation.Target.GetType();
            return await continuation(request, context);
        }
```

Actualy i understand that such question is related mostly to the general grpc, but i decide to write it here as code first allows to write custom ServiceContract.

**Comment by mgravell** [comment]
You should be able to access context.Method.ServiceName, which isn't quite
the same but is the closest immediately available. Anything more: would
require changes to Grpc.Core.Api

**Comment by shustrenko** [comment]
> You should be able to access context.Method.ServiceName, which isn't quite the same but is the closest immediately available.

Yea, this property contains ServiceContract name from the  [ServiceContract(Name = "MyService")]. But as i have several interfaces with the same ServiceContract name and same method name, so i can't rely on this value.

>Anything more: wouldrequire changes to Grpc.Core.Api
Ok, got it. Thanks

**Comment by mholec** [comment]
You can access HttpContext in your interceptor and HttpContext provides all endpoint metadata.

`context.GetHttpContext().GetEndpoint()?.Metadata.GetMetadata<RequiresCaching>()`

**Comment by mgravell** [comment]
@mholec the service contract is not endpoint metadata

**Comment by DominikAmon** [comment]
Any solutions since the post was closed? We have the same requirement to get the MethodInfo inside the interceptor

**Comment by mgravell** [comment]
The interceptor API is part of gRPC.Core (outside of my control), and the ambient call environment (for things like async-local) is part of the server (outside of my control). My suggestion here would be to build a map of the expected service endpoints, and switch on that via `.Method`. what we *might* be able to do here is have protobuf-net.Grpc add something like a `MethodInfo GetMethodInfo(ctx.Method)` API that automates this step - would that be useful?

**Comment by DominikAmon** [comment]
You mean like a shorthand implementation for a reflection iteration for a suitable method in the interface by the given method name string?
My workaround is a startup method that does the scanning by reflection once when booting up and then, when checking the method string, I lookup the method list that was created while bootstrapping.
