### ISSUE TITLE
OperationCanceledException: Read was canceled on underlying PipeReader

### ISSUE THREAD

**Issue by bilaljaved786** [protobuf-net/protobuf-net.Grpc#266]
Am getting this type of error while moving to NET 6.0

Grpc.Core.RpcException : Status(StatusCode="Unknown", Detail="Exception was thrown by handler. OperationCanceledException: Read was canceled on underlying PipeReader.")

  Source=Google.Protobuf
  StackTrace:
   at Google.Protobuf.WritingPrimitivesMessages.WriteRawMessage(WriteContext& ctx, IMessage message)
   at Google.Protobuf.WritingPrimitivesMessages.WriteMessage(WriteContext& ctx, IMessage value)
   at Google.Protobuf.WriteContext.WriteMessage(IMessage value)
   at Google.Protobuf.IBufferMessage.InternalWriteTo(WriteContext& output) in \net6\service\Department.cs:line 1275

package: Google.Protobuf v (3.21.12) NET 6.0

I tried different solution while downgrading the version of the package but still facing the same issue

**Comment by mgravell** [comment]
Please see my comments/questions on stackoverflow - same questions apply here. The first one being "are you actually using protobuf-net?"

**Comment by mgravell** [comment]
additional observation (the stacktrace isn't on the SO question): the *stack-trace* is about *writing*, but the *rpc* data is from `Read`. This is very interesting, because I don't think those two things intersect at all! Are they both taken from the same event, or are the two messages from two different failures, one read one write?

**Comment by mgravell** [comment]
Based on the SO comments, I don't *think* this is a protobuf-net/protobuf-net.Grpc question; that doesn't mean I'm not interested - I wear many hats, and I'm involved in the more general GRPC pieces too; it is simply a topic of where we should most usefully locate the conversation :)

**Comment by mgravell** [comment]
Based on SO conversation, I'm pretty confident that this is nothing to do with protobuf-net.Grpc; I propose we continue discussing this on SO for now, and we can re-route later if needed

**Comment by bilaljaved786** [comment]
ok
