### ISSUE TITLE
Generic ServiceContracts

### ISSUE THREAD

**Issue by GoNextGroup** [protobuf-net/protobuf-net.Grpc#267]
Hello.

I have one stupid question. but...

Let's have contract description like this:
```
[ServiceContract]
public interface IMyAmazingService<TRequest> 
{
       Task SearchAsync(TRequest request);
}
```

I want to have different realizations for 2 services (for example):

```
public class MyAmazingEmailService1 : IMyAmazingService<EmailRequest>
{
       public async Task SearchAsync(EmailRequest request) { ... }
}

public class MyAmazingEmailService2 : IMyAmazingService<SMSRequest>
{
       public async Task SearchAsync(SMSRequest request) { ... }
}
```

But I don't know how to correclty register these services and discover them on server/client side. And I haven't found any appropriate information about this in docs.

Could you explain me deeper this aspect? Is it possible? If "yes" what's correct way to do this in my code?

Thank you.

P.S. The reason of this question is inspired by attemption of methods' unification. For example, in my cases most "contracts" can be described as "contracts" which realise `IChange<TRequest>, IMake<TRequest>, IDelete<TRequest>`.

**Comment by mgravell** [comment]
I would mark the generic interfaces as `[SubService]`, and create an `IFooService : {all relevant specific generic sub-services}` and mark *that* as `[Service(name)]`. This flattens the API creating a single service with the relevant concrete generic types.

**Comment by mgravell** [comment]
So:

```
[Service]
interface IEmailService : IMyAmazingService<EmailRequest> {}
[Service]
interface ISMSService : IMyAmazingService<SMSRequest>, IMake<SMSRequest>
{}
```

**Comment by GoNextGroup** [comment]
But there is no way not to create redundant interfaces? Because, for example, IMake<SMSRequest> completely differs from IMake<EmailRequest>.

**Comment by mgravell** [comment]
It's not redundant; it is describing the features and routing of a service.

**Comment by GoNextGroup** [comment]
Thank you, Marc!
