### ISSUE TITLE
Is Dependency Injection supported in protobuf-net.Grpc.Native (.NET Framework)?

### ISSUE THREAD

**Issue by chrbkr** [protobuf-net/protobuf-net.Grpc#271]
According to the Getting Started docs, for .NET Framework one should use `server.Services.AddCodeFirst(new MyServer())` for registering a service. But how would I combine this with DI?

**Comment by mgravell** [comment]
The Google server implementation requires you to provide the actual object - so no DI is used on a contextual basis. If you have a DI that can provide the actual server instance (albeit only the one time), then I guess you could use it then. But the server instance model is very different between Google and Microsoft server implementations.

**Comment by chrbkr** [comment]
So the services have to be singletons (even though not necessarily declared as such)? Currently I'm using AutoFac, so I guess I'll just resolve the instances once at the beginning. Thank you!

**Comment by mgravell** [comment]
For the Google implementation: yes, effectively. For the Microsoft server: no

**Comment by mgravell** [comment]
(closing as this is really a question for Grpc.Core which is now in maintenance mode, with the intent being already implemented in the Microsoft server implementation)
