### ISSUE TITLE
"failed to connect to all addresses" using protobuf-net.Grpc.Native net48 client

### ISSUE THREAD

**Issue by menaheme** [protobuf-net/protobuf-net.Grpc#274]
I am trying to connect to a grpc service exposed using code first  (protobuf-netGrpc.AspNetCore), in a net6.0 app.
Using a net6.0 and protobuf-net.Grpc.AspNetCore on the client side works just fine.
But when trying to use protobuf-net.Grpc.Native  from a net4.8 app i get:

> Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1675865603.994000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":3218,"referenced_errors":[
> 
> {"created":"@1675865603.994000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\lib\transport\error_utils.cc","file_line":165,"grpc_status":14}
> ]}")'

the client channel looks like: 
```
Channel channel = new Channel("localhost", 7201,ChannelCredentials.Insecure);
var client = channel.CreateGrpcService<TContract>();
client.SampleOperation(...);
```

**Comment by mgravell** [comment]
Well, without being able to repro it is going to be hard to say; does the server have TLS? does this help? https://stackoverflow.com/questions/68217975/grpc-method-call-error-failed-to-pick-subchannel (in particular, setting the trace flags and seeing what appears in the console). Have you tried moving only one piece at a time? i.e. you say you have a working net6 client and aspnetcore server; can the native client talk to the aspnetcore server? can the net6 client talk to the net48 server? (the clients and servers are meant to be entirely interoperable - you can use any combination). This would at least help clarify which step is making things break.

**Comment by menaheme** [comment]
Yes ! it helped thanks. 
I am not using TLS , trying to make it simple first. 
using the trace i can see the internal error is HTTP/1.1 505 http version not supported


> 0208 18:33:59.074810 0 ..\..\..\src\core\lib\iomgr\tcp_windows.cc:212: READ 000001F673ED6FF0 (peer=ipv4:127.0.0.1:7201): 48 54 54 50 2f 31 2e 31 20 35 30 35 20 48 54 54 50 20 56 65 72 73 69 6f 6e 20 4e 6f 74 20 53 75 70 70 6f 72 74 65 64 0d 0a 43 6f 6e 74 65 6e
> 74 2d 4c 65 6e 67 74 68 3a 20 30 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 44 61 74 65 3a 20 57 65 64 2c 20 30 38 20 46 65 62 20 32 30 32 33 20 31 36 3a 33 33 3a 35 38 20 47 4d 54 0d 0a 53 65 72 76 65 72 3a 20 4b 65 73 74 72 65 6c 0d 0a 0d
> 0a '**HTTP/1.1 505 HTTP Version Not Supported**..Content-Length: 0..Connection: close..Date: Wed, 08 Feb 2023 16:33:58 GMT..Server: Kestrel....'
> I0208 18:33:59.074810 0 ..\..\..\src\core\ext\transport\chttp2\transport\chttp2_transport.cc:2969: transport 000001F6743F9890 set connectivity_state=4
> I0208 18:33:59.074810 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:159: ConnectivityStateTracker client_transport[000001F6743F9B78]: READY -> SHUTDOWN (close_transport, OK)
> I0208 18:33:59.074810 0 ..\..\..\src\core\lib\iomgr\timer_generic.cc:447: TIMER 000001F6742DE018: CANCEL pending=true
> I0208 18:33:59.075814 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:948: subchannel 000001F673F45DB0
> 
> {address=ipv4:127.0.0.1:7201, args=grpc.client_channel_factory=0x1f673f14bf0, grpc.default_authority=127.0.0.1:7201, grpc.internal.channel_credent ials=0x1f673ec1a10, grpc.internal.security_connector=0x1f673f34b40, grpc.internal.subchannel_pool=0x1f673f0cce0, grpc.primary_user_agent=grpc-csharp/2.46.6 (.NET Framework 4.8.4380.0; CLR 4.0.30319.42000; net45; x64), grpc.resource_quota=0x1f673f0e300, grpc.serv er_uri=dns:///127.0.0.1:7201}
> : connect failed: {"created":"@1675874039.075000000","description":"Failed parsing HTTP/2","file":"..\..\..\src\core\ext\transport\chttp2\transport\chttp2_transport.cc","file_line":2591,"referenced_errors":[
> 
> {"created":"@1675874039.07 5000000","description":"Expected SETTINGS frame as the first frame, got frame type 80","file":"..\..\..\src\core\ext\transport\chttp2\transport\parsing.cc","file_line":257}
> ,
> 
> {"created":"@1675874039.075000000","description":"Trying to connect an http1.x server","f ile":"..\..\..\src\core\ext\transport\chttp2\transport\chttp2_transport.cc","file_line":2544,"grpc_status":2,"http_status":505}
> ]}
> I0208 18:33:59.075814 0 ..\..\..\src\core\ext\filters\client_channel\client_channel.cc:576: chand=000001F673EF99C8: connectivity change for subchannel wrapper 000001F673F376B0 subchannel 000001F673F45DB0; hopping into work_serializer
> I0208 18:33:59.075814 0 ..\..\..\src\core\ext\filters\client_channel\client_channel.cc:611: chand=000001F673EF99C8: processing connectivity change in work serializer for subchannel wrapper 000001F673F376B0 subchannel 000001F673F45DB0 watcher=000001F673F223E0
> I0208 18:33:59.075814 0 T:\altsrc\github\grpc\workspace_csharp_ext_windows_x64\src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:246: [pick_first 000001F673EB7E70] subchannel list 000001F673E74580 index 0 of 1 (subchannel 000001F673F376B0): connect
> ivity changed: state=TRANSIENT_FAILURE, shutting_down=0, pending_watcher=000001F673F223E0
> I0208 18:33:59.075814 0 T:\altsrc\github\grpc\workspace_csharp_ext_windows_x64\src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:333: [pick_first 000001F673EB7E70] subchannel list 000001F673E74580 index 0 of 1 (subchannel 000001F673F376B0): canceli
> ng connectivity watch (connection attempt failed)
> I0208 18:33:59.075814 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc:396: Pick First 000001F673EB7E70 subchannel list 000001F673E74580 failed to connect to all subchannels
> I0208 18:33:59.076812 0 ..\..\..\src\core\ext\filters\client_channel\lb_policy\child_policy_handler.cc:87: [child_policy_handler 000001F67436E650] started name re-resolving
> I0208 18:33:59.076812 0 ..\..\..\src\core\ext\filters\client_channel\client_channel.cc:955: chand=000001F673EF99C8: started name re-resolving
> I0208 18:33:59.076812 0 ..\..\..\src\core\ext\filters\client_channel\client_channel.cc:940: chand=000001F673EF99C8: update: state=TRANSIENT_FAILURE status=(UNAVAILABLE: failed to connect to all addresses) picker=000001F6743EC7D0
> I0208 18:33:59.076812 0 T:\altsrc\github\grpc\workspace_csharp_ext_windows_x64\src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:313: [pick_first 000001F673EB7E70] subchannel list 000001F673E74580 index 0 of 1 (subchannel 000001F673F376B0): startin
> g watch (from TRANSIENT_FAILURE)
> I0208 18:33:59.076812 0 ..\..\..\src\core\ext\filters\client_channel\subchannel.cc:891: subchannel 000001F673F45DB0
> 
> {address=ipv4:127.0.0.1:7201, args=grpc.client_channel_factory=0x1f673f14bf0, grpc.default_authority=127.0.0.1:7201, grpc.internal.channel_credent ials=0x1f673ec1a10, grpc.internal.security_connector=0x1f673f34b40, grpc.internal.subchannel_pool=0x1f673f0cce0, grpc.primary_user_agent=grpc-csharp/2.46.6 (.NET Framework 4.8.4380.0; CLR 4.0.30319.42000; net45; x64), grpc.resource_quota=0x1f673f0e300, grpc.serv er_uri=dns:///127.0.0.1:7201}
> : Retry in 1501 milliseconds
> I0208 18:33:59.076812 0 ..\..\..\src\core\lib\iomgr\timer_generic.cc:344: TIMER 000001F673F460E0: SET 4628 now 3127 call 000001F673F46118[00007FFC452260BE]
> I0208 18:33:59.076812 0 ..\..\..\src\core\lib\iomgr\timer_generic.cc:382: .. add to shard 7 with queue_deadline_cap=3524 => is_first_timer=false

**Comment by mgravell** [comment]
When you run gRPC on Kestrel without TLS, be sure to explicitly specify the endpoint should be http/2, not http1or2. You in can do this in code or the configuration file. Without TLS, http/2 resolution is a bit bumpy on a mixed endpoint.

**Comment by menaheme** [comment]
Indeed ! when specifying HTTP/2 only the call goes through as advertised :)
Thank you , you are not only a world class professional, but also very kind.

**Comment by menaheme** [comment]
Googled around and found this information right in the docs (smack forehead)

https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0

In the part aboud MacOS TLS support

**Comment by JamesNK** [comment]
It's documented here: https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#protocol-negotiation

**Comment by menaheme** [comment]
> When you run gRPC on Kestrel without TLS, be sure to explicitly specify the endpoint should be http/2, not http1or2. You in can do this in code or the configuration file. Without TLS, http/2 resolution is a bit bumpy on a mixed endpoint.

I tried to use ```ChannelCredentials.SecureSsl``` instead of ```ChannelCredentials.Insecure``` 
(using the 'dotnet dev-certs https --trust' self signed localhost certificate) 
```
Channel channel = new Channel("localhost", 7201,ChannelCredentials.SslSecure);
var client = channel.CreateGrpcService<TContract>();
client.SampleOperation(...);
```

but the trace shows:

> I0209 16:22:31.876532 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:226: LOOP - TLS client read_server_certifi - !!!!!!
> I0209 16:22:31.876532 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:226: LOOP - TLS client read_certificate_st - !!!!!!
> I0209 16:22:31.876532 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:226: LOOP - TLS client verify_server_certi - !!!!!!
> E0209 16:22:31.876532 0 ..\..\..\src\core\tsi\ssl_transport_security.cc:1495: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:**CERTIFICATE_VERIFY_FAILED.**
> D0209 16:22:31.876532 0 ..\..\..\src\core\lib\security\transport\security_handshaker.cc:181: Security handshake failed:
> 
> {"created":"@1675952551.877000000","description":"Handshake failed","file":"..\..\..\src\core\lib\security\transport\security_handshaker.cc"," file_line":377,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
> 
> 

is my scenario at all supported /meat to work  ?
i can get a proper certificate, but i think localhost is quite common for development

**Comment by mgravell** [comment]
@menaheme at that point you're asking about Grpc.Core's support for self-signed certs; that's not part of protobuf-net.Grpc so I can only offer general guidance, but: see https://stackoverflow.com/a/58941359/23354 for a general overview, https://stackoverflow.com/questions/59671753/disable-ssl-certificate-validation-on-grpc-core-channel for a c#-specific (unanswered) post, and https://github.com/grpc/grpc/issues/20430 for a github issue linked to a C++ change related to this, but: I have no idea whether that change is surfaced anywhere on the .NET client

again, this library just says "you (Google/Microsoft) give me a gRPC transport: I'll do some things with it"; how that transport works is external to anything I can control here

**Comment by menaheme** [comment]
I see, thank you for the references.
if i find a way forward , i will try and post back here.

**Comment by mgravell** [comment]
@menaheme for clarification; I *am* now tangentially engaged in the main Grpc bits, but the reality is:

- Grpc.Core (the Google transport) is *effectively* "done" and is unlikely to get any significant updates or new features
- what you want already works in the Microsoft transport, so: nothing needs to be done there

**Comment by menaheme** [comment]
not sure i understood the last comment, 
is there another path to get a net4.8 client to call a net6.0 grpc server simply and with TLS ?

**Comment by menaheme** [comment]
Ok got it working - as you say this is Grpc.Core api issue.
is used [this](https://stackoverflow.com/a/60480334/488699 ) to export the self singed root CA X509Certiifcate to PEM format, and thats it basically.

raw code just to make the point:

```
X509Store store = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
var cert = store.Certificates.Find(X509FindType.FindBySubjectName, "localhost", true);
store.Close();
var sb = new StringBuilder();
sb.AppendLine("----BEGIN CERTIFICATE----");
sb.AppendLine(Convert.ToBase64String(cert.Export(X509ContentType.Cert), ase64FormattingOptions.InsertLineBreaks));
sb.AppendLine("----END CERTIFICATE----");
ChannelCredentials credentials = new SslCredentials(sb.ToString());
Channel channel = new Channel($"localhost", 7201, credentials);
```

this is just for making the life of a .net 4.8 developer easier, since the dot-net team provides self singed certificates
for localhost , and places them in the user's trusted root store.

if SslCredentials took X509Certificate2, that would of course save the export hack.

Thanks again for all your help and guidance

**Comment by mgravell** [comment]
FYI, in net8 Kestrel has been tweaked to help avoid the non-TLS thing being a pain point: https://github.com/dotnet/aspnetcore/pull/45352
