### ISSUE TITLE
Unable to Serialize Nested Positional Records

### ISSUE THREAD

**Issue by tcrory** [protobuf-net/protobuf-net.Grpc#276]
I have been testing the use of positional records without attributes through protobuf-net v3 and I discovered something unusual. If I have a positional record that includes other positional records within it, I can leave the attributes off of the top positional record however all of the types used within must have the attributes or type serialization will fail.

For example the following code will work fine:

```csharp
public record Foo(
    Bar Bar,
    Baz Baz);

[ProtoContract(SkipConstructor = true)]
public record Bar(
    [property: ProtoMember(1)]
    int X,
    [property: ProtoMember(2)]
    int Y);

[ProtoContract(SkipConstructor = true)]
public record Baz(
    [property: ProtoMember(1)]
    int Z);
```

However if I were to remove the attributes from Baz:

```csharp
public record Baz(
    int Z);
```

I would receive the following warnings in the log file:

```
warn: ProtoBuf.Grpc.Server.ServicesExtensions.CodeFirstServiceMethodProvider[0]
      Type cannot be serialized; ignoring: Test.Foo
warn: ProtoBuf.Grpc.Server.ServicesExtensions.CodeFirstServiceMethodProvider[0]
      Signature not recognized for Test.ITestService.SendFooAsync; method will not be bound
```

**Comment by mgravell** [comment]
Can you check to see that you're using protobuf-net v3? for complicated reasons the default is protobuf-net v2, but v3 can be swapped in

**Comment by tcrory** [comment]
I think I figured out what the issue was, and it's not quite what I expected. In my project, the "Baz" actually doesn't have any positional elements yet because it hasn't been designed, so it's currently defined as:
`public record Baz();  // TODO: Add elements later.`

Unfortunately, that's the one that I tested first by removing the `ProtoContract` attribute. When I remove the attribute from the other nested element (the "Bar" in the above example) and leave the attribute on the empty positional record, everything works fine.

There is still something odd going on with an empty positional record, but I imagine that, outside of the very early design phases on a big project, the odds of people needing to use an empty positional record as a placeholder are a bit unlikely.

**Comment by tcrory** [comment]
As an additional test, I found that a top-level empty record exhibits the same behavior confirming that nesting the records has nothing to do with it. Sorry about the mixup.

**Comment by mgravell** [comment]
if we look at [what the compiler does with that](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+tJQCYAIBiEEAFAJQDeAvkA), there isn't a lot that *explicitly* identifies this as a `record`, other than `[CompilerGenerated]` and the overall flavor. I guess we could say "if it doesn't have any fields at all: treat it like `Empty`". but... in reality it seems like an unlikely scenario to be worth lots of attention - thoughts?

**Comment by tcrory** [comment]
I think there is an argument to be made for trying to support it so that people could utilize placeholders in APIs. Treating it similar to `Empty` would be a fine resolution, however I'd be hesitant to treat it as if it actually were `Empty` because then the APIs wouldn't quite line up. This would only affect situations where someone was using the proto generator to create a proto file to support another language, but I think that debugging an issue where `Foo` in the interface becomes `Empty` in a proto file would generally be more difficult to diagnose and deal with.

If it's possible to make it into a custom Proto message that doesn't have any elements, that would be nice. If it's not or if it would be a lot of work, I don't think it's the worst outcome to say something like "If you are trying to use an empty positional record as a placeholder, you must add the `[ProtoContract]` attribute in order to tell the compiler that it is a real object that you want serialized."

That's what I intend to tell my team as we set up our interfaces, and I would argue that it's a perfectly valid outcome so long as it's documented.

**Comment by mgravell** [comment]
Well, do you have protobuf-net.BuildTools installed? It might already have warned you about something similar (although it might not handle records specifically). Re empty: I meant purely in terms of payload, not .proto

**Comment by mgravell** [comment]
Amusingly, making it work might be as simple as removing a check like `args.Length > 0` :) I'll take a look

**Comment by mgravell** [comment]
Specifically here: https://github.com/protobuf-net/protobuf-net/blob/24ad423608276a31e377beb7dd598a47c33fb8e4/src/protobuf-net/Meta/MetaType.cs#L982 (the second test on the line) - but I'll need to think about tests and edge cases

**Comment by tcrory** [comment]
That would be great if something that simple fixed it without any additional repercussions.

As for the BuildTools, is there a way to install it to Visual Studio rather than adding it to a project file? I'm up for trying it either way, just trying to figure out the different options available.

**Comment by mgravell** [comment]
So, yeah; bad things; lots of side-effects here - too many things get recognized as "empty" tuples. Given the option of just adding `[DataContract]` or similar before the zero record, I propose "just do that":

```c#
[System.Runtime.Serialization.DataContract] public record MyEmptyType();
```

**Comment by tcrory** [comment]
That sounds like a fair resolution to me. Thank you for taking the time to investigate it!
