### ISSUE TITLE
covariant IResponse<out T> data contract and polymorphism

### ISSUE THREAD

**Issue by RemcoBlok** [protobuf-net/protobuf-net.Grpc#277]
Hi

I previously managed to get polymorphism working with the following interface
```
    [Service]
    public interface ISalesManager
    {
        [Operation]
        Task<FindResponseBase> FindItemAsync(FindCriteriaBase criteria);
    }
```
See https://github.com/RemcoBlok/dapr-samples/tree/master/service-invocation-grpc-code-first-polymorphism

I would now like to wrap each response in a generic `Response<T>` class
```
    [ProtoContract]
    public class Response<T> : IResponse<T> where T : notnull
    {
        [ProtoMember(1)]
        public T? Value { get; set; }
        
        [ProtoMember(2)]
        public ErrorInfo? Error { get; set; }
    }
```
I want to make use of covariance so I also introduced a covariant interface
```
    [ProtoContract]
    public interface IResponse<out T> where T : notnull
    {
        [ProtoMember(1)]
        T? Value { get; }

        [ProtoMember(2)]
        ErrorInfo? Error { get; }
    }
```
which is what I end up using in my new ISalesManager
```
    [Service]
    public interface ISalesManager
    {
        [Operation]
        Task<IResponse<FindResponseBase>> FindItemAsync(FindCriteriaBase criteria);
    }
```
Covariance allows for easy casting of a `Response<DerivedFindResponse>` to `IResponse<DerivedFindResponse>` and ultimately to `IResponse<FindResponseBase>`.

On the server side the request is successfully received and a response returned from the operation method implementation, however the client receives a Grpc.Core.RpcException with StatusCode Unknown and Detail Exception was thrown by handler at ```ProtoBuf.Grpc.Internal.Reshape.<UnaryTaskAsyncImpl>d__16`2.MoveNext()```.

You can see the work in progress in this branch
https://github.com/RemcoBlok/dapr-samples/tree/covariant-iresponse/service-invocation-grpc-code-first-polymorphism

Could you advise please if this scenario is currently supported and how I can make this work? Many thanks

**Comment by RemcoBlok** [comment]
I managed to get this working by adding '[ProtoInclude(11, typeof(Response<DerivedFindResponse>))]' to the IResponse interface

**Comment by mgravell** [comment]
👍
