### ISSUE TITLE
protobuf-net.Grpc System.NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by shivkumarghatbale** [protobuf-net/protobuf-net.Grpc#283]
Getting following error =>

Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at ProtoBuf.Grpc.Internal.Proxies.ClientBase.IEVEventCppSharpService_Proxy_0.IEVEventCppSharpService.setFocusForManaged(setFocusForManagedRequest , CallContext )

Grpc client code:

var client = CppSharpSingleton.Instance.GetGrpcChannel().CreateGrpcService<IEVEventCppSharpService>();
        var ret = client.setFocusForManaged(new setFocusForManagedRequest {vmName =vmName, productType =productType, bOverWrite =bOverWrite,m_EvEventExtern =this.m_EvEventExtern,isDisposed =this.isDisposed}).GetAwaiter().GetResult();
                

Contract:

[ServiceContract]   
public interface IEVEventCppSharpService
{
    [OperationContract]
    public ValueTask<setFocusForManagedResponse> setFocusForManaged (setFocusForManagedRequest request, CallContext context = default);
}

[ProtoContract(SkipConstructor = true)]
public class setFocusForManagedRequest
{
    
    [ProtoMember(1)]
    public  String  vmName { get; set; }
    
    [ProtoMember(2)]
    public  Int32  productType { get; set; }
    
    [ProtoMember(3)]
    public  Boolean  bOverWrite { get; set; }
    
    [ProtoMember(4)]
    public  IntPtr  m_EvEventExtern { get; set; }
    
    [ProtoMember(5)]
    public  Boolean  isDisposed { get; set; }
    
}

@mgravell  Do we see this issue since the request message has IntPtr  data member. If yes, then how do we avoid this error?
Other APIs are working if they dont have intPtr data type member.

**Comment by mgravell** [comment]
I think we're covering this in #282

**Comment by shivkumarghatbale** [comment]
Yes
