### ISSUE TITLE
How to use gRPC-Web? when I use code first?

### ISSUE THREAD

**Issue by soroshsabz** [protobuf-net/protobuf-net.Grpc#296]
ITNOA

I want to use gRPC-Web to generate RESTful API in code first approach. but I have some question about that?

* How to doing that?
*  How to add json specific annotate?
```
    option (google.api.http) = {
      get: "/v1/greeter/{name}"
    };
```
* How to using Swagger for documentation? as you can see in https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?view=aspnetcore-7.0
thanks

**Comment by soroshsabz** [comment]
duplicate from #264

**Comment by zhoudi94** [comment]
I think this configuration is very useful, are there any plans to implement it?

**Comment by soroshsabz** [comment]
> I think this configuration is very useful, are there any plans to implement it?

You must upvote #264
