### ISSUE TITLE
Grpc code first versioning

### ISSUE THREAD

**Issue by soroshsabz** [protobuf-net/protobuf-net.Grpc#303]
ITNOA

as you can see in https://learn.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-7.0

in GRPC we can use versioning by defining `package` in `proto` file

How to achieve same functionality in code first approach?

thanks

**Comment by soroshsabz** [comment]
@mgravell

**Comment by mgravell** [comment]
The service name (including package) can be explicitly controlled via [Service] / [ServiceContract] - not in a position to check right now, but IIRC the example in the code linked should work as `[Service("greet.v1.Greeter")]`; however, you then still need to *provide* all the services that you want, so you might end up with multiple interfaces - `IGreeterV1`, `IGreeterV2`, etc. A single service could implement all of them, or you could have a service per interface, etc

Does that help?

**Comment by soroshsabz** [comment]
@mgravell 

If I correct understand 

```
namespace BSN.Resa.Cas.AppService.Contract
{
    [ServiceContract("BSN.Resa.Cas.V1")]
    public interface ICaptchaQueryService
    {
        Task<Response<CaptchaVerifyViewModel>> VerifyAsync(CaptchaQueryServiceVerifyRequest request);
    }
}
```

Am I right?

**Comment by soroshsabz** [comment]
For preventing write ugly interface, Am I can write below for vresioning?

```
namespace BSN.Resa.Cas.AppService.Contract.V1
{
    [ServiceContract]
    public interface ICaptchaQueryService
    {
        Task<Response<CaptchaVerifyViewModel>> VerifyAsync(CaptchaQueryServiceVerifyRequest request);
    }
}

```

Is it correct work?

**Comment by mgravell** [comment]
using namespaces to do the versioning would also work, yes; you can combine the two, if the C# namespace layout and .proto version layout aren't entirely 1:1

**Comment by soroshsabz** [comment]
Thanks a lot for responding :)
