### ISSUE TITLE
Realize POCO approach in protobuf-net.Grpc.AspNetCore

### ISSUE THREAD

**Issue by GoNextGroup** [protobuf-net/protobuf-net.Grpc#31]
Hello, Marc.

Earlier you realized POCO approach which was proposed  by mythz. I see the method `AddCodeFirst` in the `ServiceDefinitionCollectionExtensions` class.
So, I have 2 questions:
1)        

```
 public static int AddCodeFirst<TService>(this ServiceDefinitionCollection services, TService service,
            BinderConfiguration? binderConfiguration = null,
            TextWriter? log = null)
            where TService : class
        {
            var builder = ServerServiceDefinition.CreateBuilder();
            int count = Binder.Create(log).Bind<TService>(builder, binderConfiguration, service);
            services.Add(builder.Build());
            return count;
        }
```
Can this method be used twice or more times for different services? I really do not understand why this method do not assembly all services marked by marker interface `IGrpcService`.  Could this method be wided for autoassembly all services realized `IGrpcService` marker interface?

2) Unfortunatelly, I cannot use this approach on ASP.NET Core project via 
`public static IGrpcServerBuilder AddCodeFirstGrpc(this IServiceCollection services, Action<GrpcServiceOptions>? configureOptions)`.
Could `AddCodeFirstGrpc` method be cloned and made similar to the `AddCodeFirst` method from `Native` realization?

Thank you.

**Comment by mgravell** [comment]
1. Yes; as for IGrpcService, that has existed for literally days - if there's something extra you think should work, please supply a clear usage example so we can discuss it clearly

2. What bit do you want to be "made similar"? In both cases they just register things with the underlying API. The details, however, are implementation specific. What is the thing you want to do, but can't?

**Comment by GoNextGroup** [comment]
Hello, Marc.

1) If you'll check `AddCodeFirst` method, you see that it needs to call each time you want to add "Server Side Service" implementation. And you can see the same realization in the mythz  example (`_server.Services.AddCodeFirst(new ApplyServices());`). 
`IGrpcService` marker interface was added to mark Service realization. But why `AddCodeFirst` method can't be just `public static int AddCodeFirst<TService>(this ServiceDefinitionCollection services, BinderConfiguration? binderConfiguration = null,
            TextWriter? log = null)`
where in the internal you can find all classes which realize `IGrpcService` and call `public static int AddCodeFirst<TService>(this ServiceDefinitionCollection services, TService service,
            BinderConfiguration? binderConfiguration = null,
            TextWriter? log = null)`.

2)  'AddCodeFirstGrpc' do not register Service inherits from IGrpcService marker interface. Just only native server realization can "map" same Service inherits 'IGrpcService`. I've tried to realize, but it hasn't work...

**Comment by mgravell** [comment]
> But why `AddCodeFirst` method can't be just public static int `AddCodeFirst<TService>(this ServiceDefinitionCollection services, BinderConfiguration? binderConfiguration = null, TextWriter? log = null)` where in the internal you can find all classes which realize `IGrpcService` and...

find *from where*? and what is `<TService>` there? Did you perhaps mean  something like:

``` c#
AddCodeFirst(this ServiceDefinitionCollection services, Assembly assembly, BinderConfiguration? binderConfiguration = null, TextWriter? log = null)
```

with it scanning all the types in `assembly`? but in that scenario, I wouldn't expect it to be limited to *just* `IGrpcService` - since that has different rules; it would probably need to include all `[ServiceContract]` too.

**Comment by GoNextGroup** [comment]
Sorry, Marc, my fault. It works perfect now (under ASP.NET Core). Thank you.
