### ISSUE TITLE
Empty List converted to null?

### ISSUE THREAD

**Issue by Roy-se7en** [protobuf-net/protobuf-net.Grpc#315]
if the server return the data (include the empty list), the client receive the list is null?

**Comment by mgravell** [comment]
In the protobuf wire format, there is no distinction between "null" and "empty", nor any concept of "null" at all. By default, then, protobuf-net:

- doesn't write anything if a collection type is null or empty
- when reading, if not found: leaves the member alone

This means that by default, your collection will be whatever your type initializes it as. A common approach is to initialize as empty:

```
[ProtoMember(42)]
public List<Foo> Foos {get;} = new();
```

For explicit null support, allowing nulls to be represented separately to empty (for both elements and the collection, separately), see: https://protobuf-net.github.io/protobuf-net/nullwrappers

**Comment by Roy-se7en** [comment]
Thanks for your reply!
