### ISSUE TITLE
Is it protobuf-net.Grpc 1.1.1 compatible with protobuf-net 3.2.30?

### ISSUE THREAD

**Issue by ComptonAlvaro** [protobuf-net/protobuf-net.Grpc#322]
Hello:

I am using the last version of protobuf-net.Grpc, the version 1.1.1 and it uses version 2.4.8 of the protobuf-net.

I would like to know if it is possible to use the version 3.2.30 of protobuf-net, the last version, because it is compatible with the type DateOnly and I would like to know if I could use this version with protobuf-net.Grpc.

Thanks so much.

**Comment by mgravell** [comment]
Yes; the down-level reference is just to not *force* people to use V3, but: V3 works fine, and protobuf-net.Grpc can identify V3 and use newer features advantageously

**Comment by ComptonAlvaro** [comment]
Thanks so much for the attention.
