### ISSUE TITLE
DateOnly support

### ISSUE THREAD

**Issue by PatriQ94** [protobuf-net/protobuf-net.Grpc#326]
Is there any plans to add DateOnly support?

**Comment by PatriQ94** [comment]
> Is there any plans to add DateOnly support?

Fixed.
Previously we've had only `protobuf-net.Grpc.AspNetCore` and `protobuf-net.Grpc.AspNetCore.Reflection` nuggets installed which didn't work out of the box, so result was to simply install `protobuf-net` of version 3.2.30 aswell, which apparently fixed the DateOnly types.

**Comment by mgravell** [comment]
Maybe I should make a "major" rev at some point that brings protobuf-net.Grpc in line with protobuf-net v2
