### ISSUE TITLE
Make Callcontext injectable

### ISSUE THREAD

**Issue by ElderJames** [protobuf-net/protobuf-net.Grpc#33]
Can I inject the `Callcontext` to the constructor of service implement？
Just like the `IHttpContextAccssor` that it does not need to be a method parameter.

**Comment by mgravell** [comment]
No; the call-context is strictly per operation - it has a very different lifetime than the service (on the native version, the service is essentially a singleton; on Kestrel, the service lifetime is configurable in many different ways). I'd also rather avoid some kind of ambient thread-local API.

Can you clarify: what is the scenario where you need it, but are reluctant to make it a parameter?

**Comment by ElderJames** [comment]
I want to get data from headers of the current `HttpContext`,like `jwt`,better to make the `IHttpContextAccssor` work in the service on Kestrel.

**Comment by mgravell** [comment]
OK; I understand what you mean.

@JamesNK: before I go too far down the rabbit-hole investigating this - is there any ambient gRPC context already implemented in your bits?

**Comment by ElderJames** [comment]
And I also need to get the complate signal from client at duplex streaming mode

**Comment by mgravell** [comment]
@ElderJames that sounds like a very different thing, but that *should* currently materialize as the end of the `IAsyncEnumerable<T>` sequence. Is that now working for you? Or are you after something different? Perhaps an example of your intent would help there

**Comment by ElderJames** [comment]
Ok,  `yield break`  for IAsyncEnumerable<T> is work.

**Comment by mgravell** [comment]
I'm assuming that `HttpContextAccessorExtensions.GetServerCallContext` / `.GetCallContext` do what is needed here
