### ISSUE TITLE
Signscale type is unit32 when using reflection for decimals

### ISSUE THREAD

**Issue by marvinatorrr** [protobuf-net/protobuf-net.Grpc#344]
When client is using reflection to get the contracts, decimal types are represented using lo, hi, and signscale.

However signscale is uint32 so there is no way to input a negative decimal using reflection (through postman, grpcui etc)

For example lets say I want to send decimal -3.14 to the server, I would need to input lo: 314, hi: 0, and signscale: -2.

**Comment by mgravell** [comment]
Firstly, note that if possible, I would suggest using compatibility level (https://protobuf-net.github.io/protobuf-net/compatibilitylevel.html) to avoid bcl.proto whenever using x-plat tooling (or indeed, in general) - however, this is a data breaking change, so don't blindly flip switches!

However: signscale really is uint; the sign is in the low bit, not the high bit.

**Comment by marvinatorrr** [comment]
thanks this solved my issue
