### ISSUE TITLE
Integration with Serilog

### ISSUE THREAD

**Issue by christopheblin** [protobuf-net/protobuf-net.Grpc#42]
I try to integrate protobuf-net.Grpc with Serilog so that all my logs are written as JSON

           Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
                .MinimumLevel.Override("Grpc.AspNetCore", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .WriteTo.Console(new RenderedCompactJsonFormatter())
                .CreateLogger();

            await WebHost.CreateDefaultBuilder(args)
                .UseSerilog()
                .ConfigureKestrel(options =>
                {
                    options.ListenLocalhost(Constants.GRPC_PORT, listenOptions =>
                    {
                        listenOptions.Protocols = HttpProtocols.Http2;
                    });
                })
                .UseStartup<StartupGrpc>()                
                .Build()
                .RunAsync();

When I start the service, I have the following logs:

```
{"@t":"2019-11-20T08:01:41.6062274Z","@m":"RPC services being provided by \"Service1.Service1\": 1","@i":"99042bdd","0":"Service1.Service1","1":1,"SourceContext":"ProtoBuf.Grpc.Server.ServicesExtensions.CodeFirstServiceMethodProvider"}
Hosting environment: Production
Content root path: xxx\Service1\bin\Debug\netcoreapp3.0
Now listening on: http://localhost:10001
Application started. Press Ctrl+C to shut down.
{"@t":"2019-11-20T08:01:42.4065927Z","@m":"Received Sum 12 + 12","@i":"a7280eb5","SourceContext":"Service1.Service1","RequestId":"0HLRDHVGJL7QN:00000001","RequestPath":"/Service1.Def.Service1/Sum","SpanId":"|6569d07-4421f5010ca3a214.1.1.31cbe944_","TraceId":"6569d07-4421f5010ca3a214","ParentId":"|6569d07-4421f5010ca3a214.1.1."}
```

As you can see there are some parts where Serilog is not used.

How can I change that behavior ?

**Comment by mgravell** [comment]
If you're talking about the 4 in the middle: pretty sure none of those are coming from this library, so I may not be the best person to ask. You could start by looking to see where (in GitHub) the those strings are coming from.

**Comment by mgravell** [comment]
Example: https://github.com/aspnet/Hosting/blob/a3300a6a605dd66d79fabc297e8d8abdb8b8edf6/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs#L120

**Comment by mgravell** [comment]
It does look like you could configure `options.SuppressStatusMessages` though, looking at that code.

**Comment by christopheblin** [comment]
Thanks for the pointers !

I finally found the deep cause of that mess : WebHost does not use ILogger whereas Host does

So, in order to solve the problem, you simply need to do:

        await Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(options =>
                {
                    options.UseSerilog();
                    options.ConfigureKestrel(kestrel =>
                    {
                        kestrel.ListenLocalhost(Constants.GRPC_PORT, listenOptions =>
                        {
                            listenOptions.UseHttps();
                            listenOptions.Protocols = HttpProtocols.Http2;
                        });
                    });
                    options.UseStartup<StartupGrpc>();
                })
                .RunConsoleAsync();
