### ISSUE TITLE
System.Exception:“Status(StatusCode=Unimplemented, Detail="")

### ISSUE THREAD

**Issue by xyz0822** [protobuf-net/protobuf-net.Grpc#46]
Like in folder toys with PlayClient and PlayServer,if I Define a ServiceContract in PlayClient project like below:

    [ServiceContract]
    public interface IHello
    {
           ValueTask<HelloResponse> SayHello(HelloRequest request);
    }

and **also Define the ServiceContract  in the PlayServer**. 
In PlayServer i add the code like below :

`   server.Services.AddCodeFirst(new PlayServer.Hello());`

In PlayClient i add the code like below:

`  var hello = channel.CreateGrpcService<IHello>();`

and trying to invoke rpc request:

`  var result = await hello.SayHello(new HelloRequest { name = "1" });`

and i got an error "**System.Exception:“Status(StatusCode=Unimplemented, Detail="")**"
**it seems  the IHello Interface ServiceContract must be the same on and in the same project and also referenced by  the two project,PlayClient and PlayServer.**

Will it designed to be so?what if i put the IHello Interface to the thirtpart people?

**Comment by mgravell** [comment]
Hi; are they in the same *namespace* in both? the default behavior is to infer the gRPC endpoint name using the **namespace qualified** name of the service interface; if they will be in different namespaces between client and server, that won't work properly - so you'll need to explicitly qualify the fully qualified name in `[ServiceContract(Name = ...)]`. If you supply a `Name`, it is used exactly "as is", with no further processing. So hopefully, just make sure that this `Name` matches at both ends.

Let me know!

**Comment by mgravell** [comment]
Oh, for completeness: there is another lazy way of resolving this; if your service also implements `IGrpcService`, then a light-weight mode is used, which has a lot less processing of things; among other things, if you implement `IGrpcService` then *only* the type-name (without namespace qualification) is looked at.

**Comment by xyz0822** [comment]
> Hi; the two definitions of `IHello`: are they in the same _namespace_ in both? the default behavior is to infer the gRPC endpoint name using the **namespace qualified** name of the service interface; if they will be in different namespaces between client and server, that won't work properly - so you'll need to explicitly specify the a name in `[ServiceContract(Name = ...)]`. If you supply a `Name`, it is used exactly "as is", with no further processing. So hopefully, just make sure that this `Name` matches at both ends.
> 
> Let me know!

Yes，the two definitions of `IHello` are not the same _namespace_ , put in the same namespace works fine. and the lazy way  is also great. 
Thanks a lot for advising!
