### ISSUE TITLE
No serializer defined for type: 'System.Object'

### ISSUE THREAD

**Issue by mhingston** [protobuf-net/protobuf-net.Grpc#47]
Hi,

I'm having an issue trying to use protobuf-net.Grpc.Native. I'm finding that parameters from calls from the gRPC client are not being serialized for custom types. I have an [example repo](https://github.com/mhingston/protobuf-net.gRPC) which demonstrates the issue. When I try and call the [GetUsers](https://github.com/mhingston/protobuf-net.gRPC/blob/2acb5c9f794b08463c1e00c4e20cfff9f1df8eb1/Shared/Client.cs#L21) method the [QueryRequest](https://github.com/mhingston/protobuf-net.gRPC/blob/2acb5c9f794b08463c1e00c4e20cfff9f1df8eb1/Shared/Common.cs#L9) object is not being serialized.

`No serializer defined for type: 'System.Object' DAL/Shared/Client.cs (Line 21)`

Any help/pointers would be appreciated.

Thanks.

**Comment by mhingston** [comment]
I changed the `[DataContract]` annotation in `DAL/Shared/Common.cs` to use [ProtoContract]` instead and it now works as expected.

**Comment by mgravell** [comment]
Really appreciate the repro - best way of getting useful input. I should have time to look at this on the weekend.

**Comment by mgravell** [comment]
Right; the main cause of this is:

``` c#
[DataMember(Order = 2)]
public object Parameters { get; set; }
```

Protobuf isn't very good at dealing with untyped data, however there *are* ways of handling data of constrained possibilities. If you can advise on the intended range of possible values of `Parameters`, then I can offer guidance on how bet to encode that, but: "any arbitrary object" isn't going to work well.

**Comment by RebelionTheGrey** [comment]
The fast and dummy solution for this situation, I think, is using different json serializer which can store derived object information fully (you need to pass different types of object from same set, am I right?).

So, you need to add 2 properties: one is a string, second is a calculated property like

`protected string ParameterString { get; set; }
[JsonIgnore]
public object Parameter { get { return JsonConvert.Deserialize(ParameterString) }`

In this case I used `NewtonsoftJson`, which allows to store full type information about serialized object. Maybe other serializers allow the same - I don't know any who stores it fully.

Maybe this solution will be convenient for you, I hope.

**Comment by mythz** [comment]
Apart from being a hole in the Type System contract, a source of runtime issues and undeterministic behavior in other protocol buffers serializers, `object` is also [a security risk in all .NET serializers](https://www.blackhat.com/docs/us-17/thursday/us-17-Munoz-Friday-The-13th-Json-Attacks.pdf) that doesn't restrict the serialization of allowed types, e,g:

> In fact [the only kind that is not vulnerable is the default: TypeNameHandling.None](https://www.alphabot.com/security/blog/2017/net/How-to-configure-Json.NET-to-create-a-vulnerable-web-API.html)

> In this case I used NewtonsoftJson, which allows to store full type information about serialized object. Maybe other serializers allow the same - I don't know any who stores it fully.

Many do, but they're done and configured differently, so not only would this break compatibility with protocol buffers in different languages, it also incompatible across different .NET JSON implementation. 

If you want it serialized as JSON you should do it yourself by storing serialized JSON in a `string` field using your preferred JSON serializer and custom JSON configuration that's explicitly configured to work for your use-case. Or you could store information in an unstructured type like a string dictionary, or provide a hook which allows users to configure `object` serialization behavior. But you shouldn't expect protobuf-net to take dependency on an external serialization implementation to implement a incompatible and potentially vulnerable feature.

**Comment by mgravell** [comment]
Just to emphasize: for a lot of scenarios where I see people using `object`, there *are* pre-existing perfectly safe supported analogues in protobuf. Including:

- discriminated unions (`oneof`)
  - note that inheritance in protobuf-net is implemented via this approach
- `Any`
- `.google.protobuf.Value`

Hence I strongly suggest rather than trying to leap into solutions, it would be best to clarify the intent. There may be good options!

**Comment by mhingston** [comment]
Thanks all for the fast and helpful responses, much appreciated.

@mgravell The `Parameters` property is currently an anonymous type for use with Dapper as described [here](https://dapper-tutorial.net/parameter-anonymous).

@RebelionTheGrey 

> you need to pass different types of object from same set, am I right?

Yes, that's correct. I could use Newtonsoft but take note of the advice from @mythz.

**Comment by mgravell** [comment]
(quietly mutters darkly about that "here" site, but that's an entirely unrelated matter)

@mhingston  yeah, anonymous types are not really going to work - they can't be part of a meaningful contract. Ultimately, service contracts in the gRPC sense (or indeed *most* RPC senses) need to formally know what is being sent. Your best option is a per-API contract type, but a lot call also be done with inheritance, for example:

``` c#
[ProtoContract]
[ProtoInclude(1, typeof(Foo))]
[ProtoInclude(2, typeof(Bar))]
// ...
abstract class NamingIsHard {}

[ProtoContract]
class Foo : NamingIsHard {
    // ...
}
[ProtoContract]
class Bar : NamingIsHard {
    // ...
}
```

and use a `NamingIsHard` on the contract; now you can send a `Foo`, a `Bar`, etc and it should all work correctly.

**Comment by mhingston** [comment]
Thanks @mgravell

**Comment by tagcode** [comment]
Anonymous types work just fine. https://stackoverflow.com/a/72408227/499112 
Needs only HashSet<Type> validation for acceptable types.

**Comment by AgentFire** [comment]
> Right; the main cause of this is:
> 
> ```cs
> [DataMember(Order = 2)]
> public object Parameters { get; set; }
> ```
> 
> Protobuf isn't very good at dealing with untyped data, however there _are_ ways of handling data of constrained possibilities. If you can advise on the intended range of possible values of `Parameters`, then I can offer guidance on how bet to encode that, but: "any arbitrary object" isn't going to work well.

What if the intended range of possible values are "all the explicitly registered/added types"? How would you approach creating a serializer for the `object` type which would minimize the data packet? Is there an internal "number" of any given registered type? So that we would avoid serializing the whole string of assembly-qualified name of the type?

**Comment by glazkovalex** [comment]
> ... are pre-existing perfectly safe supported analogues in protobuf. Including:
> ...
> * .google.protobuf.Value

@mgravell, Hellow!
 How do I set the code-first, a message with the google.protobuf.Value field?
