### ISSUE TITLE
[Question] Does hosting GRPC services automatically preclude also hosting rest

### ISSUE THREAD

**Issue by ronnyek** [protobuf-net/protobuf-net.Grpc#55]
I've got an existing REST api I'd like to additionally like to add some GRPC api methods to. If in the program.cs for the server, I set kestrel options to use protocols `Http1AndHttp2`, grpc calls from clients fail. 

If I set it to strictly `Http2`, GRPC works, but rest endpoints do not.

I don't know if this is a limitation of Grpc.Net, or protobuf-net.Grpc, but wondered if there was a way I could "have my cake, and eat it too".

**Comment by mgravell** [comment]
this is probably a question for @JamesNK (perhaps over on https://github.com/grpc/grpc-dotnet); protobuf-net.Grpc simply hooks into whatever grpc-dotnet provides, and is outside of my control

**Comment by ronnyek** [comment]
Short answer here was no... My examples, I was disabling the the TLS/SSL validation, which is required for http2/http1 negotiation. Using a self signed cert and changing url examples to use https resolved the problem for me. 

Hopefully this helps someone else down the road.
