### ISSUE TITLE
ASP.NET core 3.1 gRPC-Web 2.27-pre1  

### ISSUE THREAD

**Issue by gustav3d** [protobuf-net/protobuf-net.Grpc#57]
Hello ,

I'm trying to get the experimental ASP.NET core 3.1 gRPC-Web 2.27-pre1 to work with code-first protobuf-net.Grpc core.

Is it supposed to function together or i'm i doing sometng wrong ?

       public void ConfigureServices(IServiceCollection services)
        {
            services.AddCodeFirstGrpc(config => {
            });
            services.AddCors(options => {
                options.AddPolicy(myCORs,
                builder => {
                builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod();
                });
            });                                   
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {         
            app.UseRouting()
                .UseGrpcWeb()
                .UseCors(myCORs)           
            .UseEndpoints(endpoints =>
            {
                GrpcEndpointRouteBuilderExtensions.MapGrpcService<DataService>(endpoints).EnableGrpcWeb();

info: ProtoBuf.Grpc.Server.ServicesExtensions.CodeFirstServiceMethodProvider[0]
      RPC services being provided by AdminTransportGrpcService.DataService: 1
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Gustav Trede\stuff\code\AdminTransportServer_NET\AdminTransportGrpcService
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:5001/AdminTransportGrpcService.DataService/getAllData
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 37.7098ms 204
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5001/AdminTransportGrpcService.DataService/getAllData application/grpc-web+proto 5
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AdminTransportGrpcService.DataService/getAllData'
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'getAllData'.
System.InvalidOperationException: A suitable constructor for type 'AdminTransportGrpcService.DataService' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)   at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.<>c.<.cctor>b__4_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.Create(IServiceProvider serviceProvider)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /AdminTransportGrpcService.DataService/getAllData'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 178.9004ms 200 application/grpc-web

**Comment by mgravell** [comment]
It is complaining about the constructor for
AdminTransportGrpcService.DataService
- can we see that type at all?

**Comment by gustav3d** [comment]
I followed the example code and made no constructors:

[ServiceContract] 
    public interface DataService
    {
        public Task<GetAllDataResp> getAllData(GetAllDataReq request, CallContext context = default);
    }


    public class _TransportAdmin : DataService
    {
        public Task<GetAllDataResp> getAllData(GetAllDataReq request, CallContext context = default)
        {
            return Task.FromResult(new GetAllDataResp
            {
               apa = DateTime.Now
            });
        }

**Comment by gustav3d** [comment]
I dont understand what you mean, the actual service with its constructors is runtime created by your code right ?

**Comment by mgravell** [comment]
Clients: yes

Servers: no, entirely yours. My code does the plumbing.

This *looks* like server?

**Comment by gustav3d** [comment]
yes

**Comment by mgravell** [comment]
OK. Well, I haven't yet had time to even look at gRPC-Web. To the beat of
my knowledge: nothing changes here, and the same style of code that worked
for regular gRPC should be fine. If that isn't the case, I'd need to
investigate.

Is your experiment here isolated in the "here's my tiny standalone GitHub
repo" sense, by any chance?

**Comment by gustav3d** [comment]
I created an isolated rep now https://github.com/gustav3d/aspnetcore-grpc-.git :)

**Comment by mgravell** [comment]
Awesome; with that, it *looks* like the problem is that you're telling it to:

``` c#
endpoints.MapGrpcService<DataService>();
```

but `DataService` is the *interface*, not the service; you *probably* want to use the concrete service type there - the library will then *figure out* what relevant interfaces your service type supports, and will do all the necessary bindings. Without telling it the concrete service type, it won't know what to create.

As a tip: I'd probably also strongly advocate the .NET convention here of using the `I` prefix, i.e. `IDataService` to denote interfaces. The problem would have been more obvious, at least!

Let me know if this helps (or doesn't)

**Comment by mgravell** [comment]
specifically, you probably want:

``` c#
endpoints.MapGrpcService<_TransportAdmin>();
```

although note that your `_TransportAdmin` type has multiple complex constructors - this *may* confuse the DI binder. Note that the DI binder (i.e. the way the constructors work) is outside of the control of protobuf-net.Grpc, so I can't work any magic for you here: your service needs to play nicely with the ASP.NET framework.

**Comment by gustav3d** [comment]
Using the impl class name worked !!
Thanks a lot for the help !
