### ISSUE TITLE
Compatibility with blazor web assembly client

### ISSUE THREAD

**Issue by julienGrd** [protobuf-net/protobuf-net.Grpc#59]
Hello, I actually migrate a silverlight/wcf app to blazor web assembly (.net core hosted)/grpc solution.

Your solution seem perfect for what i looking for (don't want to write the proto file but reuse class), but it seem you insist on the fact client and server project need target .net core 3 (in this doc https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted). 

However my webAssembly webapp is in .net standard (2.1). Globally all my assembly target .net sandard except the server app.

There is a solution to make it work together anyway ? 

thanks !

**Comment by mgravell** [comment]
That is a misconception / miscommunication. Protobuf-net.Grpc works fine on earlier TFMs - the only difference is that you can't use the newer Microsoft transports; you must instead use the established Google transports from Grpc.Core.

Protobuf-net.Grpc works identically on either.

**Comment by mgravell** [comment]
Further, for *client* work, the Microsoft transports might work just fine on NS2.1

For *server* work, I believe the Microsoft pieces are tied to Kestrel, which is .NET Core, not .NET Standard.

**Comment by julienGrd** [comment]
Ok i tried to implement this on empty blazor web assembly app.
configuration : .net core 3.1.1 for server, .net standard 2.1 for webap and shared project
I double check i forget nothing but it seem not works
Ihave the error Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: TypeError: Failed to fetch")
I'm surprise of the url called : http://localhost:10042/BlazotTestProtobufGrpc.Shared.Calculator/Multiply.
If i try to put a name of the service like the example
````
[ServiceContract(Name = "Hyper.Calculator")]
    public interface ICalculator
````
I have a different error
System.TypeInitializationException: The type initializer for 'DefaultProxyCache`3' threw an exception. ---> System.ArgumentException: Get Method not found for 'Name'

I can solve the last one by adding a specific directive which solve some webassembly problem but i go back to the first error.

When i look in the server console it seem not listen on port 10042 so maybe its a server related problem

Finally, i try to run your examples problem by checkout the repository, but same thing it seem the server not listen (nothing in the console with 10042 port) and the client throw error Error starting gRPC call : connexion refused.

So i don't know whats happen.

you can find the blazor project here https://github.com/julienGrd/BlazotTestProtobufGrpc

thanks !

julien

**Comment by mateusz-pietrzak** [comment]
I am having similar problem using protobuf-net.Grpc on Blazor/WASM:

```
System.TypeInitializationException: The type initializer for 'DefaultProxyCache`3' threw an exception. ---> System.ArgumentException: Invalid generic arguments
Parameter name: typeArguments
```

@julienGrd  Can you share the directive you had to add to fix this problem?

**Comment by mateusz-pietrzak** [comment]
@julienGrd In order to get this working with Blazor over WASM I believe you have to use **Grpc.Net.Client.Web** package and then instantiate channel (example taken straight from grpc-dotnet github with DI):

 ```
builder.Services.AddSingleton(services =>
            {
                // Create a gRPC-Web channel pointing to the backend server.
                //
                // GrpcWebText is used because server streaming requires it. If server streaming is not used in your app
                // then GrpcWeb is recommended because it produces smaller messages.
                var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler()));

                var channel = GrpcChannel.ForAddress("https://localhost:5001", new GrpcChannelOptions { HttpClient = httpClient });

                return channel;
            });
```

Then you can simply create channel with benefit of DI (I believe that you do not have to use the Empty dummy message when using protobuf-net.Grpc):

```
@inject GrpcChannel Channel

...

var client = new WeatherForecasts.WeatherForecastsClient(Channel);
forecasts = (await client.GetWeatherForecastsAsync(new Empty())).Forecasts;
```

https://github.com/grpc/grpc-dotnet/tree/master/examples/Blazor/Client

**Comment by julienGrd** [comment]
I didn't want to use the classic grpc.net package because it require all the proto file (that's why protobuf-net package was perfect for me, i already have all my classes came from wcf services and don't want to describe all of them).

Anyway I test the blazor example you put in your message and i have the same error
````
POST https://localhost:5001/count.Counter/StartCounter net::ERR_CONNECTION_REFUSED
blazor.webassembly.js:1 WASM: Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: TypeError: Failed to fetch")
blazor.webassembly.js:1 WASM:   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2[TRequest,TResponse].MoveNextCore (System.Threading.CancellationToken cancellationToken) [0x00393] in /tmpfs/src/github/grpc-dotnet/src/Grpc.Net.Client/Internal/HttpContentClientStreamReader.cs:200 
````

I think i will wait for a working example with blazor and this package

@mgravell : If it suppose to work (blazor + this package), can you put a working example somewhere ?

thanks !

**Comment by mateusz-pietrzak** [comment]
It does not require proto files, I'm using it with protobuf-net.Grpc currently and it works fine. It's just needed for Blazor in order to integrate Grpc with HttpClient that ships with Blazor (as I believe it's kind of special one since it's interoping with native  httprequest, you cannot use the same one that you would use for example in Console app due to browser sandboxing).

**Comment by julienGrd** [comment]
@mateusz-pietrzak : do you have a working example on github which i can test ?

thanks for your help !

**Comment by mateusz-pietrzak** [comment]
Here you go:

https://github.com/mateusz-pietrzak/BlazorAppGrpcTest

Let me know if it works.

**Comment by julienGrd** [comment]
your project work fine thank you very much !

I begin to adapt it to my project, works fine too :-). The only problem : the class really need The Order in the DataMember attribute, otherwise it not works (I reuse existing wcf generated class which don't have this).

I close this issue, but it can be nice to reference the project of @mateusz-pietrzak in the docs of this project
