### ISSUE TITLE
Example of how to setup encrypted channel?

### ISSUE THREAD

**Issue by mhingston** [protobuf-net/protobuf-net.Grpc#61]
I'm trying to setup encrypted communication between client and server using protobuf-net.Grpc.AspNetCore. I've setup Kestrel to use a certificate and require a client certificate as shown [here](https://github.com/mhingston/protobuf-net.Grpc-issue/blob/a6787e403c7fb486a608912897449a0db406dbb4/Server/Program.cs#L28). On the client I have setup the HttpClient to use a client certificate as shown [here](https://github.com/mhingston/protobuf-net.Grpc-issue/blob/a6787e403c7fb486a608912897449a0db406dbb4/Client/Client.cs#L25). When I run the Server and then the TestClient in my [example repo](https://github.com/mhingston/protobuf-net.Grpc-issue) I receive the following stack trace:

    System.AggregateException
    HResult=0x80131500
    Message=One or more errors occurred. (Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request."))
    Source=System.Private.CoreLib
    StackTrace:
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at System.Threading.Tasks.Task`1.get_Result()
    at DAL.TestClient.Program.Main(String[] args) in DAL\TestClient\Program.cs:line 10

    This exception was originally thrown at this call stack:
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
        System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
        ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl<TRequest, TResponse>(Grpc.Core.AsyncUnaryCall<TResponse>, ProtoBuf.Grpc.Internal.MetadataContext) in Reshape.cs
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
        System.Threading.Tasks.ValueTask<TResult>.Result.get()
        System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
        ...
        [Call Stack Truncated]
    Inner Exception 1:
    RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")

Would be grateful if someone could provide an example of how to setup encrypted channel.

Thanks!

**Comment by mgravell** [comment]
I can try and take a look when I get a second, however: ultimately protobuf-net.Grpc is just piggy-backing off the transports already provided by Microsoft (in this case) or Google, and this *looks* mostly like a transport question (i.e. none of it directly touches anything specific to protobuf-net); I'm going to be cheeky and ping @JamesNK here, because *if* this is a fundamental transport config issue, it is likely that they'll be able to spot it faster than me.

**Comment by mhingston** [comment]
Thanks @mgravell, this is indeed a transport config issue and not protobuf-net.Grpc specific.

The following [sample code](https://stackoverflow.com/a/54057626) for configuring certificate validation with Kestrel was able to help me out.
