### ISSUE TITLE
[Feature Request] Provide an alternative custom attribute to System.ServiceModel.ServiceContract to remove dependency with System.ServiceModel.dll

### ISSUE THREAD

**Issue by TieSKey** [protobuf-net/protobuf-net.Grpc#66]
Pretty much as the title says. 
While trying to test this library from Unity3D engine, I had some problems importing the System.ServiceModel.dll which led me to inspect your code and noticed the attribute is matched by name.
Knowing this I implemented my own System.ServiceModel.ServiceContractAttribute class to fool the library and it worked. 
As I understand there's no other part of the library or its dependencies that depend on System.ServiceModel.dll so providing a second equivalent attribute (ProtoServiceContractAttribute?) in addition to the current MS one, some users will be able to remove the otherwise unneeded dll.

This is somewhat related to #62 as enabling the inheritance flag in the alternative attribute could solve their problems I think.

**Comment by mgravell** [comment]
So to be 100% clear: you're proposing a new additional attribute that is
functionally equivalent to ServiceContractAtteribute?

**Comment by TieSKey** [comment]
Exactly.

**Comment by mgravell** [comment]
proposed in PR above

**Comment by mgravell** [comment]
now available on myget: https://www.myget.org/F/protobuf-net/api/v3/index.json
