### ISSUE TITLE
CallContextAccessor

### ISSUE THREAD

**Issue by jkears** [protobuf-net/protobuf-net.Grpc#72]
In my current approach I have a bunch of microservices each of which I have an ExecutionContextAccessor which is registered as InstancePerLifetimeScope within Autofac.

The HttpContextAccessor as well as Finbuckle's MultiTenantContextAccessor are injected into my ExecutionContextAccesor's constructor.  

Would it be possible to inject the CallContext into my ExecutionContextAccessor in a similar manner, is that possible? 

This becomes quite important for trace-ability of gRPC-type inter-service communications where Saga flows call across service boundaries.   

Thanks in advance!

**Comment by mgravell** [comment]
If you have an `IHttpContextAccessor`, you *should* have access to the `GetServerCallContext()` and `GetCallContext()` extension methods on that; any use? (they are declared in the `Microsoft.AspNetCore.Http` namespace, note)

**Comment by jkears** [comment]
Thanks for such a quick response.  I will check and will let you know.  

Within my domain services there will be a plethora of inbound custom headers per each request, some will originate back to an initial client request, while others will be manufactured within services and some will need to flow via gRPC or Restful Http, as well as via Integration events that flow out/in over the ESB.   

I would like to ensure that specific custom header's are consistently routed through each request across all of these different types of service integration which will be utilized within the service mesh for observe/trace-ability. 
 
Once again, many thanks for this wonderful solution and very much appreciate your support!

**Comment by mgravell** [comment]
I'm assuming that this worked fine
