### ISSUE TITLE
Question - Exception handling in protobuf-net.Grpc

### ISSUE THREAD

**Issue by duyang76** [protobuf-net/protobuf-net.Grpc#75]
Hi Marc, one more question: how protobuf-net.Grpc handles client/server side exceptions. 

My understanding is that Grpc has standard error model (implemented in C#) and richer error model (not implemented), Microsoft has a different design. What is the design/plan of protobuf-net.Grpc?

**Comment by mgravell** [comment]
Right now, I just explode with whatever the transport channels expose. However, can you give a citation on this "richer error model"? Happy to put some thought into it.

**Comment by duyang76** [comment]
Here is the [document](https://grpc.io/docs/guides/error/) from grpc.io.

It mentioned that "If you’re using protocol buffers as your data format, however, you may wish to consider using the the richer error model developed and used by Google as described here".

Maybe it is something for Grpc.Core or Grpc.net to worry about?

**Comment by mgravell** [comment]
Interesting; that API is still pretty broad and vague, and it looks to me like that would be something best handled by grpc-dotnet; any thoughts on that @JamesNK?

What perhaps gets interesting is if you wanted to propagate *specific exceptions* (like WCF's `[FaultContract]`) This *could perhaps* hack into the

``` protobuf
repeated google.protobuf.Any details = 3;
```

piece, but: *right now* protobuf-net doesn't implement `Any` (it is on the roadmap)

But! Let me turn the question around; in a perfect world, what are *you* looking for in better exception handling? what is your ideal end scenario here?

**Comment by thoblerone** [comment]
I'm coming about the same kind of question, as I like to do some parameter checking. 

As an example, let's assume the calculator should get upset if one of the parameters is zero. Normally I'd simply throw an ArgumentException:

```
        ValueTask<MultiplyResult> ICalculator.MultiplyAsync(MultiplyRequest request)
        {
            if (request.X == 0)
                        throw new ArgumentException($"{nameof request.X} must not be zero"};
            if (request.Y == 0)
                        throw new ArgumentException($"{nameof request.Y} must not be zero"};

            var result = new MultiplyResult { Result = request.X * request.Y };
            return new ValueTask<MultiplyResult>(result);
        }

```

Currently on the client side this behaviour will throw a a simple RpcExeption, not giving away any details on the indicent. I know "something" went wrong but would like to react more specific.

**Comment by mgravell** [comment]
RPC deliberately doesn't leak information by default, and **what** happened: is an implementation detail. If you explicitly *want* to allow that extra info over, you could throw your own `RpcException` with the extra context. Alternatively, we could perhaps add some library-specific exception that allows more, but I'm very hesitant to just expose fault details by default.

I might consider an opt-in config more "reveal exception details" or similar, but even then: it won't 
be able to manifest in the same exception type, except perhaps for a very small set of chosen types - it would just be the *message*.

**Comment by mgravell** [comment]
So; I have a thing; I've just pushed some changes that allows you to decorate methods or services (interfaces or classes) with `[SimpleRpcExceptions]`. If you do this, it will attempt to expose any server faults as `RpcException`, using the `Exception.Message`, and when possible: a suitable `StatusCode`. This will be in the next deploy.

**Comment by mgravell** [comment]
And now also as an alternative option: you can register a service using the `SimpleRpcExceptionsInterceptor`
