### ISSUE TITLE
Grpc.Native at Server side, Interceptor not work

### ISSUE THREAD

**Issue by lansuperman** [protobuf-net/protobuf-net.Grpc#76]
When use protobuf-net.Grpc.Native at the server side, As a console application,

I use the AddCodeFirst extension method add a Interceptor, just like this:
```
server.Services.AddCodeFirst(new TestService(), null, Console.Out, new[] {new TestInterceptor()});
```

Interceptor has override the:
```
public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
{
      Console.WriteLine("Call Start");
      var response = await continuation(request, context);
      Console.WriteLine("Call End");
      return response;
}
```

Service has operation like this:
`ValueTask<ReplyMsg> GetDataAsync(RequestMsg msg);`

Then client call GetDataAsync, At the server side, operation can be executed successfully.
But the override UnaryServerHandler cannot be called.

Do I have any mistakes here? Or is there any example about it, Thanks!

**Comment by mgravell** [comment]
The mistake is mine; fixed in above

**Comment by mgravell** [comment]
1.0.36 should have this, thanks

**Comment by lansuperman** [comment]
So quickly, This project is great!
I can finally get rid of *.proto file.
