### ISSUE TITLE
Using a Client implemented not in C#, VB or F#

### ISSUE THREAD

**Issue by DE96** [protobuf-net/protobuf-net.Grpc#77]
When I use protobuf-net.Grpc to implement my services, is it possible to comsume this service with a client that is not implemented in C#, VB or F# ?

If so, how would you do it?
Is a .proto file used internally?

**Comment by mgravell** [comment]
No, protobuf-net.Grpc does not use a .proto internally; this is not necessary if all parties already know what the contract is.

So, I perceive that the question here is "how can I generate a .proto for a service declared only in interfaces?". At the moment, that piece is incomplete but planned. In most cases it is pretty simple to put one together if you know GRPC, though. Note that protobuf-net *does* have .proto generation from data contracts; the piece that doesn't exist is just the "services" bit. So if you use `Serializer.GetProto<T>` for some data type `T` you can get a good head-start on what should be compatible.

**Comment by DE96** [comment]
Thank you for the quick response.
If I understand you correctly, that means that I can create my proto definitions for messages via `Serializer.GetProto<T>` and the service part I have to write myself?

**Comment by mgravell** [comment]
Today: yes. But the idea is for a similar API to exist that works for
services too.

**Comment by mgravell** [comment]
This now exists, yay! protobuf-net.Grpc.Reflection supports .proto schema generation from services via `SchemaGenerator`, and has support for the `rpc.reflection.v1alpha.ServerReflection` API for runtime work with tooling.
