### ISSUE TITLE
No serializer defined for type: 'System.Object'

### ISSUE THREAD

**Issue by mominmaaz** [protobuf-net/protobuf-net.Grpc#78]
In my project, I have single Contract name Health.cs (attached as Health.txt) and it's implementation in  HealthServer.cs (attached as HealthServer.txt)

I get an error attached as Error.txt

I understand that the error comes because of Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckResult 

[Error.txt](https://github.com/protobuf-net/protobuf-net.Grpc/files/4410452/Error.txt)

[HealthServer.txt](https://github.com/protobuf-net/protobuf-net.Grpc/files/4410421/HealthServer.txt):

[Health.txt](https://github.com/protobuf-net/protobuf-net.Grpc/files/4410413/Health.txt)

**Comment by mgravell** [comment]
You can't serialize something that is as open as `object` - there's just no
good way to represent that in protobuf. Do you know what values the health
result dictionary is likely to contain? There are ways to encode such data,
but to give the most appropriate advice needs context. Ultimately, I'm
going to advise sending something that conveys the same *meaning* as
`HealthCheckResult`,
but your own type, that is serialization friendly.

**Comment by mominmaaz** [comment]
Thanks for such a quick reply.
After reading more about this issue. What you advised seems to be a unanimous opnion to handle such type of object. Thank you.
