### ISSUE TITLE
Allow specifying which methods should be binded

### ISSUE THREAD

**Issue by mythz** [protobuf-net/protobuf-net.Grpc#87]
I'm currently running into issue which is emitting warning errors for trying to bind protected methods in a [GrpcServiceBase.cs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Extensions/Grpc/GrpcServiceBase.cs) base class, e.g:

![image](https://user-images.githubusercontent.com/89361/82844980-39bc6900-9f15-11ea-9782-9f9add11527d.png)

Can we add some way to flag that a method should not be bound? IMO it should only try to bind `public` instance methods, but if there's a reason why non-public methods are bound can we have something like a member-level attribute to say Ignore/DontBind or class level attribute to ignore all methods on this declaring type?

**Comment by mgravell** [comment]
Huh. Yep, totally agree that we shouldn't be looking at these; IMO valid targets are:

- public methods
- non-public methods that are explicit interface implementations of service contracts

I'll investigate.

**Comment by mgravell** [comment]
available from https://www.nuget.org/packages/protobuf-net.Grpc/1.0.81

**Comment by mythz** [comment]
Can confirm issue is resolved, thx!
