### ISSUE TITLE
Make DataMember Order optional for "code-first" migrations

### ISSUE THREAD

**Issue by geoffreygeslin** [protobuf-net/protobuf-net.Grpc#88]
As stated in the [documentation](https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted), DataMembers have to explicit the Order value to migrate with protobuf-net.Grpc.

> Key point: protobuf uses integer tokens to identify members (not names), so you need to tell the library how to map them (positive integers, unique per type:

Can you confirm this is still a prerequisite ?

I have a huge codebase with MANY Wcf DataContracts and ServiceContracts and vast majority does not explicit the Order on DataMembers...
I would like to use protobuf-net.Grpc without any prior edits on my existing DataContracts...

Can protobuf-net.Grpc use or reimplement the "sorting" behavior of DataContractSerializer, so that missing orders could be resolved.

Does this sounds possible ?
Can you point me to the source file(s) where the actual DataContracts "parsing" happens ?

Thanks

**Comment by lanfeust69** [comment]
This is actually the responsibility of the plain protobuf part (independently of the gRPC part).

As it happens, it is possible to activate a global option with something along
```
RuntimeTypeModel.Default.InferTagFromNameDefault = true;
```
However, even if you use this feature, you may want to progressively explicit the order, else you lose one of the advantages of protobuf (and gRPC) : keeping backward compatibility as long as you don't change existing members, and only add new ones.

**Comment by mgravell** [comment]
Yes, @lanfeust69  has covered the main points here - it does exist, but it *is incredibly dangerous* - it basically does an alphabetical ordering of the members (as there is otherwise *no way to order them*) - which makes it **very** brittle to changes

**Comment by mgravell** [comment]
Side note: if we stick entirely in the realms of WCF translation: another option would be to use `DataContractSerializer` to do the actual serialization. In protobuf-net.Grpc, the actual serializer *doesn't need to be protobuf-net* - it is actually pluggable. Of course, you won't get the *space* savings possible from protobuf, but if you're just after a WCF replacement: it might be enough.

An example of swapping out the serializer is found here: https://github.com/protobuf-net/protobuf-net.Grpc/blob/master/tests/protobuf-net.Grpc.Test.Integration/CustomMarshaller.cs

**Comment by geoffreygeslin** [comment]
Totally agree with you @lanfeust69. From my previous experience with WCF/DataContracts, I'm aware of how hard it is to keep contracts backward compatible without explicit orders (...not to mention type inheritance in datacontracts). Luckily, I have only a few true "external" contracts for out of control clients...

I'm curious if the InferTagFromNameDefault feature does the exact same inference as DataContractSerializer does ...but for now I think I'll keep using DataContractSerializer in place of protobuf. It seems to be the simplest and safest way to go for my context.

Too bad we won't benefit protobuf performance which I red are better thant Datacontractserializer...

Thanks both for your answers !

**Comment by geoffreygeslin** [comment]
Yet, I'm still wondering if protobuf-net.Grpc _could_ handle the problem as I proposed first (although I understand this may sound like be a bad idea).

Can an "inference and reordering" step be done before protobuf-net.Grpc emits the "Grpc /protobuf compatible code" ?

**Comment by mgravell** [comment]
@geoffreygeslin there are tons of ways of hooking this; the *real* question, perhaps, is: where does the data come from? what rules would *you* use? note: I'm happy to implement a `DataContractSerializer` marshaller in the lib, but you'd still need to tell it which types to use it for.

**Comment by mgravell** [comment]
closing this out, because this is really an open-ended thing that doesn't work well with protobuf, and mechanisms already exist in protobuf-net for this, but they are *actively discouraged* because it makes things brittle
