### ISSUE TITLE
'CancellationToken' make Type cannot be serialized whenever  

### ISSUE THREAD

**Issue by haimbell** [protobuf-net/protobuf-net.Grpc#95]
Here is an example of service,
`[Service]
public interface ICountryService
    {
        Task<CountryModel> Test(string id, CancellationToken cancellationToken =default);
    }`

and im getting the following error

> Type cannot be serialized; ignoring: 

if i remove the `CancellationToken` the methods is bounded

**Comment by mgravell** [comment]
Indeed - this is not a type that the library currently supports, although I guess we probably *could*.

Today, the workaround here would be:

``` c#
Task<CountryModel> Test(string id, CallContext ctx =default);
```

A `CallContext` wraps the two underlying gRPC APIs `CallOptions` and `ServerCallContext`, and allows you to convey cancellation - including an implicit conversion operator from `CallContext`, so: you could literally use:

``` c#
CancellationToken token = ...
var result = await myService.Test(42, token);
```

But; maybe we *could* allow `CancellationToken` directly on the signature. Thoughts? is the `CallContext` option sufficient? The advantage here is that it carries cancellation *and* everything else you could ever need - headers, trailers, etc.

**Comment by mgravell** [comment]
Also: side note: I'd probably advise using `ValueTask<T>` in preference to `Task<T>`. The advantage is particularly at the server-side implementation: it becomes trivial for the server to efficiently implement it as either sync or async.

**Comment by mgravell** [comment]
Yes, I agree that it is very attractive to support this pattern - it is, let's face it, the idiomatic "do a thing with optional cancellation" pattern. It isn't supported *today*, but I also don't think it will be hard to add. Let me see what I can do.

**Comment by mgravell** [comment]
If the CI server is happy, I'll see about merging ^^^ later

**Comment by mgravell** [comment]
CI server says "yes"; should be in next deploy! thanks, great suggestion

**Comment by mgravell** [comment]
available from: https://www.nuget.org/packages/protobuf-net.Grpc/1.0.81

**Comment by haimbell** [comment]
@mgravell  that was fast, thanks!

**Comment by mgravell** [comment]
I will try to be slower in future :)
